### ISSUE TITLE
Некорректно работает кнопка i have already the wallet с другого компьютера

### ISSUE THREAD

**Issue by Odny** [swaponline/MultiCurrencyWallet#1290]
## What is working wrong?

Произошла ошибка авторизации при попытке логина с другого компьютера. Открывается чужой кошелек, после ввода своего email-адреса. 

## What should happen instead?

Должна была открыться страница с импортированием ключей, вместо создания нового кошелька, после нажатия кнопки I have a wallet 

## Steps to reproduce

1) открыть swap.online в чистом браузере
2) создать кошелек
3) открыть в другом браузере swap.online и попытаться открыть созданный кошелек
4) bitcoin-адреса будут разными

## Your system charateristics

- Browser: Google Chrome
- OS: Windows 
- Mainnet or Testnet: Mainnet

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

## Additional info
Благоприятно было бы сделать проверку подписки на e-mail, чтобы не переподписывать один и тот же email несколько раз.

**Comment by noxonsu** [comment]
@sdwas сделай плиз, чтоб если человек зашел по swap.online/#importPrivate пропускали подписку (и флаг ставили типа уже прошел этот квест) и показывали окно импорта кошельков
