### ISSUE TITLE
Add global permalink for images

### ISSUE THREAD

**Issue by BootWP** [swaponline/MultiCurrencyWallet#2418]
Задание обновлено и описано в следующем комментарии.

**Comment by BootWP** [comment]
Пока задание с абсолютной ссылкой уже не актуально, 
Остается если есть возможность только второй момент.

И второй момент, может картинки переименовать на чистые именна без лишнего,
в место bch_6d5d5a.svg чтобы было bch.svg
в таком случае я смогу для клиентов в wp plugin добавить иконку если есть http://joxi.ru/Dr8NWkDsoY16d2

**Comment by shendel** [comment]
Логично, что он не находит.
Если вариант попробовать сделать билд с указанием урл по примеру как делается билд для гитхаб-пейдж

**Comment by BootWP** [comment]
Что слышно, делаем это задание? а то я в пустую трачу время на то что можно сделать автоматически один раз и все.

**Comment by noxonsu** [comment]
сейчас очень много ошибок в консоли Error: WebpackRequireFrom: 'imagesUrl' is not a string or not available at runtime 

![](https://screenshots.wpmix.net/chrome_w9l6bK7v8Rs12PM1bXMmcROYfbj3MRwy.png)
