### ISSUE TITLE
No more multi crypto history on homepage; Display only history the latest coin you've visited 

### ISSUE THREAD

**Issue by Oxygen-solutions** [swaponline/MultiCurrencyWallet#2509]
## What is working wrong?

we can't see our transaction anymore on the homepage with all tx of all currency, it will only display the latest currency history that you visited by clicking on a currency name and accessing to his page and tx.
If you just imported the wallet and you've not already visited a currency page, the transaction on the homepage will load infinitely  without any data

**Comment by shendel** [comment]
fixed
