### ISSUE TITLE
Rename .mp4 file

### ISSUE THREAD

**Issue by BootWP** [swaponline/MultiCurrencyWallet#2518]
Переименовать файл 71af1b68ea0f662eb88996ea7a25bf8a.mp4 в alert.mp4

![1583740933195](https://user-images.githubusercontent.com/28696444/76193630-170b9580-61ed-11ea-80c6-79f55d6e0baf.jpg)

**Comment by BootWP** [comment]
Ребята кто может сделать это задание, просто переименовать файл 71af1b68ea0f662eb88996ea7a25bf8a.mp4
в alert.mp4
и в app.xx.js также изменить имя файла на alert.mp4

**Comment by BootWP** [comment]
Отлично спасибо, ну а теперь можем удалить старый файл .mp4, а то он сейчас же лишний
http://prntscr.com/rraz4q

**Comment by noxonsu** [comment]
удалил
