### ISSUE TITLE
widget not working correctly.

### ISSUE THREAD

**Issue by BootWP** [swaponline/MultiCurrencyWallet#2520]
Я попробовал последний билд и чот там не то, 

![index](https://user-images.githubusercontent.com/28696444/76201823-8d63c400-61fc-11ea-9719-0745130cc117.png)

**Comment by shendel** [comment]
![image](https://user-images.githubusercontent.com/1880211/76306183-7e057900-62d7-11ea-86fe-b542e7504733.png)

У тебя что-то со стилями
Последний билд отрабатывает нормально
https://generator.swaponline.site/livedemo/0x91545D6960EC7E059855F33c86a1484814402885/10bd2c05-de42-42e7-8060-2b72dc38f0d9/#/

**Comment by BootWP** [comment]
Обновил, вроде работает но не все валюты открываются https://growup.wpmix.net/mcwallet/#/
вот например я добавил биткойн и SONMToken, вот BTC работает а при нажатии на SONMToken открывается белая страница  http://prntscr.com/reodpg

**Comment by BootWP** [comment]
Done!

**Comment by BootWP** [comment]
Done!
