### ISSUE TITLE
is Litecoin deprecated ? Page not found 

### ISSUE THREAD

**Issue by Oxygen-solutions** [swaponline/MultiCurrencyWallet#2526]
Litecoin currency page not found

**Comment by Naggertooth** [comment]
Litecoin currency page working

![image](https://user-images.githubusercontent.com/24671211/77771060-43316e00-7057-11ea-941d-6b7e16783337.png)
![image](https://user-images.githubusercontent.com/24671211/77771074-49bfe580-7057-11ea-8983-ccd6e9f96af8.png)
