### ISSUE TITLE
Selection of wallet on "Send"

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/MultiCurrencyWallet#2569]
1.  Job. What we need to do in order to implement this feature. Steps

![image](https://user-images.githubusercontent.com/22708849/77504789-63540800-6e72-11ea-92ae-a4a7a0e4c763.png)

Limit the choices to only those wallets with balances.

If there is only 1 wallet with balance, then there is no  need to  popup the wallet selection window. Just proceed to sending directly as if the user selected the right wallet.

If user has no balances, (all 0s), you  need to disable "send" button all together.

If user has balance, but his balance is lower than fee needed to send coins, instead of send interface you need to show that "the balance is too low" message.

2.  Purpose. What this feature is intended to resolve? 

a) Clients benefits
No annoying popups
Improves usablitiy

b) Our benefits
Happy users?

3.  Where 
a) What part of our tech resources this feature intercourse  (Back, front etc.) 
Frontend only.

b) Where’ll we implement this feature (project, space etc.) 

4.  Estimate time of implementation this feature 
15 minutes?

5.  Evidences.
No evidence needed. Just logic

**Comment by noxonsu** [comment]
это после перехода на новые приватники со старых почемуто вывалилось столько криптовалют, ну сейчас уже поздно менять, проще скрыть их

**Comment by noxonsu** [comment]
сюдаже https://screenshots.wpmix.net/chrome_nt6QMEjEIgII24aN2f0xovAoYyZNi0S8.png это в виджете. причем в виджете только eurs добавлены в админке а он все, что в коре подтягивает
