### ISSUE TITLE
Button copy privkey for erc20 = undefinied

### ISSUE THREAD

**Issue by Oxygen-solutions** [swaponline/MultiCurrencyWallet#2588]
![image](https://user-images.githubusercontent.com/59089549/78458303-925b4c80-76b0-11ea-83a9-e6fcb9bdce95.png)
![image](https://user-images.githubusercontent.com/59089549/78458307-9e470e80-76b0-11ea-933c-6bf1c7d9786c.png)

add current ethereum wallet as privkey

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2589
