### ISSUE TITLE
привести виджет билд к основному внешнему виду

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2597]
исторически было, что виджет режим так называется потому что он открывается в маленьком iframe на сайте клиента, поэтому там нет шапки, вырезано все лишнее. но лкиенты которые покупают плагин примерно каждый второй хочет "как на swaponline.io", т.е. чтоб был полный дизайн, со сплаш скрином и т.п. урезанная версия получается вообще пока не нужна. но тут будет проблема "как поменять текст сплаш скрина" и прочие вопросы. возможно стоит продумать какой то хотплаг замену текстов из локализации.

**Comment by shendel** [comment]
Локализацию можно сделать переопределяющейся - подгружать поверх текущей локализации файлы с правками (переопределенными значениями)
https://github.com/swaponline/MultiCurrencyWallet/blob/master/shared/containers/IntlProviderContainer.js#L19

Для "как на swaponline.io" у нас уже есть extarnalConfig, где уже можно настроить наличие банера сверху, доступные валютные пары, доступность пользовательских erc20, и доступность функционала инвойсов

Можно доработать (extarnalConfig) вынести туда максимально все доступные настройки костамизации - от цветовой палитры - до логотипов

**Comment by noxonsu** [comment]
да звучит ок, ладно дождемся пока кто то из клиентов начнет это просить
