### ISSUE TITLE
начать переводить диалоговые окна с оверлея на 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2617]
- [ ] диалоговое окно депозита и отправки не показывать оверлеем, возможно лучше поместить его на страницу с #/BTC/13bFRqtBivrvdBi37kxPtiSUH5qWwaoH15 прямо над историей
- [ ] добавить крестик, для выхода
- [ ] на мобиле должен по прежнему открываться полный экран

оснавня цель, чтоб если чел нажал на send он видел свой баланс там же где он и был раньше

**Comment by shendel** [comment]
Частичная реализация в этом ишью https://github.com/swaponline/MultiCurrencyWallet/issues/2604

Окна снятия (WithdrawModal) можно теперь не только вызывать через actions.modals.open, но и использовать как отдельный элемент при ренденге какой-нибудь страницы (в указаном ишью используется для встраивания формы оплаты в окно просмотра информации о инвойсе)

**Comment by shendel** [comment]
Или имеется в ввиду эти оверлеи?
![image](https://user-images.githubusercontent.com/1880211/79457836-88631300-7ff9-11ea-82ee-d6993ca0b4b9.png)

**Comment by noxonsu** [comment]
дубль
