### ISSUE TITLE
если присоединится к биткоин кошельку получается такое

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2619]
- [x] ![](https://screenshots.wpmix.net/Telegram_GONTSxARVbhrv9UwMXGTxvjfkgPHdboM.jpg)

**Comment by noxonsu** [comment]
если сделать hide то оба скрываются

**Comment by shendel** [comment]
@noxonsu  повторить как на скриншоте не получилось. Как воспроизвести

**Comment by noxonsu** [comment]
0. в инкогнито  перейти по джоин ссылке например https://swaponline.github.io/#/multisign/btc/join/02fb32ca2240ceacb11fbfe3f672c2da80f7b560ed282ef438582fa11ddd1fa630/Qmby76BAPxL19BF9Tsdbt44RsKVsTghtiPH87S2muZAi5T 
2. подтвердить создание мультисига
3. там же начать создавать биткоин мультисиг
2. во втором браузере перейти по джоин линку из п 3 но не присоединятся к кошельку
3. появится призрачный млуьтисиг, который не нужно показывать

**Comment by noxonsu** [comment]
кстати даже созданыне мультисиги, если один скрыть то скрываются и остальные тоже
