### ISSUE TITLE
Balance on multisig jumping up and down

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/MultiCurrencyWallet#2668]
## What is working wrong?

After i signed multisig, transaction appeared in transactions for multisig wallet, but when i look at wallet balance it sometimes appears and sometimes disappears

This is very bad

## What should happen instea and d?

Uhmm. It shoudl work?

The balance change  must be immediate after confirming  a multisig transaction. And if you created a 1st signature transaction it should not effect your balance, but the  transaction should appear in the transaction list as "need signature"

Now this is why displaying resulting balance is important!!!

I have said this many times

If you display resulting balance, you can show transactions in  chronological order, and even those that are unconfirmed. But if they are not confirmed, or require additional signature, these trasnactions will standout because they do not effect resulting balance.

The dollar amounts that are displayed now are taking  space,  but they could just appear on hover over the amounts (resulting balance or transaction amount)...

Please do it the way i ask.

## Steps to reproduce

Visit wallet and send multisig transation and watch your balance on main page

## Your system charateristics

![image](https://user-images.githubusercontent.com/22708849/79544522-d0d10e00-8097-11ea-9ba8-455db0161a05.png)

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7

Mac OS Mojave 10.14

- Mainnet

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots

https://storage.googleapis.com/test-bucket-33/conversations/Apr-17-2020-10-33-56.mp4

**Comment by noxonsu** [comment]
после фиксов баланс на мультисигне не учитывается в общем балансе https://screenshots.wpmix.net/chrome_lCiF5Gh2B2MZnQUqe6KvjVCP9X3TFPad.png 

плюс нужно сделать, чтоб баланс не показывался общий (типа загрузка) пока не опросим все кошельки
