### ISSUE TITLE
После завершинии странзакции не показывает сумму

### ISSUE THREAD

**Issue by BootWP** [swaponline/MultiCurrencyWallet#2680]
В место сумме показывает ноль
http://prntscr.com/s1fppn
https://swaponline.github.io/#/btc/tx/d18c14fef9c170f9f57ecacc264ea2c8a39d8851b96e4757d08def92eca4cb20

**Comment by noxonsu** [comment]
очень часто такая ошибка появляется. 

- [ ] 
- [ ] вернуть final balance
- [ ] поправить глюк с переносом txid на вторую строку
- [ ] нужно пока ссылку странзакции (https://screenshots.wpmix.net/chrome_cHjlukfehxx2VGAoL31k4aghBC3gMpO0.png)  все таки в отдельном окне вести на https://live.blockcypher.com/btc/tx/2509e5b65ed362557fcf2104e89f3c2430ceecc6a3275556c1b966eb641fe092/ , пока что наш эксплорер оставляет желатль лучшего, лучше на внешний

**Comment by Pasha8914** [comment]
1 - непонятно зачем тебе конструктор
MultiCurrencyWallet/shared/components/modals/InfoPay/InfoPay.js
почему просто не работать с пропсами в рендер. Из за того, что ты назначаешь (@shendel )
 стейт в конструкторе, а он выполняется только 1 раз, при изменении isFetching, значение стейта не меняется и везде остаются нули. 
только не нужно лепить дид апдейты всякие, сделай вот так

             ` <span><strong> {amount || ZERO_AMOUNT}  {currency.toUpperCase()} </strong></span>
`
(принимаешь эмаунт напрямую из пропс и если его нет выводишь нулевое значение
`const ZERO_AMOUNT = 0`
)
т.е оставить как есть, только удалить часть конструктора
![image](https://user-images.githubusercontent.com/43392281/79677409-52f63980-8234-11ea-9d5d-0a85b6360976.png)


2 -  componentWillMount нельзя использовать, он устарел!!

**Comment by Naggertooth** [comment]
Ошибку 100% удалось отловить при открытии второго окна с транзой (кликнув по ссылке в транзе)

**Comment by shendel** [comment]
@Pasha8914 InfoPay был изначально (вроде рустам делал @trubnikovr )
По правильному, я с тобой согласен - лучше вообще все перенести полноценно в роутер (pages/Transactions/), непосредственно в метод render этого контролла, а не городить то что есть, но не хотелось дублировать код, к тому же сам InfoPay отдельно вызывается как окно, с уже переданными данными.
#2 - да я помню, еще не привык, машинально "Will", немного путаницы они добавили, убрав WillMount, но оставив WillUnmount
Главное, удалось воспроизвести @Naggertooth ,

**Comment by noxonsu** [comment]
в таблицу добавить еще

- [ ] miner fee 
- [ ] вернуть est time to confirmation
- [ ] если транза подтверждена, то количество конфирмов (confrimations: n) 
- [ ] в первые полсекунды загрузка глючная, надо добавить красивый плейсхолдер но это @nthgness пусть сделает он спец по плейсхолдерам https://screenshots.wpmix.net/chrome_VsAN1X7on7jS8I88mDNE7oXnYEYVTKWl.png

**Comment by noxonsu** [comment]
1. отправил деньги с одного кошелька на свой же (на 2fa)
2. после отправки показало это https://screenshots.wpmix.net/chrome_L2Pcg8qc7ppJvwZhvrUZ3dYM7x6WiSNH.png 
3. рефреш не помогает
