### ISSUE TITLE
не копируется адрес

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/MultiCurrencyWallet#2681]
на главной выбираешь валюту и пытаешься скопировать - не копирует (пытаешься скопировать из тулбара)
![image](https://user-images.githubusercontent.com/43392281/79625661-d13bd880-816d-11ea-8de6-d9dd33284796.png)

https://drive.google.com/file/d/1jv6X6RkPxp3A5rPb2lgUN72Gau1QD2Fs/view?usp=sharing

**Comment by noxonsu** [comment]
- [ ] нужно скрыть эту фичу для сафари

**Comment by noxonsu** [comment]
плюс у тебя он почемуто скрывает адрес который можно легко скопировать снизу названия кошелька 
![](https://screenshots.wpmix.net/chrome_P9ZZCd2yKDJCdnbJkiv2SGbXP3IfgcI4.png)
