### ISSUE TITLE
send: It would be nicer if send dialogues was on 1 screen. without having to click

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2687]
It would be nicer if send dialogues was on 1 screen. without having to click

The source wallets would  be displayed in dropdown. by default - the last used wallet (for sending) or wallet with biggest balance in usd equivalent.

![send  dialogue](https://user-images.githubusercontent.com/22708849/79574990-b748ba00-80c9-11ea-95c5-0296667474a2.png)

And isn't it nicer if  cancel button is on  the left?

And  after you click  withraw, there should be a confirmation screen asking you to confirm everyhting. You should be  able to see:
* what wallet you are sending from
* what address you are sending to
* amount (including usd equivalent)
* transaction fees you are paying (including usd equivalent)

_Originally posted by @vladiuz1 in https://github.com/swaponline/MultiCurrencyWallet/issues/2670#issuecomment-615248674_

**Comment by vladiuz1** [comment]
# confirmation  screen

The confirmation screen can be universal for a few scenarios:
1. Confirmation of simple wallet transaction
2. Multisignature wallets, when  the other pary signs the trasaction
3. 2FA comfirmation.

in the 3-rd option yo would see an additional "2FA" input where you enter the code.

Confirmation screen  must have its own URL, so  you can return to it.

After you click withdraw, transaction need to be created with flag "initiated", and should be recorder in  the  list, and even if you don't  confirm t he  transaction, it should appear in the transaciton list with special background color with "confirmation required" tag. And you can  either cancel it or sign.

So confirmation screen is multipurpose, intuitive, and logical.

**Comment by vladiuz1** [comment]
The transactions details = confirmation screen. It should be the same thing basically.

We need to make design mock-ups for every scenario, bot desktop and mobile.

This is the core of all.

**Comment by vladiuz1** [comment]
# Transaction ledger service

If we make trnsaction ledger service on the backend with the functionality to save transactions on all stages, we need to remove the "requests" folder

![no-requests](https://user-images.githubusercontent.com/22708849/79725488-f8231780-82f1-11ea-9b22-8c8713446c01.png)

Instead, this will be a filter on regular transaction list:

![invoice-the-right-way](https://user-images.githubusercontent.com/22708849/79728253-4b976480-82f6-11ea-9c6c-6db18547f8f3.png)

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/2687#issuecomment-616097987
The confirmation screen can be universal for a few scenarios:
- [ ] Confirmation of simple wallet transaction
- [ ] Multisignature wallets, when the other pary signs the trasaction
- [ ] 2FA comfirmation.
Связанное ишью https://github.com/swaponline/MultiCurrencyWallet/issues/2625

**Comment by shendel** [comment]
So all transactions are now entirely different beasts. They can be tagged as "initiated", "signed", "partially signed", "confirmed", "confirmed 2" - confirmed by blockchain (2 confirmations). But the don't have to be in blockchain at all, they on every initiation need to remain in our transactions service. Blockchain-agnostic to the frontend. Frontend should only know how to sign blockchain-specific transactions and that's all.

**Comment by vladiuz1** [comment]
![invoice](https://user-images.githubusercontent.com/22708849/79769673-178f6400-8335-11ea-90f9-36abc9f0a0f1.png)

**Comment by vladiuz1** [comment]
![invocie](https://user-images.githubusercontent.com/22708849/79769779-3857b980-8335-11ea-889f-c0abcceb7f45.png)

**Comment by noxonsu** [comment]
перенес по истории правки в это ишью: https://github.com/swaponline/MultiCurrencyWallet/issues/2670

**Comment by noxonsu** [comment]
сделали промежуточную версию 
![](https://screenshots.wpmix.net/chrome_Ccd7pCVk0eJfRy6uh1mX5igv1QUMXdIn.png)

- [ ] я думаю можно убрать блур остальных элементов, не удобно уходить с этого экрана сейчас вообще. да и логичнее было бы оставить все элементы на своих местах, если они там остануться, то юзер их даже не заметит 
- [ ] при открытии дропдауна выбора едениц измерения появляется левый скрол https://screenshots.wpmix.net/chrome_j71qOtVNRVCi1Q3jRuBteVDKbwf63kQT.png 
- [ ] в дропдауне едениц если выбран биткоин то не показывать сумму сверху (сейчас там баланс кошелька, он уже не имеет смысла так как покзаан выше на странице). но если выбираем рубли или доллары, то показывать сколько это в биткоинах https://screenshots.wpmix.net/chrome_lW4RPG6BQXfwtB3UYQWPyIsw3tL19CRD.png . т.е. если чел  перешел на отправку биткоина, и хочет отправить 1000 рублей, то ему в инпуте показывется 1000 RUB а сверху мелким серым "0.0002 BTC will be sent"
- [ ] вместо рубля нужно показывать дефолтную валюту, это @Pasha8914 сделает пусть, плюс связать с курсами правильно
- [ ]
