### ISSUE TITLE
English

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/MultiCurrencyWallet#2692]
![image](https://user-images.githubusercontent.com/22708849/79724240-dd4fa380-82ef-11ea-8755-c853ed4fc966.png)

НИКОГДА
НИКОГДА
НИКОГДА

НЕ делайте google translate

И не ставте результаты на свопонлайн

ВС[ЕГДА ИСПОЛЬЗУЙТЕ НАТИВНОГО ПЕРЕВОДЧИКА СО  ЗНАНИЕМ ТЕМЫ 
НАЙДИТЕ ОДНОГО ХОРОШЕГО И ПУТЬ РАБОТАЕТ

1. ИСХОДНЫЙ ТЕКСТ НА РУССКОМ 
2. ПЕРЕВОД НАТИВОМ НА АНГЛ
3. ПОТОВ ВЫКЛАДЫВАЕМ В ПРОД

Иначе это стыд!

Лучше пусть по русски будет

Иначе выглядит ОЧЕНЬ херово

Made in china уже даже не так плохо как made in Russsia

Это вопрос национального позора 

НЕЛЬЗЯ ТАКИЕ  ТЕКСТЫ СТАВИТЬ НА ПРОДУКТЫ в ПРОДЕ

**Comment by noxonsu** [comment]
удалил
