### ISSUE TITLE
Use only Google Fonts and no more than three

### ISSUE THREAD

**Issue by BootWP** [swaponline/MultiCurrencyWallet#2704]
# Problem

Используются 5 шрифтов, два от гугл и три локальные.

От гугл
Roboto и Roboto Mono.

Локальные
CerebriSans Regular
CerebriSans Bold
CerebriSans SemiBold

Inter-Regular
Inter-Medium
Inter-Bold
Inter-Semibold

Manrope-Regular
Manrope-Medium
Manrope-Bold

# Task

Нужно использовать максимум 3 шрифта, это по правилам дизайна,
но так как все шрифты не на много различаются то оставим только два,
и все от гугл чтобы мы избавились от 1mb и от лишних файлов и папки fonts.

В место Inter, Manrope и CerebriSans использовать Roboto
они не на много различаются, похожее они больше на Open Sans,
но если подключим и Open Sans то Load Time: Slow

![1587618409735](https://user-images.githubusercontent.com/28696444/80061367-c2706f80-8539-11ea-8900-7f8db7d66fdc.jpg)

Так что пока обойдемся шрифтом Roboto

В файле app.xxx.css изменить старые названия шрифтов на Roboto
и подобрать для каждого и нужный font-weight:
Roboto:400,500,700,900

**Comment by noxonsu** [comment]
Согласен, давайте попробуем отставить робото, т.к. у всех он закеширован

**Comment by vladiuz1** [comment]
Важно еще

Все шрифты грузить с локально копии - а не с гугловского cdn.

Все сторонние ссылки нужно постепенно убирать

**Comment by noxonsu** [comment]
если грузить локальные то наверно можно оставить красивый шрифт

**Comment by BootWP** [comment]
Тогда нужно решить какие два шрифта оставить, и остальное убрать.

**Comment by noxonsu** [comment]
![Screenshot_2020-05-20-23-19-52-471_com android chrome](https://user-images.githubusercontent.com/2914674/82493349-7ab91580-9af0-11ea-9daa-7a7fa61144ed.jpg)

Ну вот эти симпотные

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_HdqS3D1C5kH8ouhiu95g0UtorvJH9Jx9.png) тут без засечек надо сделать
