### ISSUE TITLE
Tokens Percentages

### ISSUE THREAD

**Issue by BootWP** [swaponline/MultiCurrencyWallet#2707]
Нужно добавить процент для токенов, а также чтобы можно было процент добавить из вне через переменную, больше деталей к noxonsu.
В настройках WordPress Это выглядит так:
![photo_2020-04-26_08-21-57](https://user-images.githubusercontent.com/28696444/80298802-94d53180-8798-11ea-9839-6cdd99e24400.jpg)

**Comment by noxonsu** [comment]
@BootWP в админке секуцию Percentage переименуй в "Transaction fees". и надо ниже биткоина добавить инпут "BTC Adress where to collect fees" и так же ниже Ethereum
![](https://screenshots.wpmix.net/chrome_g95oZ2AOmgEOtAp7GAA7TPbqhwTapIWK.png) 
под "Other tokens" подпиши просто текста "Address the same as Ethereum" без инпута.

**Comment by BootWP** [comment]
@noxonsu 
Добавил в этом виде http://prntscr.com/s787l8
так будет ок?

**Comment by BootWP** [comment]
Вывел данные на странице в переменную widgetERC20Comisions

выгладит это все вот так 
![image](https://user-images.githubusercontent.com/28696444/80767497-b5163f00-8b50-11ea-9fa4-240a6bad5138.png)

**Comment by shendel** [comment]
только вместо 'other' - 'erc20'. Так не будет путаницы, при возвращении остальных блокчейнов

**Comment by BootWP** [comment]
Поменял 'other' на 'erc20'.
