### ISSUE TITLE
в виджет режиме надо убрать снизу экспорт приватников

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#2709]
в виджет режиме надо убрать снизу экспорт приватников

**Comment by noxonsu** [comment]
либо просто сделай чтоб открывалось сохранение ив вод 12 слов. а вообще надо уже баннеры внедрять туда как на основном

**Comment by noxonsu** [comment]
ниего не поменялось ![](https://screenshots.wpmix.net/chrome_GjDGohP7BmlrLdMV67cru7cOTJ8sRgkL.png)

**Comment by noxonsu** [comment]
- [ ] заодно надо убрать битый лого с виджета вообще https://screenshots.wpmix.net/chrome_l3whTOnB04PFQyNggaknaO4T710PPfMG.png если лого не прописан то не показывать его
