### ISSUE TITLE
Add logo, fix zero.

### ISSUE THREAD

**Issue by BootWP** [swaponline/MultiCurrencyWallet#2718]
## What is working wrong?

1. Лого в шапке не отображается, 

![image](https://user-images.githubusercontent.com/28696444/80862163-80eb6d00-8c7b-11ea-9a83-93a75fc480f6.png)

2. Какой та ноль '0' показывается на странице create wallet https://swaponline.io/#/createWallet
![image](https://user-images.githubusercontent.com/28696444/80862204-c445db80-8c7b-11ea-995a-67c24b1c0143.png)

**Comment by noxonsu** [comment]
это касается только виджета как я понял. ноик отсутсвуте, @BootWP скажи как в инкогито моде повтрить баг

**Comment by noxonsu** [comment]
подтверждаю, при заходе в инконнито виден нолик

**Comment by BootWP** [comment]
Лого появился спасибо, но стили для лого нужно подправить так как если лого не квадратный то очень маленьким отображается. 
Там добавлено `max-width: 55px,`
правильнее будет так:
```
max-height: 55px;
width: auto;
display: block;
```
![image](https://user-images.githubusercontent.com/28696444/81161668-97076f00-8f94-11ea-91dd-f3a37a981b5d.png)

**Comment by noxonsu** [comment]
поправили в другом пуле вроде
