### ISSUE TITLE
Инвойсы - жуткие лаги и баги отрисовки

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#2732]
В рамках https://github.com/swaponline/MultiCurrencyWallet/issues/2675

- [x] Прелоадер глючит
- [x] Есть глюк, при переходе на ссылку - не удается ввести сумму (баг с котировками, возможно не прогрузились)
- [x] На странице инвойса не понятно как кнопки оплаты (не определяет плательщика)
- [x] В списке всех инвойсов - кнопки управления (Оплатить, Отклонить) - вообще не понятно почему так стало, надо починить

**Comment by noxonsu** [comment]
пока инвойсы от всех скрыты
