### ISSUE TITLE
don't show "black" background in ERC20 icons

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2736]
![](https://screenshots.wpmix.net/chrome_R7IlbMlMDyEA8bKiFxZkAiamFHSbKijq.png) if admin doesn't set background color of icon, jost show icon

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/blob/master/externalConfigs/testnet-default.js#L39
Это уже есть
