### ISSUE TITLE
firebase bundle optimization

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2748]
![](https://screenshots.wpmix.net/Telegram_nck4V2ERreAmomLKNd8dI2fAbs8T0daR.jpg) 

вот тут разработчики вообще жалуются что 100кб это много, а у нас 1.6 !

https://github.com/firebase/firebase-js-sdk/issues/332 

может что то в вебпаке надо указать, чтоб собиралась браузерная версия легкая?

**Comment by Naggertooth** [comment]
https://github.com/firebase/firebase-js-sdk/issues/2241#issuecomment-620120180

Либо делать свою сборку, что надо изучать
Либо ждать

**Comment by iower** [comment]
Outdated
Reason: #3985
