### ISSUE TITLE
#/btc/tx/.. show final balace for all output adresses

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2752]
https://swaponline.github.io/#/btc/tx/d0e67c93c1a60ed533a9424c7751fc6818487d7f1ec681ae82a12aa55cc6fbcd 

![](https://screenshots.wpmix.net/chrome_6slkBjVuFZdN5bd2YZ7qGEMHlMbljPSb.png) показывать финальные балансы и отправителя и получателя, т.е. писать как то так

Final balances:
Azx...FG (your) 0.009
Frg...DD 0.001

your ставится если в локалсторадже приватник от этого адреса

**Comment by shendel** [comment]
В рамках ишью https://github.com/swaponline/MultiCurrencyWallet/issues/2693
Это нужен свой сервер, который будет отдавать информацию о транзе
Проблема в том, что второго финала нет в самой транзе

Если посмотреть на эту транзу на блоккрипере
![image](https://user-images.githubusercontent.com/1880211/82474916-6b2bd380-9ad4-11ea-9c2f-5db4cfb3bf91.png)

Красное - это наш текущий final balance

**Comment by noxonsu** [comment]
тоесть битпей не отдает второй utxo?

**Comment by noxonsu** [comment]
"Alexander Shestopalov, [28.05.20 11:39]
можно на стороне реакта - опрасить балансы, заброадкастить транзу - и сбросить данные к нам"
