### ISSUE TITLE
submenu: "copy private key" open new window

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2847]
![](https://screenshots.wpmix.net/Telegram_AjMZUaod4caBIleNhg8CXtwiBqced40K.png)

**Comment by Pasha8914** [comment]
@noxonsu новое окно браузера? или модалку?
если новое окно браузера то получается нужно убрать ошибку с 2умя вкладками своп онлайн? или как?

**Comment by noxonsu** [comment]
Same thing needs to happen for the copy address link as it too can not be copied.
