### ISSUE TITLE
fontawesom only .woff needed

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2848]
создай issue, Для fontawesome оставить только файлы шрифтов формата .woff

**Comment by BootWP** [comment]
Done!
![image](https://user-images.githubusercontent.com/28696444/85154036-9a626b80-b25f-11ea-87d1-5492ea791400.png)
https://github.com/swaponline/multi-currency-wallet-pro/commit/16114f7d230503b23b6f82706dc92e26578e25ab
