### ISSUE TITLE
add recommended price to erc20tokens config

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2851]
Hi, For example, if I add an ERC20 token, the wallet will show that 1 token is worth 1 dollar. Where can I change the correct value (rate) of the token?

![](https://screenshots.wpmix.net/chrome_Ubfp29ydFaQKdImSPbS7cgJityvrBxb1.png)

**Comment by shendel** [comment]
Это решение? https://github.com/swaponline/MultiCurrencyWallet/pull/2852

**Comment by noxonsu** [comment]
https://github.com/swaponline/multi-currency-wallet-pro/issues/15

**Comment by BootWP** [comment]
Done!
https://github.com/swaponline/MultiCurrencyWallet/pull/2852#issuecomment-646921127
