### ISSUE TITLE
tour design improves

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2866]
(screens in telegram)

Please remove the highlight from the balance portion as we want to focus the user on the buttons only.

Please remove the highlight from the balance portion as we want to focus the user on the buttons only.

Please add a period here at the end if this sentence.

This tip runs off the page. Please fix.

Please narrow the highlight box on these buttons to only show the button and not so much white space.

Please change this to read: "That's it! Lets get started."

And just change the "next" button to say "close" instead.

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/84664232-92ee4a00-af61-11ea-901c-c741a0d68354.png)
сделал все кроме этого, кто разберется - молодец, я не смог

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/2878

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2877
