### ISSUE TITLE
Logo Displacement When Back Button Clicked.

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2869]
See screenshot. This occurs when you open the USDT wallet and then click the back button.
![Screenshot_20200612-081004_Chrome](https://user-images.githubusercontent.com/66849208/84546281-07f62100-accf-11ea-86d6-6a55a8131f3b.jpg)

**Comment by iower** [comment]
The header has been completely rewritten
![image](https://user-images.githubusercontent.com/35522011/99936768-bc6b9700-2d85-11eb-8a51-1a1d9c16896d.png)
