### ISSUE TITLE
Dark theme 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2871]
example https://coinmarketcap.com/
![](https://screenshots.wpmix.net/chrome_NgCw15xK69tPMg1iG7sHiFyuE2LhIuWs.png)

![](https://screenshots.wpmix.net/Telegram_qMVYU4pg3IlLisuDRVFKxl3sOlIMwdOX.png)

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/Telegram_DJEifR8p4OXermasMNcq2E5DWX19XgQQ.png)

**Comment by Bitplicity** [comment]
Any luck?

**Comment by Pasha8914** [comment]
I've already started

**Comment by Pasha8914** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2934

check progress here

**Comment by Bitplicity** [comment]
Great, thanks!

**Comment by noxonsu** [comment]
should be darker

![](https://screenshots.wpmix.net/chrome_yKmmolMPe89YfaETtVF0V0V8R0LyqCq3.png)
