### ISSUE TITLE
window.exitLink = ''; add exit link to config 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2872]
если плагин установлен в подпапке /wp/Wallet то при клике на exit юзера отправляет на /wp-login.php?action=logout исправить это можно если @BootWP пропишет корректную ссылку на выход в index.html

**Comment by BootWP** [comment]
Добавил на WP ссылку на logout url window.logoutUrl = '';
![image](https://user-images.githubusercontent.com/28696444/84575744-4287b880-adb8-11ea-9497-c47fff1fe19b.png)

**Comment by BootWP** [comment]
Ссылка на наш новый сайт если что здесь https://wallet.wpmix.net/
