### ISSUE TITLE
tour: mobile overlapping

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/MultiCurrencyWallet#2878]
![image](https://user-images.githubusercontent.com/43392281/84664232-92ee4a00-af61-11ea-901c-c741a0d68354.png)
сделал все кроме этого, кто разберется - молодец, я не смог

**Comment by shendel** [comment]
![image](https://user-images.githubusercontent.com/1880211/84710258-86232380-af6c-11ea-9bbd-074b65c75429.png)

**Comment by shendel** [comment]
![image](https://user-images.githubusercontent.com/1880211/84710378-c08cc080-af6c-11ea-9194-97e256cedcf9.png)

**Comment by shendel** [comment]
Для мобильных нужно прописать, чтобы окно тура было от левого края экрана до правого во всю ширину
