### ISSUE TITLE
createWallet: remove PIN from eth,erc20

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#2880]
сейчас можно активировать пин на erc20 насколько я понял реально оно не работает? так как не сделали еще мультисиг и 2fa для эфира. следовательно надо пропускать все секьюирити опции сразу для не битка

**Comment by shendel** [comment]
Не удалось воспроизвести. При выборе эфира или токена - сразу добавляет их и перенаправляет на главную страницу
