### ISSUE TITLE
bitcoinjs v5 - use not deprecate methods (psbt)

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#2889]
Обновить код отправки btc, используя новые методы библиотеки

**Comment by noxonsu** [comment]
новая версия должна уже ументь отпавлять на такие адреса bc1q2nwcpn8vlgqz050320trknnvyrtpkcu5ch2ss5 

https://screenshots.wpmix.net/chrome_TbWGfrjYnvaaimdgv1laW7xB0KxiIQOc.png

**Comment by noxonsu** [comment]
https://github.com/bitcoinjs/bech32/issues/25#issuecomment-413527513
