### ISSUE TITLE
Embed shortcode to wallet footer

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2899]
Hello, 

I need to add a shortcode to the wallet. This shortcode is to be displayed in the footer of the wallet below the transaction and exchange buttons. [ccpw id="643"]

Thanks.

**Comment by Bitplicity** [comment]
?

**Comment by Noah-svg** [comment]
也可以看看这个 [https://github.com/uduncloud](https://github.com/uduncloud) 对你有帮助
