### ISSUE TITLE
Fix SMS page and Icon size on mobile

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2907]
The sms page shows huge flag icons on the mobile device. It also shows 12 word secret phrase. Please fix this page. 

![Screenshot_20200618-105030_Bitplicity](https://user-images.githubusercontent.com/66849208/85035812-96e0be80-b151-11ea-98ac-27bd9eb0ee37.jpg)

Thanks

**Comment by shendel** [comment]
placeholder https://github.com/swaponline/MultiCurrencyWallet/pull/2908
icon of country flag https://github.com/swaponline/MultiCurrencyWallet/pull/2904


Can you check bug with the size of the flag of the country at https://swaponline.github.io/#/ and confirm it?

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2909

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_HtlqTJ41ncjivyvHjdfi4FQdnwmK0HAo.png) now it's ok in WP
