### ISSUE TITLE
Question on fees

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#2914]
It is to do about the way the fees are collected for the operators.
Hi mate have a question , the fees are added when someone withdraws there coins/tokens from the web wallet, but say for example someone saves there private keys then adds that wallet, for example to there metamask and moves the coins to another wallet, would be that a way for them to get around paying any fees??
Ok see that's a way for people to get around paying the fee because they can export the private key into another wallet like metamask and then move the funds and knowing people in crypto they would catch onto that fast , adding the fee to the trades would get rid of that problem.
So i was wondering if we could have it so the fees can be added to each actual trade , to stop people from doing this ??

**Comment by shendel** [comment]
this is not possible, alas. We can add options for hide the "show private key" in dropdown menu, optionally. here you need to think

**Comment by LogicDEX** [comment]
ok so the fee cant be applied to trades ??
well the option to make it so it doesnt show is a option

**Comment by shendel** [comment]
fee for trades in process. will be later

**Comment by LogicDEX** [comment]
is there a time frame for this and will it be possible to have the option to hide private key in menu??

**Comment by shendel** [comment]
May be today or tomorrow. Task created
