### ISSUE TITLE
Add option to customize Faq text

### ISSUE THREAD

**Issue by JoaoCampos89** [swaponline/MultiCurrencyWallet#2915]
# Problem

What the moment there is no option to customize faq text on the plugin

# Task

Add tab to edit all possible text or hide cards that are not needed. I understand this could be done via scripting, but would be nice, if is possible to inject custom cards on places on the swap online pages 

# Purpose

(What this feature is intended to do or solve?)

# Area

(What part of our tech resources this feature intercourse: backend, frontend etc.)

(Where’ll we implement this feature: project, space etc.)

# Estimate time of implementation

# Additional data

**Comment by NotEternal** [comment]
#3879
