### ISSUE TITLE
Sms page showing blank screen!

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2917]
Hi, 

After updating to the newest plugin release...

When you try to create a new sms protected wallet, after you save your secret code it takes you to a blank page with no place to enter your telephone number.

Please help.

**Comment by shendel** [comment]
failed to recreate
give more information

**Comment by Bitplicity** [comment]
Here you go

**Comment by shendel** [comment]
https://wallet.bitplicity.com/

**Comment by Bitplicity** [comment]
https://wallet.bitplicity.com/wp-content/uploads/2020/06/20200622_003936_edited.mp4

**Comment by Bitplicity** [comment]
https://wallet.bitplicity.com/wp-content/uploads/2020/06/20200622_004131_edited.mp4

**Comment by shendel** [comment]
interesting....
@Pasha8914 can re-check on phone?
