### ISSUE TITLE
ghostx.live: Withdrawal error

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#2921]
## What is working wrong?

keep getting error when trying to withdraw BTC from site, multipul people are getting this error
error is in screen shot at bottom

## What should happen instead?

it should withdraw as per normal 

## Steps to reproduce

Just a normal withdrawal procedure, so just try to withand you get the error

## Your system charateristics

- Browser: Chrome (not sure on other peoples computer
- OS: windows (not sure on other peoples computers
- Mainnet or Testnet: Main

## Does this affect atomic swap flow?

- [ ] yes
- [x ] no

## Are real funds at risk?

- [ ] yes
- [x ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...
![Screenshot (120)](https://user-images.githubusercontent.com/57644895/85269834-0b499380-b4ab-11ea-8bdb-1995391922a6.png)

## Additional info
I have got this error from various people on GHOST X

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2925 probably fixed (admin of ghostx.live must update the plugin in wp-admin - updates - check updates)

**Comment by LogicDEX** [comment]
Hi updated and preformed a withdrawal, didnt get a error but it just sites there pending , been over 10 minutes now 
![Screenshot (121)](https://user-images.githubusercontent.com/57644895/85290006-dd744700-b4ca-11ea-8242-e1af9f3f4e6c.png)

**Comment by LogicDEX** [comment]
Also tested eth withdrawal and getting the error as well 
![Screenshot (122)](https://user-images.githubusercontent.com/57644895/85291660-57a5cb00-b4cd-11ea-9a97-7d2227574de4.png)

**Comment by LogicDEX** [comment]
> Also tested eth withdrawal and getting the error as well
> ![Screenshot (122)](https://user-images.githubusercontent.com/57644895/85291660-57a5cb00-b4cd-11ea-9a97-7d2227574de4.png)

Actually it did go through even though i got that error

**Comment by LogicDEX** [comment]
seems eth withdrawals are fine i tested again

**Comment by LogicDEX** [comment]
Plugin version: 1.0.66 | Build version: 528e6d | Updated: 00h : 01m : 09s ago.
updated to latest build but it just sits there processing still

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2930

**Comment by noxonsu** [comment]
normal and pin works now
