### ISSUE TITLE
exporting pin protected multisig wallet

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#2927]
ok having problem also importing the private key for the pin protected wallet, is there a way to do this as the private key imports a standard wallet , not the multi sig wallet that it is

**Comment by shendel** [comment]
re create pin wallet with some pin-code

**Comment by LogicDEX** [comment]
no to use the private key to import it to another wallet , not on the site

**Comment by noxonsu** [comment]
I think we should create an instruction on how to withdraw funds from SMS and pin protected and multisig outside of our software, for example, Electrum
