### ISSUE TITLE
ghostx.livebalance from pin protected wallet not reflecting on exchange page

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#2929]
## What is working wrong?

Balance in btc pin protected wallet not showing in exchange balance

## What should happen instead?

I believe going to exchange that balance in pin protected wallet should be able to be used for trade and show there

## Steps to reproduce

- steps
- to
- reproduce

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [x ] no

## Are real funds at risk?

- [ ] yes
- [x ] no

## Screenshots

![balance](https://user-images.githubusercontent.com/57644895/85313381-88e0c400-b4ea-11ea-968a-744cb7fc554b.jpg)
![balance1](https://user-images.githubusercontent.com/57644895/85313397-8e3e0e80-b4ea-11ea-903e-53f72f523085.jpg)

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/2889

https://github.com/swaponline/MultiCurrencyWallet/issues/2892

https://github.com/swaponline/MultiCurrencyWallet/issues/2897

https://github.com/swaponline/MultiCurrencyWallet/issues/2898

Pin-prorected will be ready today, maybe tomorrow
