### ISSUE TITLE
Add Wallet & Exchange Shortcodes Pls.

### ISSUE THREAD

**Issue by zachkinsey** [swaponline/MultiCurrencyWallet#2931]
# Problem
The wallet/exchange has no shortcodes. Meaning that I can't add them to any location on my site. 

They're not modular at all.

# Task

Breakdown the wallet/exchange into shortcodes, perhaps resize/restyle them to better fit more implementations by default.

# Purpose

Wallet doesn't fit that well with my Theme. I have everything crypto related inside a members area with a User Panel on the left. The wallet/exchange is just a stand-alone page.

# Area

Potentially both front and backend.

# Estimate time of implementation
Not too long?

**Comment by noxonsu** [comment]
the plugin has [mcwallet] shortcode (you can try it), but we hide it due to many compatibility issues, all themes have their own CSS styles, header, footer etc...
