### ISSUE TITLE
Make editable or remove link

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2965]
Please allow me to edit where this link goes or remove it entirely. See screenshot.

![Screenshot_20200627-004720_Chrome](https://user-images.githubusercontent.com/66849208/85914962-5946fa00-b811-11ea-82d0-ab44af207f3a.jpg)

**Comment by noxonsu** [comment]
remove

**Comment by noxonsu** [comment]
Just remove link

**Comment by Pasha8914** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2984
