### ISSUE TITLE
Buy Token page problem

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2978]
Problems with dark mode design when you click "buy token" from wallet dropdown menu. See screenshot. Should just route to the exchange page. 

![Screenshot_20200629-193645_Chrome](https://user-images.githubusercontent.com/66849208/86066476-351d3000-ba40-11ea-83ce-517d07b61935.jpg)

**Comment by Bitplicity** [comment]
Please just have the "buy token" link route to the Exchange page instead of this replica exchange page.

**Comment by Pasha8914** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2984
