### ISSUE TITLE
:How to export wallet" button problem.

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2980]
This "how to export wallet" button is not showing as an option on all wallets. Only on sms wallets.

![Screenshot_20200629-195434_Chrome](https://user-images.githubusercontent.com/66849208/86067429-d9a07180-ba42-11ea-8f02-1df9c0e22c35.jpg)

Also, the export download that you get after clicking "download" is not readable and the last link in the file sends you to this page:  https://swaponline.github.io/2fa_wallet.zip

See screenhot: 
![Screenshot_20200629-195706_Chrome](https://user-images.githubusercontent.com/66849208/86067613-4582da00-ba43-11ea-9232-3891075b6057.jpg)

Also please remove empty space: 

![Screenshot_20200629-195524_Chrome](https://user-images.githubusercontent.com/66849208/86067677-677c5c80-ba43-11ea-8c0a-3197572053b4.jpg)

**Comment by shendel** [comment]
2h30min

**Comment by noxonsu** [comment]
@shendel please separate time counter for bug fixes and features because bug fixes are our job, this must be free
