### ISSUE TITLE
Add coinmarketcap api for calc exchange rate

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2982]
When a user trys exchange an erc token on the exchange page, it doesn't show the amount in Canadian dollars. When you click "CAD" no conversion occurs, nothing happens. 

[Screenshot_20200626-203608_Chrome](https://user-images.githubusercontent.com/66849208/86067903-f9846500-ba43-11ea-90c4-4edfe03fa137.jpg)
![Screenshot_20200626-203606_Chrome](https://user-images.githubusercontent.com/66849208/86067904-fa1cfb80-ba43-11ea-9af2-026e9954c829.jpg)

**Comment by Bitplicity** [comment]
![20200629_200937](https://user-images.githubusercontent.com/66849208/86068112-7c0d2480-ba44-11ea-9c63-3e49c03544fe.jpg)

**Comment by shendel** [comment]
By default exchange rate is one to one

For example - for Binance USD we are have exchange rate
https://youtu.be/v8s1t4t3ydk

For RSR we are not have exchange rate
https://youtu.be/dyVNUeiW5h8
https://youtu.be/BAUA-uj3dmY

You can set custom exchange rate in admin panel

In future we are can add coinmarketcap.com for exchange rate
For RSR there exists rates
https://coinmarketcap.com/currencies/reserve-rights/

**Comment by noxonsu** [comment]
we can start integrating coinmarketcap (proxy https://noxon.wpmix.net/cursAll.php ). estimate time for implement 2h

"Also let me know if you notice the job running over 2 hours."

**Comment by shendel** [comment]
3 hours

**Comment by Bitplicity** [comment]
Canadian conversion still not working when the user attempts to send a token. However the conversion does now work on the wallet page so thanks for that. See screenshots:

![Screenshot_20200707-132335_Chrome](https://user-images.githubusercontent.com/66849208/86877704-5ff92b00-c0b5-11ea-89f2-a0a09980ba37.jpg)
![Screenshot_20200707-132309_Chrome](https://user-images.githubusercontent.com/66849208/86877706-6091c180-c0b5-11ea-98a6-75364843ef64.jpg)
