### ISSUE TITLE
Remove "debug" links.

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2983]
Please remove these links: 

![Screenshot_20200629-020314_Chrome](https://user-images.githubusercontent.com/66849208/86068162-9d6e1080-ba44-11ea-96b9-2c83ae9155d6.jpg)

**Comment by noxonsu** [comment]
this need for debugging, when users contact support

**Comment by noxonsu** [comment]
We can hide it to "The swap was stuck? Try to reload the page. Debug information [here]"

**Comment by iower** [comment]
Implemented as it was suggested in the previous comment
