### ISSUE TITLE
Remove "No orders found"

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#2985]
Remove. Not necessary as not showing correct information. 

![Screenshot_20200629-201740_Gallery](https://user-images.githubusercontent.com/66849208/86068554-a8757080-ba45-11ea-90d5-6964b714a847.jpg)

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_hEXXHKv2Ufqlhfes9IUytKyntxGSlQ0x.png)

**Comment by noxonsu** [comment]
I think this message doesn't need to delete, we can short this to: "No orders found. Enter amount less than 0.018 ETH or 0.0005 BTC"

**Comment by iower** [comment]
Seems outdated
