### ISSUE TITLE
"i only need wallet for my custom erc20 token"

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3002]
https://codecanyon.net/comments/24660065

сделать возможность в админке отключить ексчендж. (скрывается верхнее меню, и нет опций обмена в контекстных меню и в активах)

**Comment by noxonsu** [comment]
window.disableAtomicSwapExchange

**Comment by BootWP** [comment]
@noxonsu Как точнее назвать опцию в админке?

**Comment by noxonsu** [comment]
"Only wallet mode (disable exchange)"
