### ISSUE TITLE
Disallow exchange from ETH (adn erc20) to BTC if user doesn't has enough eth and tokens on his internal balance

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3004]
Сейчас аноним может начать выполнять ордера например начинает продавать usdt, наш бот морозит битки, а пользоватль ничего не кидает, потому что он просто так тыкал. 

нужно при попытке запустить ордер или из формы в сторону биткоина писать сообщение "please top up your balance before start swap". при этом если чел отдает биткоин, то такого ограничение не должно быть (потому что он первый биток должен кинуть, так что все ок)

**Comment by vladiuz1** [comment]
`please top up your balance before you start the swap` ?
