### ISSUE TITLE
load-app takes 30+ sec to be loaded

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3022]
![](https://screenshots.wpmix.net/chrome_8XCPT3aw2DAHPpYdWNPjyueyiCK4IVyX.png)

**Comment by shendel** [comment]
Посмотрел по коду. Нужно после обработки js-файла app.js кешировать его, а при обновлении плагина удалять.

**Comment by noxonsu** [comment]
now it's ok ![](https://screenshots.wpmix.net/chrome_a2vFELOjvFJXxYm2AkLcgRUCbI66ZjCo.png) but still slow first loading, i suggest to use  cloudflare.com
