### ISSUE TITLE
order book breaked

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#3029]
сломался ордербук. белый экран при попытке купить-продать

**Comment by noxonsu** [comment]
все еще не работает, попытался зайтив  ордербук и купить usdt за биткоин, он долго пытался запросить потом показал красным REQUESTING и ссылку Go to the swap при нажатии на которую белый экран, при этом бот вырубается похоже (ордера пропадают)

**Comment by noxonsu** [comment]
заработало
