### ISSUE TITLE
btc-sms, btc-multisig - withdraw form

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#3040]
Привести btc-sms и btc-multisig к общему виду при отправке (как обычный биток или pin-protected)

**Comment by noxonsu** [comment]
https://drive.google.com/file/d/1TyNXMHmRd24SiitwO4WhUr2ywYpM9CAV/view

**Comment by noxonsu** [comment]
давай сюда же, чтоб не создавать новый. если тебе присалли ссылку или ты начинаешь мультисиг показывать окно - сохраните 12 слов. 

в само окно про 12 слов надо добавить ссылку "I have my 12 words seed" которую взять с экрана добавления кошелька.

**Comment by noxonsu** [comment]
mining fee расчитывается не корректно, не хватает 10 сат. за байт, возможно нужно уменьшить время кэша либо тупо добавлять 10-15 сат

**Comment by shendel** [comment]
> mining fee расчитывается не корректно, не хватает 10 сат. за байт, возможно нужно уменьшить время кэша либо тупо добавлять 10-15 сат

https://github.com/swaponline/MultiCurrencyWallet/pull/3038

**Comment by shendel** [comment]
майнер фи был исправлен с месяц-пол назад (брало unspents не с того адреса)
