### ISSUE TITLE
routing error

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#3042]
На главной странице не корректно работает переключение между "Мои кошельки" и "История"
Вот пример переключения между вкладками "Мои кошельки" и "Запросы" (как должно быть)
![image](https://user-images.githubusercontent.com/1880211/87156241-0a936880-c2c5-11ea-941a-7944add33df4.png)

А вот так происходит переключение между "Мои кошельки" и "История" (как не должно быть)
![image](https://user-images.githubusercontent.com/1880211/87156505-6fe75980-c2c5-11ea-8c70-dbe8a005834d.png)

Из-за этого происходят жуткие лаги при переключение, вплоть до "зависания" браузера на пару секунд

**Comment by iower** [comment]
Outdated
