### ISSUE TITLE
erc20 with symbol "4YO" breaks the app

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3047]
![](https://screenshots.wpmix.net/chrome_RKwToLkkc2sm7UMaypRbIWfBPafB3DMg.png)

**Comment by noxonsu** [comment]
0xdd3bc7c1352bbc0db21bedd871cd4d3cba44c6f7

**Comment by noxonsu** [comment]
похоже они просто перевыпустили токен, так что пока не нужно

**Comment by alvaro8a** [comment]
Это верно, мы выпустили новый токен. Таким образом, мы можем начать работать.
В демоверсии написано, что мы можем хранить €, но в моих кошельках такой возможности нет.




Álvaro Ochoa
CEO ASR4YOU B2C
+34 658 17 88 67
WEB <https://www.asr4you.com/> - MAIL <mailto:info@asr4you.com> - FACEBOOK <https://www.facebook.com/asr4you/> - INSTAGRAM <https://www.instagram.com/asr4you_network/>


De conformidad con el Reglamento (UE) núm.2016/679, General de Protección de Datos, Ud. puede ejercer de forma totalmente gratuita los derechos de acceso, información, rectificación, supresión y olvido, limitación del tratamiento, oposición, portabilidad y a no ser objeto de decisiones individuales automatizadas enviando un e-mail a office@asr4you.com Puede consultar los términos y condiciones del servicio www.aasr4you.com y nuestra política de privacidad www.aasr4you.com Si no desea recibir información por correo electrónico notifíquenoslo por este mismo canal.

**Comment by noxonsu** [comment]
>В демоверсии написано, что мы можем хранить €, но в моих кошельках такой возможности нет.

You can add https://coinmarketcap.com/currencies/stasis-euro/ as a token 0xdb25f211ab05b1c97d595516f45794528a807ad8

**Comment by shendel** [comment]
надо ключи оборочивать в ковычки, чтобы такого не повторялось больше
'4you': { ..... }

**Comment by alvaro8a** [comment]
Hi 


И можем ли мы сделать это возможным?
Одной из причин использования вашего кошелька является то, что мы можем хранить FIAT.

Regards

**Comment by alvaro8a** [comment]
Hi

Спасибо. Я решил это, создав новый токен.

Regards
