### ISSUE TITLE
Urgent: Not able to send Bitcoin

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3048]
Not able to send Bitcoin with a pin protected account. See screenshot:

![IMG-20200711-WA0054](https://user-images.githubusercontent.com/66849208/87237186-24b27100-c3c1-11ea-92bf-d6ec6e51823e.jpg)

**Comment by Bitplicity** [comment]
When user tries to enter the 12 words instead still does not work.

**Comment by shendel** [comment]
Auth server now online
Withdraw with secret phrase tested. Working too. May be user user not correct 12 words?

**Comment by noxonsu** [comment]
tested: sending with 12 words is working. May be it doesn't work if 2fa server is down?

**Comment by shendel** [comment]
tested: when server offline. sending with 12 words is working
tested with not valid secret phrase (some extra spaces between words. some uppercase letters).  
there was a bug.
fixed

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/3108
