### ISSUE TITLE
Wallet Intro Tutorial Error

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3049]
Hello,

The intro tutorial freezes after the first 3 or so "Next" clicks. It does not allow the user to get to the end of the tutorial. 

Thanks.

**Comment by noxonsu** [comment]
@Bitplicity on iphone? 

on PC works fine  https://drive.google.com/file/d/1qr-LMe_SXjTmpo9QGc7vYFbMh3JS5a7g/view

**Comment by Bitplicity** [comment]
On android and iphone.

**Comment by noxonsu** [comment]
![Screenshot_2020-07-13-20-03-51-319_org telegram messenger](https://user-images.githubusercontent.com/2914674/87332407-2fe1da00-c544-11ea-95d1-a998395eb26f.jpg)
Yes, "next" button isn't working on this step

**Comment by noxonsu** [comment]
it's ok now

**Comment by iower** [comment]
Double (#3209) / ready
