### ISSUE TITLE
Exchange Page Input Issue

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3050]
Hello,

When he user tries to enter an amount into the exchange page for a transaction, it completely cuts off the field so the user has no idea what amount they are entering. Very bad for user experience. See screenshot. Notice that when trying to enter amount in ethereum the ethereum field is hidden...and the user only sees the Bitcoin field. 

![Screenshot_20200712-034610_Chrome](https://user-images.githubusercontent.com/66849208/87241559-71627000-c3f2-11ea-8e07-26218c493a9f.jpg)

**Comment by noxonsu** [comment]
1. hide header (logo etc)
2. short message (already did)

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/3089

**Comment by noxonsu** [comment]
- [ ] https://screenshots.wpmix.net/Telegram_L85Xu622dGrRoH2B65TaUhIIVKWIxuWh.png баксы сьехали
- [ ] https://screenshots.wpmix.net/Telegram_L85Xu622dGrRoH2B65TaUhIIVKWIxuWh.png сообщение заменить на "This trade amount is too high for present market liquidity. Please reduce amount to X. " так же немного заходит за край экрана, попытка скрола перезагружает страницу т.к. типа конец экрана
