### ISSUE TITLE
Button Buttons Disappearing

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3052]
Hi,

The bottom buttons "wallet, transactions and exchange" all disappear when you click "exchange" and enter an amount in the exchange fields. See screenshot:

![Screenshot_20200712-040052_Chrome](https://user-images.githubusercontent.com/66849208/87241793-84763f80-c3f4-11ea-963d-9231bca1bf50.jpg)

**Comment by Bitplicity** [comment]
Also, the exchange page does not permit refresh by page pull-down.

**Comment by noxonsu** [comment]
we hide buttons for focusing user to the input and show him a form with calculations. pull-down is working in chrome now
