### ISSUE TITLE
Fiat Balance Not Working

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3063]
Fiat balance not working. Showing a zero balance when there is funds. Also, not showing correct fiat balance on the send and exchange page.  See screenshot:

![Screenshot_20200714-225602_Chrome](https://user-images.githubusercontent.com/66849208/87498449-ca661a00-c625-11ea-8e35-dd45e06603b1.jpg)
![Screenshot_20200714-225613_Chrome](https://user-images.githubusercontent.com/66849208/87498450-cafeb080-c625-11ea-9716-cc0a889a014d.jpg)

**Comment by shendel** [comment]
in the new browser managed to repeat

**Comment by shendel** [comment]
api breaked. fix in progress

**Comment by shendel** [comment]
api fixed

**Comment by Bitplicity** [comment]
Thanks!
