### ISSUE TITLE
Remove "Buy Token" menu link 

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3064]
Please remove "buy token" menu link. It goes to the same page as the "exchange" page so please remove this duplicate menu item. See screenshot: 

![Screenshot_20200714-221133_Bitplicity](https://user-images.githubusercontent.com/66849208/87498611-334d9200-c626-11ea-96ca-a426e8ebce62.jpg)

**Comment by noxonsu** [comment]
also hide this (on multisig, smd and pin-protected bitcoin wallets)
![](https://screenshots.wpmix.net/Telegram_riyG7kO4dhEWax3BU9S0293a9yIdlAeO.png) 

juts hide, not remove
