### ISSUE TITLE
Overlapping on Exchange page

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3065]
Overlapping on the Exchange page. Text is partially hidden. See screenshot: 

![Screenshot_20200714-220647_Bitplicity](https://user-images.githubusercontent.com/66849208/87498679-5ed07c80-c626-11ea-874c-cfaf9b6e3732.jpg)

**Comment by iower** [comment]
@Bitplicity It looks like you are using Samsung Internet Browser and it renders the page a little differently.

**Comment by iower** [comment]
@Bitplicity Can't reproduce. Is there a problem now? What browser are you using?

**Comment by iower** [comment]
Seems like all fine
