### ISSUE TITLE
history: glitches while loading

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3069]
..

**Comment by noxonsu** [comment]
на мобильнике когда заходишь в историю кошелька инпут некрасиво наезжает на полэкрана. не могу поймать скрин

**Comment by shendel** [comment]
связанные
https://github.com/swaponline/MultiCurrencyWallet/issues/3042
https://github.com/swaponline/MultiCurrencyWallet/issues/3026

**Comment by iower** [comment]
Fixed? @noxonsu
