### ISSUE TITLE
Custom fees with node app?

### ISSUE THREAD

**Issue by Gabo1122** [swaponline/MultiCurrencyWallet#3076]
Hello, is it possible to set up a custom fee for transactions like in the wordpress version? But for the nodejs version? If so, how do I do it?

**Comment by shendel** [comment]
You mean npm run prod
or
npm run build:mainnet?

**Comment by Gabo1122** [comment]
I mean, I saw the Wordpress version, and it has sort of an admin panel, is that also included in the nodejs version? Or how can I set up a custom fee for transactions? And also a default limit price on the orders of my custom token?

**Comment by noxonsu** [comment]
Embed this html code into your index.html build before app.js 

![](https://screenshots.wpmix.net/chrome_s1wWPhpRlphLwZOBm61HvPjX7b95pVVL.png)

**Comment by Gabo1122** [comment]
Thanks for your help, but which file exactly is the one I need to edit?

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/blob/master/client/index.html#L671 try here
