### ISSUE TITLE
hide all adreessess and prevent logout untill client hasn't saved 12 words

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3079]
сейчас если чел не сохранил 12 слов (т.е. в инконито deposit не сделать пока не сохраниш приватник) при клике на депозит просит сохранить 12 слов, это ок. надо так же скрыть адреса тут https://screenshots.wpmix.net/chrome_vpGEkMSBPxGhaP4N6oZ6qvQK11P8GLao.png, вместо адреса показывать "show the address" при клике кидать на deposit где уже его просят сохранить 12 слов.

**Comment by shendel** [comment]
Проверку, сохранил ли человек слова, можно посмотреть тут https://github.com/swaponline/MultiCurrencyWallet/blob/master/shared/components/modals/ReceiveModal/ReceiveModal.js#L69

**Comment by noxonsu** [comment]
сюда же - сейчас если  у нас определен window.logoutUrl то появляется кнопка выхода, нужно при нажатии на нее проверять сохранил ли чел свои сид, если нет то не давать выйти, пусть сохраняет потом выходит.

**Comment by noxonsu** [comment]
then https://github.com/swaponline/MultiCurrencyWallet/issues/3086
