### ISSUE TITLE
Menu disappearing

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3083]
Hello,

When you click the send button and then return to the wallet homepage by clicking the "x", the menu completely disappears. 

See video: 

https://wallet.bitplicity.com/wp-content/uploads/2020/07/20200720_152114.mp4

See Screenshot: 

![Screenshot_20200720-151823_Chrome](https://user-images.githubusercontent.com/66849208/87977640-1210f980-ca9d-11ea-8c04-29b14f360ac3.jpg)

**Comment by iower** [comment]
Reproduced
