### ISSUE TITLE
Change the message "Don't forget to save your private keys" on preload screen

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3090]
We should change this text: 
![](https://screenshots.wpmix.net/chrome_MUsxB6urF04gCWnJ0n15Vw76ZUtwwiCA.png) 

1. Before a user's 12 words seed phrase has been saved: 

- **Don't forget to save your recovery phrase!**

2. After seed phrase has been saved: 

- **Make sure you keep your recovery phrase in a safe place!**
or randomly
- **Don't forget where your recovery phrase are saved!**

Note: Many users just forget where are they have saved their backups (where is the paper or file).

**Comment by noxonsu** [comment]
@Bitplicity, are this correct message?

**Comment by Bitplicity** [comment]
There are some gramatical and factual errors. It would be more accurate to say: 

#1 - Don't forget to save your 12 word recovery phrase and private keys.
#2 - Keep your recovery phrase and private keys in a safe place. 

As the user also needs to remember to copy their private keys, not just their recovery phrase. Also, grammatically,  "Don't forget where your recovery phrase are saved" should use "is", not "are".

**Comment by noxonsu** [comment]
> user also needs to remember to copy their private keys, not just their recovery phrase

phrase is enough, this is HD wallet principle (one root - many blockchains, addresses)

![](https://bits.media/images/hd-wallet/Bitcoin_HD_tree.jpg)

1. final:
- [ ] Don't forget to save your 12-word recovery phrase

2. Can be randomly picked from these:
- [ ] Keep your recovery phrase and private keys in a safe place
- [ ] Don't forget where your recovery phrase is saved
