### ISSUE TITLE
exchange: erc20 ghost issues

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3097]
![](https://screenshots.wpmix.net/chrome_okCH3hB3jCXR5UN099J3WRnI3X4S4eDg.png) but orderbook has more

**Comment by noxonsu** [comment]
похоже, тут суть в том, что если вычесть комиссию, то будет очень маленькая сумма

**Comment by noxonsu** [comment]
1. указал https://screenshots.wpmix.net/chrome_3WKmUbddqkw77FpDiISHlrcjWuDatHXc.png , свап начать невозможно, непонятно почему. я думаю конечному пользователю надо тупо отдельно показать майнинг фи, прямо под формой типа 

Mining fees are: 0.00 BTC, 0.3 ETH

**Comment by shendel** [comment]
> 1. указал https://screenshots.wpmix.net/chrome_3WKmUbddqkw77FpDiISHlrcjWuDatHXc.png , свап начать невозможно, непонятно почему. я думаю конечному пользователю надо тупо отдельно показать майнинг фи, прямо под формой типа
> 
> Mining fees are: 0.00 BTC, 0.3 ETH

Ну тут относительно понятно
На балансе 0.00063 BTC
Мы хотим продать 0.0006, но максимально мы можем продать только 0.00013 (что и пишет), потому-что еще есть майнер фи, который в данном случае 0.00049 - итого 0.00063 минус 0.00049 равно примерно 0.00013 (сколько мы и можем себе позволить продать)

Тут надо перефразировать и сверху где "Ваш баланс", писать "Доступный баланс для обмена" и сразу вычитать оттуда майнер фи
