### ISSUE TITLE
add PAY token

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3106]
https://etherscan.io/address/0x1fe72034da777ef22533eaa6dd7cbe1d80be50fa

**Comment by iower** [comment]
Logo src: https://github.com/PayAccept/logokit

**Comment by noxonsu** [comment]
please add to "hiddenCoins" by default https://screenshots.wpmix.net/chrome_jsKrnu6m2AgG8tbfLmfYFZZpa4oOJLpc.png (зашел чтоб провреить ghost, а пейтокен почемуто тоже показывается)

**Comment by iower** [comment]
next #3111
