### ISSUE TITLE
(Question) How to add custom usd price to ERC20 Token?

### ISSUE THREAD

**Issue by Gabo1122** [swaponline/MultiCurrencyWallet#3109]
Hello everyone,
Where can I set up a custom USD price for my ERC20 token? 
Where does the wallet gets this price from? Can I set it up to get info from a different API?
Thanks in advance

**Comment by noxonsu** [comment]
How to add custom feed https://github.com/swaponline/MultiCurrencyWallet/pull/3017/files

**Comment by Gabo1122** [comment]
Can you guide me a bit more please?

**Comment by Gabo1122** [comment]
Or how can I make the wallet balance display the erc20 token price according to customEcxchangeRate: '1.25',

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_xVi4FJD1ojsBjvExQss9PTghI9ucnucp.png)
