### ISSUE TITLE
BTC-testnet: 'no connection...' (bitpay/insight -> bitpay/bitcore)

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3115]
# Problem

testnet
![image](https://user-images.githubusercontent.com/35522011/88783211-f053f880-d1a7-11ea-8265-3034dda37096.png)

# Task

bitpay/insight -> bitpay/bitcore

**Comment by shendel** [comment]
прокси почти готов, нет только broadcast,

**Comment by shendel** [comment]
https://github.com/swaponline/insight
в конфиге прописать вот так 
![image](https://user-images.githubusercontent.com/1880211/88808781-f8b62e80-d1bb-11ea-82ea-0a99725ef06b.png)

**Comment by noxonsu** [comment]
можешь выдавать пока rawtx для броадкаста пусть прогер сам отправляет

**Comment by iower** [comment]
Broadcast is really needed for testnet swaps

**Comment by shendel** [comment]
> Broadcast is really needed for testnet swaps
броадкаст в работе
для свапа он не нужен. если основной bitpay не доступен, для броадкаста использует апи blockcypher
