### ISSUE TITLE
add new NL (Dutch, Netherlands) locale

### ISSUE THREAD

**Issue by INSTAINBLOCKS** [swaponline/MultiCurrencyWallet#3124]
Hello,

Here are my translations I have so far for the wallet to Dutch, NL(Netherlands) language. If I have missed something let me know.

**[translations mcwallet NL Dutch.zip]**(https://github.com/swaponline/MultiCurrencyWallet/files/5010335/translations.mcwallet.NL.Dutch.zip)
**Texts**
[dutch translations.txt](https://github.com/swaponline/MultiCurrencyWallet/files/5010475/dutch.translations.txt)

Greetings,
INSTAINBLOCKS■

**Comment by shendel** [comment]
@INSTAINBLOCKS Language added
You can translate other labels
https://github.com/swaponline/MultiCurrencyWallet/blob/master/shared/localisation/nl.json

**Comment by INSTAINBLOCKS** [comment]
Finally finished, was a lot of work.

[translated strings nl.txt](https://github.com/swaponline/MultiCurrencyWallet/files/5176120/translated.strings.nl.txt)

**Comment by shendel** [comment]
Fixed Json 
[nl.txt](https://github.com/swaponline/MultiCurrencyWallet/files/5182759/nl.txt)
