### ISSUE TITLE
Swap: TypeErrors

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3133]
- testnet
- custom token 0xaFF4481D10270F50f203E0763e2597776068CBc5
![image](https://user-images.githubusercontent.com/35522011/89513546-23246f00-d7ee-11ea-9588-946f178a3e17.png)

**Comment by shendel** [comment]
Похоже на сбой в ipfs, почему-то не нашло ордер, с которым свап начали
Повторить не получилось
