### ISSUE TITLE
Sun got very big today after update plugin

### ISSUE THREAD

**Issue by INSTAINBLOCKS** [swaponline/MultiCurrencyWallet#3136]
![image](https://user-images.githubusercontent.com/41331864/89712798-7e439680-d993-11ea-82a0-d94319066000.png)

**Comment by iower** [comment]
Appears only in the dark mode

**Comment by INSTAINBLOCKS** [comment]
Wallet keeps loading now after todays update.

**Comment by iower** [comment]
Checked, looks right
![image](https://user-images.githubusercontent.com/35522011/89756726-caf6b100-dafc-11ea-8d94-2cfc04c45bf5.png)

**Comment by noxonsu** [comment]
@INSTAINBLOCKS send the link where we can see the bug

**Comment by INSTAINBLOCKS** [comment]
@noxonsu  https://instainblocks.com/my-wallet/

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_OYidG7lCOmSfPIhNAD73SEXIVovfs17B.png)

**Comment by INSTAINBLOCKS** [comment]
It works for me after clearing the cache, but I am still wondering why this happened in the first place.
