### ISSUE TITLE
Include `insight` to this repo

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3138]
# Purpose

- easier dev launch 
- less windows
- clearer workflow for 3rd party developers (current workflow isn't documented)

# Task

- move files https://github.com/swaponline/insight
- merge dependencies
- run `app` with dev server
- delete repo https://github.com/swaponline/insight

**Comment by noxonsu** [comment]
в дев режим ты хочешь добавить его?
