### ISSUE TITLE
Exchnage: disable swap start on low ETH

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3141]

**Comment by noxonsu** [comment]
i think 0.01 is enough.

**Comment by noxonsu** [comment]
Нужно проверять чтоб хватало на сумму обмена плюс газ*1.3

**Comment by noxonsu** [comment]
Так же в бота добавить, чтоб он не обменивался на маленькие суммы, минимум 50 баксов а то майнинг фи все сжирает

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_cSYWbpHQVmviLmAAYashaNY7eXr8OVi2.png) чето расходятя показания у виджета

**Comment by noxonsu** [comment]
"You will pay up to 0.02 ETH, 0.0002 BTC extra as mining fee"

**Comment by noxonsu** [comment]
комиссию считает сильно завышенную. когда начинаю свап eth-btc показывает

You'll be charged additionally up to 0.032625 ETH and 0.0003653 BTC as a mining fee. в реальности https://etherscan.io/tx/0x2112b1f8d97c17bbf0d42eef373ead08507d8950a9866e941c35400380ccd644 т.е. в 100 раз!

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/3218
