### ISSUE TITLE
Mobile Allignment Issues - Wallet + Add Currency Button

### ISSUE THREAD

**Issue by INSTAINBLOCKS** [swaponline/MultiCurrencyWallet#3144]
![image](https://user-images.githubusercontent.com/41331864/89803768-8d614a80-db33-11ea-979a-29b87e064192.png)
- Wallet Button overlaps text on exchange

![image](https://user-images.githubusercontent.com/41331864/89803779-905c3b00-db33-11ea-916a-ade6011ea194.png)
- Add currency button almost not visible after adding 1 token.

**Comment by INSTAINBLOCKS** [comment]
I would like to add to this that there is a white space at the bottom as too.
![image](https://user-images.githubusercontent.com/41331864/89871739-394c7980-dbb8-11ea-9a81-629fd9e03066.png)

**Comment by iower** [comment]
Wait for @INSTAINBLOCKS manual update

**Comment by INSTAINBLOCKS** [comment]
> Wait for @INSTAINBLOCKS manual update

@iower first issue is fixed.
![image](https://user-images.githubusercontent.com/41331864/89896918-82afbf80-dbde-11ea-9999-074ab775fdf5.png)

**Comment by iower** [comment]
Checked on the https://instainblocks.com/my-wallet/ , looks OK
