### ISSUE TITLE
Is it possible to make a telegram Tipbot which is connected to this wallet?

### ISSUE THREAD

**Issue by Christian-RIZE** [swaponline/MultiCurrencyWallet#3150]
Title speaks for itself

**Comment by noxonsu** [comment]
Could you please describe the userflow? 

1. Alice want to tip Bob with 3 TOKEN....
2. ??

**Comment by Christian-RIZE** [comment]
Alice want to tip Bob with 3 token
Alice says to Bob in a telegram group with the Bot /tip 1 ETH @bob 
Bob receives 1 ETH in his connected wallet with the bot

**Comment by noxonsu** [comment]
not possible at this time
