### ISSUE TITLE
No back or X button on empty balance

### ISSUE THREAD

**Issue by INSTAINBLOCKS** [swaponline/MultiCurrencyWallet#3155]
![image](https://user-images.githubusercontent.com/41331864/89999746-85b6b880-dc8f-11ea-8441-d06779a722a1.png)

**Comment by noxonsu** [comment]
- [ ] also check for 0.01 ETH min (if user starting BTC/ERC20)

**Comment by shendel** [comment]
> * [ ]  also check for 0.01 ETH min (if user starting BTC/ERC20)

https://github.com/swaponline/MultiCurrencyWallet/issues/3141
