### ISSUE TITLE
Add "custom token price" 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3158]
Клиент просит, чтоб мог ставить своему токену прайс, т.к. его нет на коинмаркеткапе. такое раньше было но кудато делось, надо вернуть https://screenshots.wpmix.net/chrome_uvHuXw3jNjohxmXO5A8OK7P7vN7Hp2Q0.png

**Comment by shendel** [comment]
Старый плагин
Но нельзя редактировать уже созданные токены https://github.com/swaponline/multi-currency-wallet-pro/issues/30
