### ISSUE TITLE
Why can I only create an exchange order with BTC

### ISSUE THREAD

**Issue by Christian-RIZE** [swaponline/MultiCurrencyWallet#3159]
I want for example to trade USDT against ETH. Why is that not possible?

**Comment by iower** [comment]
Related: https://github.com/swaponline/swap.core/issues/502

**Comment by shendel** [comment]
> Related: [swaponline/swap.core#502](https://github.com/swaponline/swap.core/issues/502)

У нас раньше был USDT на основе Btc, но его удалили
Вот бренж до удаления
https://github.com/shendel/swap.core-1/tree/disableOldUSDT
Вот собственно сам флоу
https://github.com/shendel/swap.core-1/blob/disableOldUSDT/src/swap.flows/ETHTOKEN2USDT.js
https://github.com/shendel/swap.core-1/blob/disableOldUSDT/src/swap.flows/USDT2ETHTOKEN.js

Сейчас у нас USDT на основе ERC20, нужен флоу ETH-ERC20

**Comment by Christian-RIZE** [comment]
Is there something to do about?

**Comment by noxonsu** [comment]
99% of DEXs are working with ETH, whereas we decided to focus on BTC, USDT, EOS. We will add ETH but later
