### ISSUE TITLE
Order stuck

### ISSUE THREAD

**Issue by Christian-RIZE** [swaponline/MultiCurrencyWallet#3160]
https://www.blockchain.com/btc/tx/13bd147a792143064d1397b5544e839dfa1d8eeacf21894dc8f60c9bd41df50d

<img width="1280" alt="Schermafbeelding 2020-08-13 om 08 49 14" src="https://user-images.githubusercontent.com/69308977/90102905-e56d9c00-dd41-11ea-8e3f-ed1f9381e6c6.png">

It is stuck for over 10 hours now

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/3166
