### ISSUE TITLE
History: 52586 year

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3161]
## What is working wrong?

...Describe what do you think should happen instead in this situation...
![image](https://user-images.githubusercontent.com/35522011/90105545-83bc2a80-dd5f-11ea-8d87-76aa5e0fa9ad.png)

## Your system charateristics

- Browser: Chrome
- OS: Ubuntu
- Mainnet or Testnet: Testnet

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by shendel** [comment]
Проблема только на тестнете с битков в insight
На маиннете все ок
![image](https://user-images.githubusercontent.com/1880211/90114132-faa2f480-dd5a-11ea-8502-83d5b308277e.png)

**Comment by shendel** [comment]
Не критичный для mainnet
