### ISSUE TITLE
Simplify config

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3165]
# Problem

Not obvious how to configure

# Solution (draft)

```
domain
or
domain-network
```
```
default-default
default-mainet
default-testnet
extension-mainnet
extension-testnet
localhost-mainnet
localhost-testnet
swaponline.github.io
widget-testnet
widget-mainnet
```

**Comment by shendel** [comment]
приоритет конфигурации
1. domain-network (если нет - пункт 2)
2. domain (если нет - пункт 3)
3. default-network (если нет - пункт 4)
4. default (если нет - то нет, использует стандартные из config/network)

**Comment by iower** [comment]
Documented!
