### ISSUE TITLE
connect metamask

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3171]
motivation: use metamask's balances instead of topup to internal wallet

**Comment by JoaoCampos89** [comment]
An alternative solution instead of support only Metamas is use this library which already build a modal with several web3 wallets: https://github.com/Web3Modal/web3modal

**Comment by noxonsu** [comment]
Test. 
1. Clear storage
2. Go to #/exchange
3. Click "connect wallet"
4. In web3modal select metamask
5. Connect metamas
6. Check: i see the same adresses and balances on my  main page
7. Start swap ETH-BTC 
8. Freeze ETH when it ask
9. Finish a swap
10.history in metamask show income transaction
