### ISSUE TITLE
+ TypeScript (phase 1)

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3172]
[TypeScript phase 1](https://github.com/swaponline/MultiCurrencyWallet/issues/3172)
[TypeScript phase 2](https://github.com/swaponline/MultiCurrencyWallet/issues/3562)
[TypeScript phase 3](https://github.com/swaponline/MultiCurrencyWallet/issues/3741)

# Plan / progress

## js->ts

- [x] add ts config

- [x] front
	- [x] build shows typecheck erros, CI stops on errors
	- [x] fix routes
	- [x] .js -> .ts|.tsx
	- [x] fix types / add @ts-ignore
	- [x] build
	- [x] run
	- [x] fix watcher
- [x] core
	- [x] .js -> .ts
	- [x] fix types / add @ts-ignore
- [x] common
	- [x] .js -> .ts
	- [x] fix types / add @ts-ignore
- [x] bot
	- [x] .js -> .ts
	- [x] fix types / add @ts-ignore
	- [x] build
	- [x] run

## Remove @ts-ignore / Add types (separate task)

- #3562

---
---
---
---
---
---

# Problem

- bugs
- fixes produces other bugs
- fragile for 3rd party PRs

### Examples of issues

- #3178
- #3133
- #3182
- #3268
- #3299
- #3464 ?
- #3494
- #3674

# Possible solution

More strong typization - move project to TypeScript (by small steps)

(The 1st attempt of typization was `prop-types`)

Also, structure detected in https://github.com/swaponline/swap.core/blob/master/src/swap.app/constants/PAIR_TYPES.js

## Pro

- Types and interfaces as self-documented domain knowledge
- Static analysis
- Less feedback time (editor show errors)
- (!) Compile-time errors, not execution-time
- Less bugs in production
- Save time at long distance

## Contra

- More difficult
- Costs time to integrate
- Some other difficults?

**Comment by noxonsu** [comment]
@shendel что думаешь

**Comment by shendel** [comment]
Вообще как-бы в веб-паке у нас есть ts - некоторые зависимости на нем написаны.
В целом можно добавить в /webpack/rules/ правила для обработки этих файлов
но тут, я думаю сузиться вход разработчиков, если проект полностью перевести на ts,
у нас сейчас ECMAScript по стандартам W3, большинство современных браузеров (хром, опера, фаерфокс) его поддерживают из коробки
А TypeScript - это по сути интерпритатор, - на выходе в любом случае будет VanillaJS

**Comment by shendel** [comment]
@vladiuz1

**Comment by iower** [comment]
- The project may not be rewrited completely on TS, just in critical places (like modules interfaces, main structures)
- Key is not module development time, but module refactor time (module interaction bugs)

**Comment by iower** [comment]
As variant, we may previously test +TS cost/profit on smaller project [swap.core](https://github.com/swaponline/swap.core).
It may helps for refactors https://github.com/swaponline/swap.core/issues/502
After that core interfaces to start +TS MultiCurrencyWallet will be ready.
