### ISSUE TITLE
-IPFS +GUN

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3179]
https://github.com/amark/gun

*Suggested by @7flash*

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.core/issues/441 realted

**Comment by noxonsu** [comment]
- pub sub либа которую мы используем УЖЕ ДАВНО не использует ipfs, а напрямую libp2p
- следовательно, чтоб окончательно избавится от кода ipfs надо всего лишь обновить пакеты (а это довольно кропотливый процесс, который постоянно откладывается, т.к. и так все работает) 
- после этого сделать возможность подключить любой меседжинг через плагины
- далее написать плагин для gun, для rabitmq или просто базу данных

**Comment by iower** [comment]
Finally migrated to `libp2p`. No reasons to use `GUN`.
