### ISSUE TITLE
Backup crashes

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3182]
## What is working wrong?

After 12 words:

![image](https://user-images.githubusercontent.com/35522011/90476040-24389300-e142-11ea-91e9-eaef987f4493.png)

...and no redirect to the wallet.

## Your system charateristics

- Browser: Firefox
- OS: Ubuntu
- Network: mainnet
- Domain: swaponline.io

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by noxonsu** [comment]
сохранил 12 слов на mytoken.wpmix.net, вроде все ок
