### ISSUE TITLE
Wordpress Plugin Bug for for different user login with the same browser

### ISSUE THREAD

**Issue by Dezueka** [swaponline/MultiCurrencyWallet#3202]
## Screenshot or description
The problem when login and log out with different users in the same browser get the same Wallet address and balance, this should be fixed for session cleared after logout for different WordPress user, otherwise. the other user will get risk with losing funds for accessing it from the internet cafe or other public internet if middleman third party can access the other user account with the same browser.

![screenshot-www laocommerce com-2020 08 25-17_40_49](https://user-images.githubusercontent.com/26108578/91165350-ad2f6b80-e6fa-11ea-8ee0-92d98107e77f.png)

## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: laocommerce.com/buy
- Mainnet 
- Browser:  Google Chrome
- OS: Window 10

## Does this affect atomic swap flow?

- [x] yes
- [*] no

## Are real funds at risk?

- [*] yes
- [x] no

**Comment by noxonsu** [comment]
@Dezueka do you use the деуые version of the plugin? (dashboard - updates - check updates)

**Comment by Dezueka** [comment]
Yes, both old and latest version still be the same. Another thing is when we clear the browser cache & history, WordPress user account in the same site & browser have to import the keyphrase again to restore the Wallet account, otherwise, the wp user must create the new Wallet account .

**Comment by shendel** [comment]
@Dezueka i add clear storage on logout (after user confirm save phrase), also there exists this option 
![image](https://user-images.githubusercontent.com/1880211/91325779-44182880-e7cc-11ea-9da8-8a57398292ea.png)
 if enabled, the user's wallet will be restored upon login

**Comment by Dezueka** [comment]
Thanks for your kindly support & cooperation.
