### ISSUE TITLE
Wallet keeps loading

### ISSUE THREAD

**Issue by INSTAINBLOCKS** [swaponline/MultiCurrencyWallet#3208]
Hello the wallet keeps loading but see no errors. What is the problem here you think?

**Comment by shendel** [comment]
hm... code truncated
![image](https://user-images.githubusercontent.com/1880211/91416707-74a5a400-e858-11ea-95c0-6b4e6642bb41.png)
may be cache broken
try disable cache or (may be optimization plugin installed?)
![image](https://user-images.githubusercontent.com/1880211/91416869-a74f9c80-e858-11ea-896e-aa679a1f97d3.png)

**Comment by INSTAINBLOCKS** [comment]
Seems like it was from another plugin somehow. Strange as it worked before but it is fixed, thanks for the help.
