### ISSUE TITLE
Swap history not show for Ghost Swaps

### ISSUE THREAD

**Issue by JoaoCampos89** [swaponline/MultiCurrencyWallet#3220]
Ghost swaps not show up on the swap history causing we  not being able to call the refund functions on a failed swap. I already looked at Swap History component, but I am without any clue what is missing. Can you guys provide some guidance?. This is the missing part before we launch Ghost support on mainnet
 
## Screenshot or description

![image](https://user-images.githubusercontent.com/8621730/91724185-4fc07200-eb73-11ea-9c90-8a4626457f2a.png)

## Steps to reproduce

- Place Ghost order on mainnet
- Start swap and then one user get offline
- Try to refund, on the swap history card but not shows up the missed swap

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [x] yes
- [ ] no

**Comment by shendel** [comment]
Add GHOST check there https://github.com/shendel/swap.react/blob/master/shared/pages/History/SwapsHistory/RowHistory/RowHistory.js#L43
There https://github.com/shendel/swap.react/blob/master/shared/pages/History/SwapsHistory/RowHistory/RowHistory.js#L66 (ghostScriptValues)
And there https://github.com/shendel/swap.react/blob/master/shared/pages/History/SwapsHistory/RowHistory/RowHistory.js#L99 (ghostScriptValues)
Make this like in componentDidMount https://github.com/shendel/swap.react/blob/master/shared/pages/History/SwapsHistory/RowHistory/RowHistory.js#L66

**Comment by JoaoCampos89** [comment]
@shendel your repo is different than the master should I merge your repo, or wait for you to merge and then pull the changes?
