### ISSUE TITLE
1. Ghost tile not featured on Deposit page.

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3227]

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/Telegram_G3ttjaeDB3GDiPCVJCH7ThnLtGIHKkwa.jpg)

**Comment by alyavasilyeva** [comment]
@noxonsu  подскажи, пожалуйста, как воспроизвести баг. у меня там ETH и GHOST, без BTC. Это зависит от валюты  текущего кошелька?

**Comment by noxonsu** [comment]
@alyavasilyeva на ghostx.live если есть то можно приложить скрин и закрывать

**Comment by alyavasilyeva** [comment]
@noxonsu  
![image](https://user-images.githubusercontent.com/27780611/99420014-c7e63a80-290d-11eb-87b2-d549d90d9809.png)

**Comment by noxonsu** [comment]
чето не так, должна быть иконка другая

**Comment by alyavasilyeva** [comment]
@noxonsu можешь сказать, какая? и почему их вообще два?
