### ISSUE TITLE
2. Create offer button could be place more strategically as though it’s an option, either or, to Exchange now.

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3228]

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/Telegram_eCqyRX2N9JdVR7mCwNHsKSnuCVGN70n9.jpg)

**Comment by noxonsu** [comment]
should be looks like regular link, `or <a href=''>create limit order</a>`

**Comment by this-js-hub** [comment]
Testing complete. Looks good. You can close the issue.
