### ISSUE TITLE
10. UX: Colours pallet to be adapted to Ghost brand. (Red/Black)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3236]

**Comment by JoaoCampos89** [comment]
Hey @noxonsu what we can do to move forwarder on this?

 Ideally it will be adding an option to us add css file to it or allow the plugin to upload a custom css. I can change all the css but then with new updates it get replaced.

**Comment by JoaoCampos89** [comment]
Duplicate #3345
