### ISSUE TITLE
Metamask: improve flow

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3248]
- can't hide metamask address (menu->hide)
- prohibit adding metamask-mainnet to MCW-testnet

## Improve createWallet page

- `Connect wallet` -> `Use Metamask`
- `Access using 12-word phrase` -> `Restore from 12-word phrase`
- Add `Create wallet` option
- Options: <kbd>Create wallet</kbd>, <kbd>Restore from 12-word phrase</kbd>, <kbd>Use Metamask</kbd>

**Comment by shendel** [comment]
> * can't hide metamask address (menu->hide)
Такого не было..... через выпадающее меню можно было убрать кошелек (и можно до сих пор) при условии, что у него ноль на счету

**Comment by shendel** [comment]
адрес кошелька показан по той причине, что он внешний, не зависит от 12 слов, которые человеку следует сохранить

**Comment by noxonsu** [comment]
Connect wallet устоявшееся выражение, см uniswap.exchange, его надо еще разместить на странице обмена

**Comment by iower** [comment]
Closed, some points moved to #3667
