### ISSUE TITLE
Sometimes site does not work in iframe

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3249]
![Screenshot_2020-09-09-21-32-25-603_org telegram messenger](https://user-images.githubusercontent.com/2914674/92639157-16f76a00-f2e4-11ea-8d7c-ea320ccb6add.jpg)

https://preview.codecanyon.net/item/multicurrency-crypto-wallet-and-exchange-widgets-for-wordpress/full_screen_preview/23532064?_ga=2.148324597.396451418.1599668606-1527966991.1590482613

**Comment by noxonsu** [comment]
Not every function works In this window, please open new tab. If the error will repeat please contact admin https://t.me/sashanoxon

**Comment by shendel** [comment]
![image](https://user-images.githubusercontent.com/1880211/92894157-04377f00-f423-11ea-9698-886dd64f3c5c.png)
