### ISSUE TITLE
Logo can be smaller + other suggestions.

### ISSUE THREAD

**Issue by INSTAINBLOCKS** [swaponline/MultiCurrencyWallet#3254]
I think with 100px and maybe a little more to the right. in the middle above the balance is better. 
Also it creates some more space at the bottom so everything fits in screen as well (for example the add currency button).

Have added:    
    width: 100px; ( 75px would also be good.)
    margin-left: 125px;

Although this would confilct on smaller screens I think.

![image](https://user-images.githubusercontent.com/41331864/92928184-0a3b5900-f43f-11ea-877a-2ff0ad009258.png)

--------------------------------------------------

- Another idea I got is rearrange the layout like the screenshot below, **just a suggestion.**
![image](https://user-images.githubusercontent.com/41331864/92930615-956a1e00-f442-11ea-8efa-42dd44ddca4e.png)
![image](https://user-images.githubusercontent.com/41331864/92931333-96e81600-f443-11ea-8913-fb74ada31758.png)

**Comment by iower** [comment]
- [x] logo size changed
- [ ]  change layout - wontfix
