### ISSUE TITLE
Can't get BTC balance

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3268]
## Steps to reproduce

- Incognito
- Restore from 12 words
- BTC balance: infinite load, `Provided address "undefined"`

## Environment

- Domain: swaponline.io
- Mainnet or Testnet: mainnet
- Browser: Chrome
- OS: 

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by noxonsu** [comment]
тоже с вновь созданным кошелем и эфир тудаже
![](https://screenshots.wpmix.net/chrome_2F74VZkOYsvMOJZ7NIAJ0pN9oIrxKW3Q.png)

**Comment by noxonsu** [comment]
все норм, только теперь не работает если прямо зайти на https://swaponline.github.io/#/exchange/btc-to-eth пустая страница
