### ISSUE TITLE
Bot: btc adresses whitelist 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3322]
добавить туда адрес бота. если юзер меняется с ботом, то юзер может не ждать 1 подтверждения когда eth->btc делает, т.к. мы не будем его обманывать.  тогда если клиент меняется с ботом то клиент не ждет 1 конфирма

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/instances/newSwap.js#L86
default white list
https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/core/swap.app/SwapApp.js#L7
