### ISSUE TITLE
Branding colours 

### ISSUE THREAD

**Issue by JoaoCampos89** [swaponline/MultiCurrencyWallet#3345]
# Problem

At the moment the branding colours are to tied to swap online branding. If a user want to brand their exchange, an way is to directly change the generated css files by react build.

# Task

In this task we create a brand colour (or colours) variable which will be used accross all components. This could be done by theme injection. Example of implementation: https://medium.com/@openshift.ninja/dynamic-branding-with-react-and-scss-css-variables-9d877c1c87fa

# Estimate time of implementation

10 h

**Comment by JoaoCampos89** [comment]
@noxonsu is this completed by #3418 ?

**Comment by NotEternal** [comment]
related to #3531
