### ISSUE TITLE
Swap: BTC tx link error

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3350]
![image](https://user-images.githubusercontent.com/35522011/95582745-803dda80-0a54-11eb-8a63-8ceda7738cdc.png)
![image](https://user-images.githubusercontent.com/35522011/95582775-8af86f80-0a54-11eb-90ea-0a319e3db52e.png)

**Comment by noxonsu** [comment]
testnet?

**Comment by shendel** [comment]
да, тоже наблюдал такое на тестнете. я думаю что tx еще не обновилась на blockchain.info (мы ее броадкастим на insight) могло не успеть синхронизировать мем-пулл

**Comment by NotEternal** [comment]
нам это не решить
