### ISSUE TITLE
Exchange fee: right tickers

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3394]
![image](https://user-images.githubusercontent.com/35522011/95994193-6a138e00-0e49-11eb-94b9-e2a6cbeb60f0.png)

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/firefox_N9Wk24cZdF6thrR5uTHYmzfAPHSVcCVV.png)

**Comment by JoaoCampos89** [comment]
@shendel is this complete? Can I close it?

**Comment by JoaoCampos89** [comment]
Checked and solved
