### ISSUE TITLE
User can create offer with 0 Balance

### ISSUE THREAD

**Issue by JoaoCampos89** [swaponline/MultiCurrencyWallet#3419]
User can create offers with zero balance this should not be possible. Orders which involve ETH, the user should be warned that needs ETH as well to complete the order and not be able to place in that case as well

## Steps to reproduce

- Go to Exchange
- Create any offer when have zero balance

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by cryptobot123** [comment]
Yeah it should not. anyone can fix that?
