### ISSUE TITLE
Share button displays incorrect URL

### ISSUE THREAD

**Issue by JoaoCampos89** [swaponline/MultiCurrencyWallet#3420]
Share button on offers page create an incorrect url which is not able to be shareable. 

As feature maybe create a share button with multiple actions to share on Telegram, Twitter and so on. Maybe something like this: https://github.com/nygardk/react-share

## Screenshot or description

it shares this: ./en/eth-btc/QmW3ra9iig2mahf5dGgKhkUKreX8e7RvFyTGTJonSKNpLP-1603128628113

instead of: https://swaponline.github.io/#/en/eth-btc/QmW3ra9iig2mahf5dGgKhkUKreX8e7RvFyTGTJonSKNpLP-1603128628113

![image](https://user-images.githubusercontent.com/8621730/96509019-d586a280-1231-11eb-9cdc-40731549fcc8.png)

## Steps to reproduce

- Go to Exchange
- Place Offer
- Click Share button

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by cryptobot123** [comment]
how to fix?
