### ISSUE TITLE
Not enough balance.

### ISSUE THREAD

**Issue by cryptobot123** [swaponline/MultiCurrencyWallet#3431]
![not enough](https://user-images.githubusercontent.com/36717883/96672513-0df3c100-1397-11eb-8a3e-6d89d65dbadb.PNG)

![offer](https://user-images.githubusercontent.com/36717883/96672544-1f3ccd80-1397-11eb-870b-251ae9b6e9f6.PNG)

![wallet](https://user-images.githubusercontent.com/36717883/96672566-2e238000-1397-11eb-9dd5-7cb68070b3bd.PNG)

**I tried buy SWAP for 0.0005   i have enough balance but it keeps showing not enough balance**

**Comment by iower** [comment]
Old UI points to old version. Offers list was rewrited recently.
Can you update and check again?

**Comment by cryptobot123** [comment]
I installed the https://github.com/swaponline/MultiCurrencyWallet

**Comment by cryptobot123** [comment]
okay i'll update here later

**Comment by noxonsu** [comment]
is the bug still appears?

**Comment by iower** [comment]
Seems outdated
