### ISSUE TITLE
GHOST and NEXT coin not showing in add currency 

### ISSUE THREAD

**Issue by cryptobot123** [swaponline/MultiCurrencyWallet#3438]
![not showing](https://user-images.githubusercontent.com/36717883/96766459-b5133f80-140d-11eb-8c94-702b1b9e6c10.PNG)

**Comment by noxonsu** [comment]
check your configs

**Comment by cryptobot123** [comment]
> check your configs

can you point me out where sir?  
i mean exact configs lcoation
thank you

**Comment by noxonsu** [comment]
hm, just noticed this not in the readme. now added https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/README.md#enabledisbale-blockchains-on-domain

**Comment by cryptobot123** [comment]
Thank you now GHOST and NEXT coin is showed now.   :)
