### ISSUE TITLE
ордера пропадают если у клиента вкладка была закрыта, потом открыта, то его ордера не переотсылаются всем

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#344]
## What is working wrong?

ордера пропадают если у клиента вкладка была закрыта, потом открыта, то его ордера не переотсылаются всем

## What should happen instead?

если я открыл заново вкладку, то мои ордера периодически должны рассылатся, чтоб появились опять у всех. 

## Steps to reproduce
1. на андроиде открыл свап онлайн и создал ордер
2. ордер сразу появился на десктопе (и у всех остальных)
3. экран андроида через некоторое время погас
4. андроидовский ордер пропал
5. я включил снова экран андроида, там была открыты ордера и мой там был
6. однако андроидовский ордер проал в бразуере на десктопе
7. перезагрузка десктоповой вкладки не помогла, перезагрузка андроидовской вкладки тоже

## Your system charateristics
хромы, десктоп и андроид + browserstack (macos chrome)

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by noxonsu** [comment]
в общем после нескольких перезагрузок ордер все таки появился, но уведомление о том, что надо начать свап не приходит (в андроид)

**Comment by noxonsu** [comment]
короче после шаманств все таки выполнили свап. как то все  это связано с тем, что у пользователя некоторые оредра скрываются. нужно их не скрывать а показывать и писать что то например "you have already started this swap"

**Comment by noxonsu** [comment]
помогла только полная очистка локалстораджа, после чего чужой оредр снова стал виден

**Comment by nikdementev** [comment]
вообщем если ты закрыл вкладку ты отписываешься от всех евентов, если ты открываешь ее снова подписываешься и нужно время, что бы ты присоединился ко всем, все и так всем отсылается)

**Comment by noxonsu** [comment]
я ждал очень долго, больше часа, ордера не появились. ок, попробуй повтарить мои действия и скжаи все ли у тебя в порядке, если да, ишью ставлю на холд до тех пор пока не смогу повторить баг
