### ISSUE TITLE
Auto-accept for a maker

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3440]
![image](https://user-images.githubusercontent.com/35522011/96838583-7b6c2400-1461-11eb-9679-8a46d8f7c8ac.png)

---

![image](https://user-images.githubusercontent.com/35522011/96838604-82933200-1461-11eb-8f87-1422c1c716c7.png)

**Comment by cryptobot123** [comment]
Yes please  auto accept is  the best.

**Comment by cryptobot123** [comment]
liquidity feature  <3

**Comment by cryptobot123** [comment]
Thank you @shendel  good job
