### ISSUE TITLE
excahnge: set defaults from-to to metamask/custom

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3444]
![](https://screenshots.wpmix.net/chrome_m9KdPwP3JeIOmpBlcDEhY2GjjqLA40pA.png)

**Comment by noxonsu** [comment]
1. ставим по умолчанию в битке внешний адрес
2. по умолчанию выбран метамаск и видна кнопка коннекта
3.

**Comment by shendel** [comment]
связанный https://github.com/swaponline/MultiCurrencyWallet/issues/3567

**Comment by shendel** [comment]
сюда - же
https://github.com/swaponline/MultiCurrencyWallet/issues/3617
