### ISSUE TITLE
Do not allow people to post offers if the funds are not available in GhostX wallet.

### ISSUE THREAD

**Issue by TheNitruc** [swaponline/MultiCurrencyWallet#3461]
# Problem People creating offers in which they don't have the funds.
![ghost!](https://user-images.githubusercontent.com/73307616/97093891-ba46d900-161d-11eb-917f-c4f55c3c9b9e.PNG)

(What is wrong now? What is working not well?)

# Task

(What we need to do in order to implement this feature?)

# Estimate time of implementation

**Comment by noxonsu** [comment]
не давать размещать ордера, если у человека не достаточно денег на это
