### ISSUE TITLE
Cancel offer option is invisible but clickable. UI bug

### ISSUE THREAD

**Issue by TheNitruc** [swaponline/MultiCurrencyWallet#3492]
No option to remove a offer after placing one.
![ghost8](https://user-images.githubusercontent.com/73307616/97626378-16d03c80-1a00-11eb-95cf-472617dfae20.PNG)

## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by TheNitruc** [comment]
Someone could make a trade they didn't want to make because they cannot remove it.

**Comment by TheNitruc** [comment]
![ghost9](https://user-images.githubusercontent.com/73307616/97628750-8136ac00-1a03-11eb-95f4-9312e7ade9b5.PNG)

**Comment by iower** [comment]
Also langSwitch
![image](https://user-images.githubusercontent.com/35522011/97629887-9554ca80-1a50-11eb-9c2f-8602fcb3a479.png)

**Comment by iower** [comment]
The bug is observed only on https://ghostx.live/

**Comment by TheNitruc** [comment]
Yes

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 29, 2020 at 4:42 PM, iower<notifications@github.com> wrote:   


The bug is observed only on https://ghostx.live/

**Comment by noxonsu** [comment]
confirmed on wallet.wpmix.net 

![](https://screenshots.wpmix.net/chrome_WpUhElUz3jDB5Bn07Uiutg3bI7WdYqv6.png)
