### ISSUE TITLE
ARTZ error in the execution of the token contract

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3497]
![](https://screenshots.wpmix.net/Telegram_y8Sv4cwPKwEgc3o0xClLhbKpVUod0K3l.jpg)

**Comment by noxonsu** [comment]
looks like metamask connected

**Comment by shendel** [comment]
Удалось воспроизвести. При подключении метамакса нужна перезагрузка для ре-инициализации кора, в частности создание контрактов для работы с токенами через новый интерфейс веб3. Добавил
