### ISSUE TITLE
Swaps history: wrong time

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3506]
shows local time +3h

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/Telegram_XAeXS5YkwH8nMkHiCh8wcIWFaJ03KeC4.png)

**Comment by iower** [comment]
Maybe related: #3161

**Comment by noxonsu** [comment]
если дату не удается определить то лучше не показывать вовсе

**Comment by shendel** [comment]
нужно обновить плагин
исправлено уже
https://github.com/swaponline/MultiCurrencyWallet/issues/3405
