### ISSUE TITLE
Create Milestone Project to Get Stable version

### ISSUE THREAD

**Issue by JoaoCampos89** [swaponline/MultiCurrencyWallet#3510]
I propose we create a milestone project with the issues listed here by Ghost community, which is spotted to be the ones that they care more to get GhostX close to stable version. So basically we use Github Project feature, group all issues there and then we name project as Exchange stable version. When all that issues are concluded, people will know now that a stable version is out.

## Screenshot or description

List of issues.

![image](https://user-images.githubusercontent.com/8621730/97823162-e5bd6980-1c96-11eb-9ba4-cbf6879716ab.png)

## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by noxonsu** [comment]
Added the milestone ![](https://github.com/swaponline/MultiCurrencyWallet/issues/3497) 

@JoaoCampos89 please ask the tester to open issues, not sent it to the chat (message can be miss)

**Comment by JoaoCampos89** [comment]
@noxonsu all described issues are already submitted. I want this milestone to move all related issues to it and have a feedback process. When all the issues are closed we will know that will be in a stable version

**Comment by noxonsu** [comment]
@JoaoCampos89 can you tag all these issues with the new milestone?

**Comment by JoaoCampos89** [comment]
@noxonsu I added all issues to the milestone. I will check after if some of them are missing.

**Comment by JoaoCampos89** [comment]
Closed as we already created the milestone
