### ISSUE TITLE
the process of helping clients with a stucked swap

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3513]
it's sad to hear your swap was stuck. 

1. Go to history page, find your swap
2. Go to this swap and make screenshot
3. Click "debug" at the bottom of the page and copy debug information https://screenshots.wpmix.net/chrome_IjweoTtuD13XPYDVBJIy6N46EB9aNVFz.png
4. Save console log file in Chrome: https://help.mypurecloud.com/articles/gather-chrome-console-log/, or another browser (https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-s-console-file )
5. attach screenshot, log file and debug information
5. if the swap was performed with known participant ask him to do the same

**Comment by noxonsu** [comment]
по плагину. 

основные проблемы: 
**- что то не работает:** 
Go to wp-admin->dashboard->updates->Check Again

https://screenshots.wpmix.net/chrome_YwPqgnY2cCxj8gjB42SuD0dq6DdmqU1o.png

**кошель вообще не отображется**
please disable all plugins expect mwc

**где прочитать про ...**
http://support.swaponline.io/

**не работает функция**
просим сразу админку, заходим смотрим настройки комиссий, смотрим что на главной кошелька в сорсах отдается в window. переменных и думаем

**Comment by iower** [comment]
Documented
