### ISSUE TITLE
plugin: 12 words seed wasn't showed when user logged in in account B after logout from account A

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3524]
Also, this account BTC was created with that account and now the BTC account has disappeared 👻 we don’t see it at all. It has on it 250 USD perhaps little less.

Either it was reset and renounced from your side OR perhaps it was HIDEN by accident but now we can NOT see how to un hidden the account. Can you verify ? Also that same account NEVER gave the option to see the 12 security words

Noxon, [03.11.20 23:17]
Where you get the address for deposit?

The application. It was created when opening the user account

Noxon, [03.11.20 23:27]
Did you login to this account from the browser you used in another account?

Yes it was from the same browser. Just the BTC account created there is not longer there. It disappeared 👻

**Comment by NotEternal** [comment]
### Test with first account
https://drive.google.com/file/d/1AgnvN2vG53146DEbNHKtYlSN7Q8TT5K7/view?usp=sharing

### Test with second account
https://drive.google.com/file/d/1J4H-tc0gYvJyp3NhRpv20fma_W7ASA70/view?usp=sharing
