### ISSUE TITLE
Plugin: extra output `';`

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3535]
![image](https://user-images.githubusercontent.com/35522011/98220907-cd886b80-1f70-11eb-84f3-dc0356ac895f.png)
![image](https://user-images.githubusercontent.com/35522011/98220995-e98c0d00-1f70-11eb-895e-25058b7a405d.png)
![image](https://user-images.githubusercontent.com/35522011/98221112-0e808000-1f71-11eb-9c1c-55b6a44e7923.png)

## Environment

- Domain: multiple
- Mainnet or Testnet: mainnet

## Your version

- [x] latest
![image](https://user-images.githubusercontent.com/35522011/98221279-438cd280-1f71-11eb-93a5-3ae1ace62405.png)
https://github.com/search?q=b319dd176374c0c0c8703b9c7b7602da5a4f36e2&type=Commits

**Comment by noxonsu** [comment]
не могу повторить( если в сорсы страницы зайти где ее там видно конкретно?

**Comment by noxonsu** [comment]
нашел поправил https://github.com/swaponline/multi-currency-wallet-pro/blob/master/includes/enqueue_scripts/wp_enqueue_scripts.php
