### ISSUE TITLE
Change Make sure you save your private key too "Show Private Key and Save"

### ISSUE THREAD

**Issue by TheNitruc** [swaponline/MultiCurrencyWallet#3560]
# Suggestion for improvement

(What is working not well? What we need to do in order to implement this feature?)

**Comment by noxonsu** [comment]
replaced to "loading"

**Comment by NotEternal** [comment]
![image](https://user-images.githubusercontent.com/61930014/99221939-86c22d80-281c-11eb-80bc-36a372807c01.png)
