### ISSUE TITLE
Will let me send 8 ghost but not 9 or more... 

### ISSUE THREAD

**Issue by TheNitruc** [swaponline/MultiCurrencyWallet#3634]
## Screenshot or description

![ghost1](https://user-images.githubusercontent.com/73307616/99927010-afad5b80-2d11-11eb-8cf8-f6d9c346cd87.PNG)

## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Your version

- [x] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by noxonsu** [comment]
возможно связано https://github.com/swaponline/MultiCurrencyWallet/issues/3636
