### ISSUE TITLE
erc20 send gas fees 10x that of Metamask

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3662]
app
![](https://screenshots.wpmix.net/Telegram_Jz1tpGPErYpRvP9QLis2rna3Eg1edC7M.png)

metamask
![](https://screenshots.wpmix.net/gwRcUZ8Mab.png)

**Comment by iower** [comment]
#3643 would be useful to implement to solve such issues

**Comment by iower** [comment]
Exchange ETH fee also:

![image](https://user-images.githubusercontent.com/35522011/100331413-f214b800-2ff1-11eb-8b10-f61dcc1ad0b5.png)

**Comment by noxonsu** [comment]
related
