### ISSUE TITLE
testrun:bot script (needful for CI)

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3682]
- [x] add script `testrun:bot`
- [x] ...?
- [x] add script to CI

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/3684
https://github.com/swaponline/MultiCurrencyWallet/pull/3686

![image](https://user-images.githubusercontent.com/1880211/100397829-f1653b80-305c-11eb-91c5-4c57fed2e14d.png)

https://github.com/swaponline/MultiCurrencyWallet/pull/3688/checks?check_run_id=1461319876#step:6:11

![image](https://user-images.githubusercontent.com/1880211/100397861-1ce82600-305d-11eb-9d63-f8448a66d30c.png)
![image](https://user-images.githubusercontent.com/1880211/100397894-37ba9a80-305d-11eb-9581-077d6ae1648b.png)
