### ISSUE TITLE
Broken form

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3705]
## Screenshot or description
![image](https://user-images.githubusercontent.com/35522011/100628939-90827f80-334a-11eb-8969-fc7ca2990195.png)

## Environment

- Mainnet

## Your version

- [x] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by iower** [comment]
After b81fcd36527f01ce8f51d2450ad80830ad1526e9

**Comment by noxonsu** [comment]
пока откатил
