### ISSUE TITLE
Bad first addition token

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#3711]
the first time added, it loads endlessly
![image](https://user-images.githubusercontent.com/61930014/100704957-6203b380-33e1-11eb-869e-c8fb0894f980.png)

and console error
![image](https://user-images.githubusercontent.com/61930014/100705081-937c7f00-33e1-11eb-82ff-dcf95fda0115.png)

after reload page it's ok

## Steps to reproduce

- add custom erc20 token
- press add button

## Your version

- [x] latest

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by iower** [comment]
Tested, OK
