### ISSUE TITLE
[ghost] The transaction is in mempool and unconfirmed and not returned more than 2 weeks

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3720]
https://ghostx.live/#/GHOST/tx/4b6dd43dcc71d49bf8ac2d78dbad3745db096b7ecdb40e1639bed31b8dca0ac8

**Comment by noxonsu** [comment]
Fee Rate | 0.00034665 GHOST per kB

**Comment by noxonsu** [comment]
- [ ] what is mempool timeout of ghost blockchain ? @JoaoCampos89 
- [ ] where i can see the current recommended miner fee to show in the sending form?

**Comment by shendel** [comment]
- [ ] Replace by fee?

**Comment by shendel** [comment]
Used default (constant) fee https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/helpers/ghost.ts#L211
Api with dinamic fee not implements
https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/config/mainnet/feeRates.js

**Comment by JoaoCampos89** [comment]
Was this solved? 

what is mempool's timeout of ghost blockchain ? I don't know this information at the moment, needed to check on source code

**Comment by NotEternal** [comment]
Your transaction added to block
https://ghostscan.io/block/c0b0d145e9dae4392108d7c3542a9e09bd3951f5a91aa05506c27be5d2d4d5bf

Can see miner fee here
![image](https://user-images.githubusercontent.com/61930014/101161278-59261280-366b-11eb-83fd-213df2a08797.png)
