### ISSUE TITLE
Swap history - wrong directions

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#3742]
![image](https://user-images.githubusercontent.com/1880211/101006074-159bad80-3572-11eb-950f-7bbefecbfbbf.png)

You buy BTC, and sell ETH, but

![image](https://user-images.githubusercontent.com/1880211/101005661-f7ce4880-3571-11eb-914b-860091425c7e.png)

I sell BTC, and buy ETH

Previus swap show correct info
![image](https://user-images.githubusercontent.com/1880211/101006369-2d733180-3572-11eb-94f6-cd069ff5b597.png)
![image](https://user-images.githubusercontent.com/1880211/101006644-424fc500-3572-11eb-9ad8-f6ea7a0f1a6f.png)

**Comment by noxonsu** [comment]
связано https://github.com/swaponline/MultiCurrencyWallet/issues/3729

**Comment by shendel** [comment]
ну тут скорей всего нет проверки на флаг isMy
