### ISSUE TITLE
warning: preimage length attack для htlc

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3772]
1. Создаешь максимально длинный секрет, вторая сторона простотне может получить деньги тк бч тупо не может вместить его в транзу
2. создать секрет в 1024 символа, взять хеш, начать свап.
3. проверить где валится, подумать как исправить

при обмене битка на токен, солидити принимает только определенное количество байтов, если будет другой секрет, то создатель секрета просто не заберет  эфир и токены и все разбегутся по таймауту.

**Comment by shendel** [comment]
Делали с OP_SIZE , но так и не смержили
https://github.com/swaponline/swap.core/pull/462
