### ISSUE TITLE
remove "connect wallet" banner 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3784]
![](https://screenshots.wpmix.net/chrome_Ln8ZA9bXGcgNBQnX1x0TL0zNrwpbfBrj.png)

лучше вот тут показать ссылку как на #/createWallet прямо оттуда взять

**Comment by iower** [comment]
## More mobile-friendly variant

![image](https://user-images.githubusercontent.com/35522011/101755824-28c0f700-3af7-11eb-837a-a43d6b227860.png)

**Comment by iower** [comment]
wide banner after disconnect
---
![image](https://user-images.githubusercontent.com/35522011/102609069-b5e5fa80-414c-11eb-8ec9-abdf6a82942f.png)
