### ISSUE TITLE
Offers: the list doesn't switch

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3787]
https://swaponline.github.io/

![image](https://user-images.githubusercontent.com/35522011/101753485-8142c500-3af4-11eb-8393-bf3d887c1b16.png)

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/mintty_rXYJXj2ryEaYQt0dxLCNju9X5vqU5EHk.png)

**Comment by noxonsu** [comment]
еще пример как у бинанса столбцы вынесены. прайс первой колонкой (а у нас третей), эмаунт второй колонкой (а у нас первой), тотал третей (а у нас второй). 

![](https://screenshots.wpmix.net/chrome_9dosRuggfeU2RspVhDvE5rWTQiFkN8Yw.png)

у бинфинекса тоже колонки названы, price amount и total
![](https://screenshots.wpmix.net/chrome_P90cLGUXOTPD2WkFQ4N5boq1rn3Nz49B.png)
