### ISSUE TITLE
how to add my own erc 20,23 token to the exchange list ?

### ISSUE THREAD

**Issue by kakamband** [swaponline/MultiCurrencyWallet#3810]
hi swaponline support team ,
how to add my own erc 20,23 token to the exchange list ?
waiting for your response
finest regards

**Comment by NotEternal** [comment]
1 click the button 'Add currency'
2 click the button 'or other currencies' and choose 'Custom erc20 token'

![addToken1](https://user-images.githubusercontent.com/61930014/102048909-e65f2900-3e1a-11eb-8e2d-6d91c387e3b7.png)

3 add token's address and click the 'Next'

![addToken2](https://user-images.githubusercontent.com/61930014/102049023-18708b00-3e1b-11eb-9b8a-aae1316641af.png)

**Comment by NotEternal** [comment]
Seems resolved
