### ISSUE TITLE
Urgent! Transaction History Not Being Recorded

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3853]
After a recent update, when you receive Bitcoin to the wallet it is not recorded/displayed on the Transaction page anymore. This is an important issue, please help. See video attached. 

https://usaupload.com/ur/Edited_20201220_035441.mp4[](https://usaupload.com/ur/Edited_20201220_035441.mp4) 

https://user-images.githubusercontent.com/35522011/102719053-74e91400-430d-11eb-8bc2-3f08be5d10a8.mp4

**Comment by Bitplicity** [comment]
Issue occurs across all devices and browsers.

**Comment by iower** [comment]
Reproduced
