### ISSUE TITLE
Urgent! Login Redirect Problem

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3854]
In custodial mode, everytime a user logs in they are seeing the 'create a new wallet' screen before the page redirects them to their previously created wallet. The page redirects the user to the correct page if they wait for about 5 seconds. 

Issue occurs across all devices and browsers. 

This is very confusing for returning users and makes for a very poor user experience. They should be redirected to their wallet after login. Please help. See video.

 
https://user-images.githubusercontent.com/35522011/102718668-233f8a00-430b-11eb-8290-e328814777dc.mp4

**Comment by iower** [comment]
https://user-images.githubusercontent.com/35522011/102718668-233f8a00-430b-11eb-8290-e328814777dc.mp4

**Comment by shendel** [comment]
Users after log-in not see "createWallet" page now
But - users see empty wallet (before restore) - need some splash screen with information
