### ISSUE TITLE
BTC - Multisign - Calc tx size + Tx price

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#3880]
Constant price for sat per byte?
Incorrect calc tx size?
![image](https://user-images.githubusercontent.com/1880211/103040307-137eaa80-4584-11eb-8d32-a5394163f01f.png)

**Comment by noxonsu** [comment]
we use https://api.blockcypher.com/v1/btc/main

**Comment by Benelli13** [comment]
Incorrect mining commission not in line with the market, which makes it difficult to use the wallet

**Comment by vptteam** [comment]
Incorrect mining commission not in line with the market, which makes it difficult to use the wallet

**Comment by shendel** [comment]
linked https://github.com/swaponline/MultiCurrencyWallet/issues/3726

I recheck, in soft btc transaction size calc correctry(%) - dismatch with broadcasted (size) - 2-5% (in bytes)

**Comment by shendel** [comment]
Reproduced and repeated

Testnet (its no matter)
https://www.blockchain.com/ru/btc-testnet//tx/be6c3f6e2b05c1b1fcd59cb7f709528620f64dca0ceac3e63b9dcace2fd8e8cf
I send 0.0021 Btc, soft can been use only input (unspent) # 4 with 0.00899999 (btc), but, used all unspend (because of this, the transaction size is 2175 bytes (even multiply by 100 - not 150 - already a lot)

we are working on a solution to this problem

**Comment by vptteam** [comment]
A solution should be provided.

**Comment by shendel** [comment]
@vptteam i'm workin on it

**Comment by shendel** [comment]
@vptteam A decision will be made as soon as possible. What the problem is already found, I am working on a solution

**Comment by vptteam** [comment]
@shendel Thank you. let us know once an update is released asap. merry christmas

**Comment by vptteam** [comment]
we are still waiting for this @shendel

**Comment by vptteam** [comment]
issue is not resolved. looks same.
with a balance of $76$,am paying a fee of $26

**Comment by noxonsu** [comment]
we use a higher recommended mining fee, I think it can be lower, for example reducing the fee on 30% will delay transaction only for 10 minutes. Also if your transaction has many inputs (many small incoming transactions) or it's multisig or 2fa address (the size higher on 30%+ in this case because requires 2 signatures) or your wallet has service commission (extra mining fee need to sent this commission to admin's address). I recommend using the regular wallet for small transactions

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/3914
