### ISSUE TITLE
What of Fees How will it go

### ISSUE THREAD

**Issue by Speedevs** [swaponline/MultiCurrencyWallet#3882]
Assuming someone want to buy A token with some ETH how can the swap Collect an automatic Fee of 1Token from the user ETH he wish to swap.
E.g
Bob sends 1ETH 
How can a fee of 1$ of the token he wish to swap be collected from bob

**Comment by NotEternal** [comment]
Just add your commission and address for get commission in the code (which build transaction). Commission for token need be in ETH amoun. After getting ETH commission your can exchange it on dollars
