### ISSUE TITLE
My SECRET_PHRASE is correct ?

### ISSUE THREAD

**Issue by kakamband** [swaponline/MultiCurrencyWallet#3883]
hi swaponline,
My SECRET_PHRASE is : rut aspic formic wave hopeless booby gracious redeem canning dotation bagging hero
is it correct ?

**Comment by iower** [comment]
- Secret phrases should't be public
- If you have any funds on addresses generated from this phrase - please move funds to your other addresses immediately to avoid loss of funds
- If you still want to test phrase->addresses conversion, use https://iancoleman.io/bip39/
