### ISSUE TITLE
Form+metamask: wrong available amount

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3887]
![image](https://user-images.githubusercontent.com/35522011/103094548-afa9bf80-461f-11eb-8de7-e76c2cd5f8a8.png)

**Comment by shendel** [comment]
там минус фии - доступно для обмена, а не сколько на счету

**Comment by shendel** [comment]
аналогично и с btc, и к метамаксу это не имеет никакого отношения

**Comment by shendel** [comment]
@iower если нажать в этой форме "воображаемую" кнопку "продать все" - подставит 0.03204 -> найдет предложение - разница (0.0419-03204) уйдет на майнинг фии
