### ISSUE TITLE
"THIS SWAP IS CANCELED" 

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3906]
## Steps to reproduce
- current master
- clean storage/localstorage

participant: local testnet bot
From: ETH-metamask
To: BTC-internal

- set amount
- press `Exchange now`

## Result

1) Swap starts
2) No txs, error

### Frontend error
![image](https://user-images.githubusercontent.com/35522011/103294441-ae0f3b80-4a13-11eb-84ab-99ef18ecf971.png)

https://user-images.githubusercontent.com/35522011/103295385-a18be280-4a15-11eb-8575-b73c3b284521.mp4

### Bot output 
![image](https://user-images.githubusercontent.com/35522011/103294776-502f2380-4a14-11eb-8149-29a8722f9ea7.png)

## History

![image](https://user-images.githubusercontent.com/35522011/103294942-b451e780-4a14-11eb-8d82-8224f1ae3299.png)

**Comment by noxonsu** [comment]
только что свапнулся без проблем. а в логах бота что то есть? ![](https://screenshots.wpmix.net/chrome_1Xlzq4pcq04wS5CTBiYEEKeFFCM9Sg4X.png)

**Comment by iower** [comment]
Now it's OK
