### ISSUE TITLE
WP: preloader page, set background

### ISSUE THREAD

**Issue by Benelli13** [swaponline/MultiCurrencyWallet#3907]
![Screenshot_20201229-194709_Samsung Internet](https://user-images.githubusercontent.com/76553128/103299923-badd6080-4a0e-11eb-8a0b-0b625f5f2915.jpg)
In which file can add a background to this loading page?

**Comment by NotEternal** [comment]
src/front/client/index.html
~ 560+ line
element with id - wrapper_element

**Comment by Benelli13** [comment]
Can I do this in a WordPress plugin?

**Comment by NotEternal** [comment]
now it cannot be done from WP
