### ISSUE TITLE
add "mining fee is too high" to faq

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3915]
we use a higher recommended mining fee, I think it can be lower, for example reducing the fee on 30% will delay transaction only for 10 minutes. Also if your transaction has many inputs (many small incoming transactions) or it's multisig or 2fa address (the size higher on 30%+ in this case because requires 2 signatures) or your wallet has service commission (extra mining fee need to sent this commission to admin's address). I recommend using the regular wallet for small transactions

**Comment by Speedevs** [comment]
much better
