### ISSUE TITLE
Withdraw: changing fee sum

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3946]
testnet
## 1. Open withdraw btc

![image](https://user-images.githubusercontent.com/35522011/104706287-b4ecbc80-573c-11eb-9073-0c04da1b4d29.png)

---
---

## 2. Enter address and amount, wait few seconds:

![image](https://user-images.githubusercontent.com/35522011/104706430-e5345b00-573c-11eb-9f6f-79f013fcc181.png)

**Comment by shendel** [comment]
Related
https://github.com/swaponline/MultiCurrencyWallet/issues/3914
https://github.com/swaponline/MultiCurrencyWallet/issues/3912
https://github.com/swaponline/MultiCurrencyWallet/issues/3880

**Comment by iower** [comment]
Still observable,
But explainable.
I believe it's not-a-bug,
But UI lack.
