### ISSUE TITLE
exchange: wrong eth mining fee calculation

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3955]
пишет 
Miner fee: **0.0201** ETH + 0.00061366 BTC ≈ $50.44 (?)

хотя последние свапы заняли в 10 раз меньше eth

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/4103#issuecomment-797584523

**Comment by VitaliyShulik** [comment]
seems resolved
