### ISSUE TITLE
swap: link to bitcoin explorer is broken

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3958]
![](https://screenshots.wpmix.net/chrome_96eHo2zvSLM7IyjHEo11XEkgNwVeIR7m.png)

при переходе показывает "Endpoint not found. Please check you" 

https://api.blockcypher.com/v1/btc/main/tx/688c9ea36794a241bed272f5f7917428e72eb37d304ff632c68f2410e68db2c6

**Comment by NotEternal** [comment]
Resolved. I guess it can be closed (tested only for testnet)
