### ISSUE TITLE
WP: Dark theme by default

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3988]
### Feature requests
1)
![image](https://user-images.githubusercontent.com/35522011/106584429-fae0b780-6567-11eb-9bd2-7257b8fef4e3.png)
---
2)
![image](https://user-images.githubusercontent.com/35522011/106584754-6591f300-6568-11eb-8b9a-249d471cf0b4.png)
---
3)
![image](https://user-images.githubusercontent.com/35522011/108410580-6bb2ef80-7249-11eb-98b1-bbc1787b343c.png)
---
4)
![image](https://user-images.githubusercontent.com/35522011/114601124-94d28800-9cae-11eb-9682-b2c375d36972.png)

## Suggestion for improvement

Add checkbox in the admin panel
- [x] `Dark theme by default`

**Comment by noxonsu** [comment]
?? по умолчанию везде тема белая

**Comment by WIZARDOM** [comment]
A dark mode for dark themes would be really important, otherwise, the usability of the wallet would suffer.

**Comment by noxonsu** [comment]
так же просят:
6. Option to disable light/dark function

тоесть надо выбор. лайт дефолт, дарк дефолт, лайт без дарк

**Comment by shendel** [comment]
1. default light
2. default dark
3. only light
4. only dark
