### ISSUE TITLE
Pay the bill error

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4002]
### Before click
![before](https://user-images.githubusercontent.com/61930014/107200002-1c431700-6a32-11eb-8c8c-f2564f743909.png)

### After click
![after](https://user-images.githubusercontent.com/61930014/107200037-26651580-6a32-11eb-86a6-b00b741ce6ea.png)

## Steps to reproduce

- Create new invoice (better for yourself)
- Open the invoice
- Click on 'Pay' button

**Comment by iower** [comment]
See also: #3112
