### ISSUE TITLE
Error: This page should be opened in a secure connection (with "https" in the beginning)

### ISSUE THREAD

**Issue by ismailkherbach** [swaponline/MultiCurrencyWallet#4003]
## Screenshot or description
I am getting this eror when i run npm run dev
Error: This page should be opened in a secure connection (with "https" in the beginning)

![Capture d’écran 2021-02-08 à 3 29 17 PM](https://user-images.githubusercontent.com/26410561/107233234-a5525200-6a22-11eb-9da7-863c0fbac5db.png)

## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: localhost
- Mainnet or Testnet: testnet
- Browser: Chrom 
- OS: Macos

## Your version

- [- ] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [ -] no

## Are real funds at risk?

- [ ] yes
- [ -] no

**Comment by noxonsu** [comment]
- [ ] add clickable link in this message (for plugin clients)
- [ ] add instruction "if you are running npm run dev please follow this instruction: " and link to this issue
