### ISSUE TITLE
How to make a custom build & deploy?

### ISSUE THREAD

**Issue by amrit623** [swaponline/MultiCurrencyWallet#4045]
Hi, I've decided to opt for the build version rather than the wordpress plugin, I've followed all instructions and changed the front-end and ran the build for the mainnet. I've tried to host the files however I'm not sure how to set my version live ? Can someone point me in the right direction please ? 

Thanks.

**Comment by iower** [comment]
Hi,
after you do `npm run build:mainnet` you have the folder `/build-mainnet/`.
It's your builded version. Try to open `/build-mainnet/index.html` in the browser - you should see the working service.
Just copy files from `/build-mainnet/` to your hosting (static, no need for Node.js).
Feel free to edit the docs.

**Comment by amrit623** [comment]
Thank you !

**Comment by amrit623** [comment]
![image](https://user-images.githubusercontent.com/36797987/109083173-4f0d3080-76fd-11eb-8129-5330c0e99d12.png)
ran the build hosted the files but i keep getting hit with this screen it just doesn't load past the first loader ? Appreciate any help Thanks !

**Comment by NotEternal** [comment]
You must be sure that your build with latest version. Before making build, reinstall **node_modules** folder and checking that **Nodejs** has 14 version. Try to update the build and deploy again

**Comment by iower** [comment]
Seems resolved.
@amrit623 please reopen the issue, if you have any questions.
