### ISSUE TITLE
add SWAP token on https://exchange.pancakeswap.finance/

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4058]
часть токенов я перемесил из эфира в сеть бинанса. https://bscscan.com/token/0x92648e4537cdfa1ee743a244465a31aa034b1ce8 вот контракт. нужно добавить на https://exchange.pancakeswap.finance/ 

https://github.com/pancakeswap вот их репо, скорее всего надо пул и что то еще там сделать

как получить токены?
1. https://academy.binance.com/ru/articles/connecting-metamask-to-binance-smart-chain
2. написать мне

**Comment by NotEternal** [comment]
https://github.com/pancakeswap/pancake-swap-interface/issues/231#issuecomment-792413156

**Comment by NotEternal** [comment]
https://github.com/pancakeswap/pancake-swap-interface/issues/231#issuecomment-792413156

**Comment by noxonsu** [comment]
https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x92648e4537cdfa1ee743a244465a31aa034b1ce8 добавил пул
