### ISSUE TITLE
rename eth->bsc (ethereum -> bsc) on https://bsc.swaponline.io/ 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4089]
https://bsc.swaponline.io/#/ тут поднят билд через команду  npm run build:bsc  (точную смотри в пакадж.жсон) надо по всему проекту заменить эфир на binance smart chain чтоб понятно было, что это именно bsc а не эфир. логотип тоже заменить

**Comment by shendel** [comment]
(config.binance === true) - значит билд под бинанс

**Comment by shendel** [comment]
`npm run build:bsc-testnet`
`npm run build:bsc-mainnet`
`npm run build:bsc-testnet-widget`
`npm run build:bsc-mainnet-widget`

**Comment by shendel** [comment]
Для отладки
`npm run dev:bsc-testnet`
`npm run dev:bsc-mainnet`
