### ISSUE TITLE
Doesn't have USDT address in the store

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4162]
## Screenshot or description

![Screenshot_2021-03-29_07-18-11](https://user-images.githubusercontent.com/61930014/112859288-2612ef00-905f-11eb-8429-4ec607781aa2.png)

## Steps to reproduce

- add usdt wallet

## See also
https://github.com/swaponline/MultiCurrencyWallet/blob/b0bf14e279c0e0ffc97f658ed072f61aa7287a94/src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx#L774

**Comment by shendel** [comment]
это не с этим связано
