### ISSUE TITLE
Add NEXT2ERCNEXT (NEXT2WrappedNEXT) exchange

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#4194]
## Steps

- [ ] take test tokens
- [ ] add ERC token https://etherscan.io/token/0x377d552914e7a104bc22b4f3b6268ddc69615be7
- [x] test swap

**Comment by shendel** [comment]
- [ ] развернуть токен на робстене
 - [ ] получить монету NEXT в сети UTXO
 - [ ] проверить свап

**Comment by noxonsu** [comment]
- [ ] ждать пока сделают нормальный инсайт
