### ISSUE TITLE
fix extention compilation

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4199]
```npm run build:chrome-extension-mainnet```
в будущем понадобится для маркетмейкинга в фоне

**Comment by NotEternal** [comment]
пока не работает в браузере. Пока вижу проблему со сборкой, после которой манифест не там и переименованный. И видимо надо обновить его версию. Особенно часть с **security police**, тк не грузятся некоторые внешние скрипты
