### ISSUE TITLE
ITEZ error

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#4221]
![image](https://user-images.githubusercontent.com/35522011/114601473-fa267900-9cae-11eb-9b2b-387a6dad4a42.png)

**Comment by noxonsu** [comment]
попрпвил в баннерах которые грузятся на свапонлайн https://screenshots.wpmix.net/chrome_780vedtANefAO24GlJsFJEJsezudoblf.png 

хз где еще старая ссылка..
