### ISSUE TITLE
Refactoring estimateFeeValue

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4223]
I tried to split estimateFeeValue method from shared/helpers/btc at another module and move it to common/utils/coin/btc, but when I import this module to helpers and try use it an incomprehensible error (maybe it looping imports error) occurs - externalConfig doesn’t work with this error and front client don’t build successfully.

Screenshot:
![image](https://user-images.githubusercontent.com/36531102/114653890-d1cc6800-9d0a-11eb-98de-24fde796f3e2.png)

**Comment by noxonsu** [comment]
ждем пул с минимальнымпримером нерабочего переноса

**Comment by VitaliyShulik** [comment]
Добавил пул
