### ISSUE TITLE
bsc.swaponline.io . Ethereum > BSC + change icon

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4226]
поменять надпись Ethereum на BSC  и иконочку в этом билде

**Comment by iower** [comment]
Related: #4089

**Comment by noxonsu** [comment]
так же он просит мейннет в метамаске (а надо bsc) https://screenshots.wpmix.net/chrome_KpW3B7xYh9DIdauEujDW6afMeBSeANyR.png
