### ISSUE TITLE
Reload page error

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4253]
Error occur when I have some swap history and try reload transaction history page

<img width="697" alt="Screen Shot 2021-04-20 at 12 23 52" src="https://user-images.githubusercontent.com/36531102/115347549-5d466d00-a1d3-11eb-98e6-0724fc5b96cc.png">

- [x] transaction history
- [x] marketmaker page

**Comment by VitaliyShulik** [comment]
also at marketmaker page...

**Comment by shendel** [comment]
mm исправлен в https://github.com/swaponline/MultiCurrencyWallet/pull/4169
