### ISSUE TITLE
make extension workable

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4274]
в данный момент проблема в content security policy который не дает загружать внешние скрипты. надо все втянуть все в билд, по позможности избавится от <script> тегов (либо внести в csp их хеши, короче по ходу дела станет понятно). 

https://github.com/swaponline/MultiCurrencyWallet/blob/master/package.json#L67 так у нас билдится екстеншин

**Comment by noxonsu** [comment]
https://screenshots.wpmix.net/chrome_kfi8oN4gjltmuC5yFSPcDTNs1Os23Sdj.png

**Comment by noxonsu** [comment]
сам екстеншин это тупо билд + manifest.json , он у нас похоже устаревший https://github.com/swaponline/MultiCurrencyWallet/tree/master/src/front/chrome-extension

**Comment by NotEternal** [comment]
связано с #4199
