### ISSUE TITLE
Extension flow fixes

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#4304]
- [x] научится запускать фон

- [x] и при чтоб открывался интерфейс по клику на иконку экстеншна

- [x] убрать сплаш скрин он лишний там

- [x] так же не загружается в стор из за "При загрузке файла произошла ошибка. Повторите попытку. В пакете найдено несколько манифестов: application/assets/manifest.json, manifest.json." нужно удалять лишний манифест

- [ ] список токенов привести только btc, eth, swap, wbtc (для bsc сети btcb)

```

**Comment by noxonsu** [comment]
проверил, действительно в фоне висит index.html но ордера созданные в самом екстеншене исчезают когда закрываешь вкладку

**Comment by VitaliyShulik** [comment]
@noxonsu думаю можно закрывать
