### ISSUE TITLE
mm extention: check everything

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4365]
нужно полностью проверить екстеншин, что он открывает и работает с нужной сетью, что маркетмейкинг активируется, сохраняется, что выставляются ордера, и т.п.. я вот пытаюсь проверить текущий мейннет, который собрал экшин и там куча багов.

**Comment by noxonsu** [comment]
https://drive.google.com/file/d/1t989dEGtiFX-igGd00cQ7sCSrjX6wybG/view

**Comment by noxonsu** [comment]
- [ ] мейннет должен работать на bnb, пара btc/btcb
- [ ] тестнет должен работать на eth, пара btc/wbtc (тестовый)

**Comment by NotEternal** [comment]
При попытке открыть в инког

**Comment by NotEternal** [comment]
Не работает в инкогнито. После открытия в нем открывает обычную вкладку. Если открыт только инкогнито мод,, то запускает браузер с обычной вкладкой
