### ISSUE TITLE
NEXT marketmaking

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#4407]
- [x] Deploy bitpay insight
- [x] Check atomic swap
- [x] Create marketmaking page
- [ ] Tests

---

- (next эксплорер лежит)
- Если https://swaponline.io/ + ETH-NEXT через "Create offer", то надо вернуть "Create offer"

- панель мм NEXT-wNEXT
- проверить, чтоб ETH-NEXT по-прежнему работало (через "Create offer")

- когда будет ETH+BSC, будем предлагать сделать NEXT-NEXTB

## Other
#4194
#4598

**Comment by noxonsu** [comment]
looks like we should only set next config here https://github.com/bitpay/bitcore/blob/master/bitcore-test.config.json#L21
