### ISSUE TITLE
e2e test split tests

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4419]
https://github.com/swaponline/MultiCurrencyWallet/blob/b2325161787ec96216bd765dfb1176b3c1b20d98/tests/e2e/swap.test.ts#L18

нужно разделить чтоб было три галки а не одна. + там вижу какието ошибки https://github.com/swaponline/MultiCurrencyWallet/runs/2590100170?check_suite_focus=true#step:6:48 , тест точно работает?

**Comment by VitaliyShulik** [comment]
Тесты точно работают, я их разделил с помощью `console.log` - там понятно на каком этапе сейчас тест и видно будет где валится.

По поводу ошибок - не понятно почему происходят, но отлавливаются они вот после этих [добавлений](https://github.com/swaponline/MultiCurrencyWallet/blob/b2325161787ec96216bd765dfb1176b3c1b20d98/tests/e2e/utils.ts#L22)  

В одном `describe` я пытался сделать, но не получается никак сделать отдельно в одних и тех же браузерах тесты последовательно - только если для каждого теста отдельные браузеры открывать и уже делать, что очень ресурсозатратно по памяти и могут зависать из-за этого тесты...
