### ISSUE TITLE
BNB (bep20) trading and adding to back end 

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#4421]
With the BSC chain , is it possible to add to the admin area a way to add BEP20 tokens to trade against BNB, also add so fee can be applied . Ideally im looking at trading 
BTC <> ETH
BTC <> BNB
ETH <> BNB
the BNB would be BNB on the BSC chain
Plus BEP20 tokens to exchange to BNB <>
I tried to add BEP20 token on front end but it wouldnt do it

**Comment by NotEternal** [comment]
Hello.
1) You will be able to add bep20 in the admin panel soon.
2) Now we were not going to include the swap commission.
3) We're making swaps between BTC <> BNB and BTC <> BEP20.
4) We're going to make swaps between EVM chains, like BSC and ETH

**Comment by LogicDEX** [comment]
From my understanding atm erc20 can trade between btc and eth? correct?
and eth <> BTC
BNB on the smart chain basically being a clone of eth and BEP20  the same as ERC20, why can BEP 20 also trade against BNB?
as most people that hold and trade BEP would want to use it as a way to trade against BNB at set prices.
And also add in the admin area the same fee structure as the eth chain or make so that what ever is set up on the eth fee set up crosses over to the BNB and BEP20 and i understand what you mean by swap commision fees but at least the withdrawal fee??

**Comment by NotEternal** [comment]
1) now there are swaps berween erc20 and btc
2) we're making swaps berween bep20 and btc
3) that's correct: ETH <> BTC
4) making BNB <> BTC
5) there is commision for withdraw, isn't that right? Do you have problem with BSC withdraw commission, but with ETH chain all right ?

**Comment by LogicDEX** [comment]
with commision , sorry i mean to say there will be commisions on bnb abd bep20 withdrawals?
and the other i understand , but will people be able to trade BNB <> with Bep20 tokens, the same way people can trade Eth <> with erc20 tokens

**Comment by NotEternal** [comment]
Yes, it will for BNB and BEP20 in the withdraw form. I'm not sure about swaps between ETH-like coin and his tokens. We're planning to make swaps ETH <> BNB and BEP20 <> ERC20. Possibly it also will be in the future, but not soon

**Comment by LogicDEX** [comment]
ok i thought eth to erc20 was already there ??
and tried to add bep20 to front end but wouldnt do it and to add withdrawal fee for bnb/bep20 is it in the admin area cant see it 
https://prnt.sc/133xwm6

**Comment by NotEternal** [comment]
Please watch out for #4434
