### ISSUE TITLE
Uncaught (in promise) Error: Cant finish step sign = 1 when on step 3

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4430]
в инкогнито (тейкер), начал свап wbtc-btc подключив валлет коннект в итоге не показывается окно подтверждения в консоле такая ошика https://screenshots.wpmix.net/chrome_G9IHvxJkocBvezJVwYDELSXJNSgn8ALU.png

**Comment by VitaliyShulik** [comment]
кажется решено вот тут #4588
