### ISSUE TITLE
ETH fees so high,can add in Gas adjust?

### ISSUE THREAD

**Issue by cks1368** [swaponline/MultiCurrencyWallet#4433]
(Please write something / give us feedback)

**Comment by iower** [comment]
`send` / `swap`?

For `send`:

`Standard`
`49 Gwei`
`$3.61 | 3 Minutes` (https://www.gasnow.org/)



In the MCW: `70 Gwei`, it uses https://data-api.defipulse.com/api/v1/egs/api/ethgasAPI.json?api-key=53be2a60f8bc0bb818ad161f034286d709a9c4ccb1362054b0543df78e27 most likely, `fastest`

Miner fees may be less for `send`.

I support adding something like this #4108 for ETH/BSC also.
