### ISSUE TITLE
Plugin: select ethlike network while token creation

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#4434]
## Problem
![image](https://user-images.githubusercontent.com/35522011/118608071-be616080-b7d2-11eb-9dc0-9f19aa1d41ff.png)

## Solution

1) Plugin: add dropdown, write selected network to `window.widgetERC20Tokens` OR write tokens to  `window.widgetBEP20Tokens`

```
window.widgetERC20Tokens = {
    'weenus': {
    address: '0x101848D5C5bBca18E6b4431eEdF6B95E9ADF82FA',
    decimals: 18,
    fullName: 'WEENUS',
    icon: '',
    customEcxchangeRate: '1',
    iconBgColor: '',
    howToDeposit: '',
    howToWithdraw: '',
  },
    'xeenus': {
    address: '0x7E0480Ca9fD50EB7A3855Cf53c347A1b4d6A2FF5',
    decimals: 18,
    fullName: 'XEENUS',
    icon: '',
    customEcxchangeRate: '1',
    iconBgColor: '',
    howToDeposit: '',
    howToWithdraw: '',
  }
}
```

2) Front: read network field (fallback to ETH if undefined)

**Comment by NotEternal** [comment]
Also need to add commission field for BNB, BEP20 tokens

**Comment by noxonsu** [comment]
наиболее просто тип сети прямо в массиве ```window.widgetERC20Tokens = {
    'weenus': {
    address: '0x101848D5C5bBca18E6b4431eEdF6B95E9ADF82FA',
    decimals: 18,
    fullName: 'WEENUS',
    icon: '',
    customEcxchangeRate: '1',
    iconBgColor: '',
    howToDeposit: '',
    howToWithdraw: '',
    **network:'bsc'**
  }
  ```
@NotEternal так можно?

**Comment by NotEternal** [comment]
Да. Возможно лучше полностью указывать название сети. Еще поле со стандартом добавить
```
standard: 'bep20'
```

Плюс все так же нужно все места обойти и подумать как теперь это хранить. Сейчас везде просто по именам, как тут например
```
Object.keys(window.widgetERC20Tokens).forEach((key) => {
  widgetCurrencies.push(key.toUpperCase())
})
```

**Comment by NotEternal** [comment]
хотя нет, там же одинаковые ключи в виде названий будут в обьекте. То есть сейчас у нас обьект с ключами в виде названий, но если я все места увидел, то там и правда можно все это вместо обьекта в массиве получать
```
window.widgetERC20Tokens = [
  { name: weenus, standard: erc20 }
  { name: smth else, .... }
]
```
