### ISSUE TITLE
amount too low

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4441]
![](https://screenshots.wpmix.net/firefox_OxuTfc8wEy8tewUIqdn5GdLDfB10LzXL.png)

- [x] нужно писать конкретнее "слишком маленькая, не покрывает обмен + майнинг фи"

**Comment by noxonsu** [comment]
при это ввожу 0.02 уже просит ввести поменьше 
![](https://screenshots.wpmix.net/firefox_pVpQf13UNEC7xcO6qoGAB8AiMwVVFPsl.png)

**Comment by noxonsu** [comment]
хм. первая ошибка пропала неожиданно.. странно

**Comment by noxonsu** [comment]
- [ ] https://screenshots.wpmix.net/firefox_VSOWx26hazqbM35qATs6LExXG32owjOb.png

**Comment by VitaliyShulik** [comment]
> при это ввожу 0.02 уже просит ввести поменьше

почему-то не сфетчился баланс - у меня все норм при проверке сейчас...

**Comment by VitaliyShulik** [comment]
@noxonsu 
- [ ] нужно ropsten.swaponline.io добавить в вайтлист 

<img width="804" alt="Screen Shot 2021-05-20 at 10 35 29" src="https://user-images.githubusercontent.com/36531102/118919933-3f496500-b957-11eb-82dd-f760217ac4ce.png">
