### ISSUE TITLE
Exchange: create btc wallet

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4443]
When the user creates a BTC wallet, on the second step of choosing security goes to Exchange page and there clicks on creating a BTC wallet - an error occurring

<img width="819" alt="Screen Shot 2021-05-20 at 12 56 36" src="https://user-images.githubusercontent.com/36531102/118933298-d9ff6f00-b96a-11eb-8dac-221d27b6629a.png">

**Comment by NotEternal** [comment]
@VitaliyShulik seem resolved. I can't reproduce it

**Comment by VitaliyShulik** [comment]
Yes, it's resolved
