### ISSUE TITLE
swap: wbtc>btc empty "deposit" step

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4445]
- [x] https://screenshots.wpmix.net/chrome_7iFtGUNEMEntSwyqtJT91OnshHVKQeRe.png у тейкера

**Comment by VitaliyShulik** [comment]
видимо у мейкера не подтвержденная транзакция и он не может сделать отправку транзакции депозита из-за этого, нужно больше информации почему так произошло, логи есть?
