### ISSUE TITLE
new network: add polygon (matic) to wallet and swap

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4448]
https://medium.com/stakingbits/setting-up-metamask-for-polygon-matic-network-838058f6d844

- [x] добавить на кошель 
- [x] добавить токен wbtc https://info.quickswap.exchange/token/0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6
- [x] добавить в swap пару BTC/WBTC (on polygon) или BTCB (bsc)/WBTC (polygon)
- [x] рефакторинг, чтоб в дальнейшем еще проще было добавлять сети)

**Comment by VitaliyShulik** [comment]
**Core**:
- [ ] Add Coins in constants (COINS.ts)
- [ ] Add web3Matic to Swap.App
- [ ] Add Matic to swap.app constants TRADE_TICKERS
- [ ] Add register erc20Matic tokens to Swap.App/utils (в дальнейшем лучше рефакторинг сделать как отдельный класс и наследовать от него форматы токенов)
- [ ] Add swap.auth for matic
- [ ] Add Flow MATIC2BTC, MATICTOKEN2BTC and vice versa (еще нужно на другие utxo валюты)
- [ ] Add MaticSwap and MaticTokenSwap classes to swap.swaps
- [ ] Add Matic to externalConfig —> blockchainSwapEnabled
- [ ] Add maticData to ConfirmBeginSwap.tsx 

**Front**:
- [ ] Add maticToken to helpers
- [ ] Add Matic to helpers constants TRADE_TICKERS
- [ ] Add MATIC_TOKEN case to fetchCoinFee method
- [ ] Add Matic to helpers swaps
- [ ] Add Matic flows to instances newSwap
- [ ] Add Matic to CreateWallet Steps startPack
- [ ] Add Matic ticker to prepareDropDownOptions
- [ ] Add UTXO_to_ERC20MATIC, UTXO_to_MATIC classes and vice versa to swaps 
- [ ] Add matic to redux redusers currencies

**Comment by NotEternal** [comment]
Всего не упомнишь. Будем по дороге сюда добавлять инфу с галочками. Помощь в будущем и легче следить за сложностью добавления. После всего имеет смысл обновить наши доки, тк что-то устарело/обновилось.

Добавил на кошелек (Создание, отображение, отправка). Проблемы с получением всех транзакций. Как я думал что надо будет убрать эксплореры и делать через веб3, но у веб3 нет метода для получения сразу всех транз (плохо искал?). Это отдельный вопрос, что делать если будем сами все находить через веб3 и рпс. Главное я еще не нашел апи для Matic chain, чтобы получать все транзы и сейчас их не видно в истории.
Для общего познания есть такой сервис [Covalent](https://www.covalenthq.com/)

**Comment by VitaliyShulik** [comment]
> Проблемы с получением всех транзакций. Как я думал что надо будет убрать эксплореры и делать через веб3, но у веб3 нет метода для получения сразу всех транз (плохо искал?).

да, вроде нет такого метода, одно из решений - нужно по всем блокам пробегаться по всем транзакциям и сравнивать адреса куда или откуда со своим адресом - долгая и затратная операция
