### ISSUE TITLE
problem with the exchange

### ISSUE THREAD

**Issue by rabahaldoori** [swaponline/MultiCurrencyWallet#4465]
I need help please I have problem with the exchange. Its keep loading and after that say no order found You can see the images

![New222](https://user-images.githubusercontent.com/31085177/119933614-0e19f780-bf4a-11eb-855f-a7c35cb99d9a.PNG)

and when i trying to add any token i got this massage "Please add a valid ERC20 address!"

Thank you!

**Comment by VitaliyShulik** [comment]
Hello

> I need help please I have problem with the exchange. Its keep loading and after that say no order found You can see the images

everything is displayed correctly, maybe there are no orders and because of this you cannot carry out Swap

> and when i trying to add any token i got this massage "Please add a valid ERC20 address!"

please follow this issue #4446

**Comment by rabahaldoori** [comment]
what do you mean there are no orders and because ? you mean people have to make sell order so i can my users got swap ?

about the ERC20 i mean from the admin panel


![GR](https://user-images.githubusercontent.com/31085177/119976092-3c182f80-bf7c-11eb-8164-b989a8076d5d.PNG)

you can see the  "Node is down "

**Comment by NotEternal** [comment]
hello @rabahaldoori. We're solving problem with token addition and you will be able to do it soon.

About orders:
you can't see it because:
1. people don't create their own orders
2. people aren't online
3. problem is on our side)

**Comment by NotEternal** [comment]
Also don't forget to switch drop down currency 
![Screenshot 2021-05-28 10:09:46](https://user-images.githubusercontent.com/61930014/120005144-2e26d680-bf9d-11eb-97fd-975aa3f6abe6.png)

You will see  available orders for this pair here
![Screenshot 2021-05-28 10:10:46](https://user-images.githubusercontent.com/61930014/120005560-907fd700-bf9d-11eb-986b-d6b616a35f3a.png)

**Comment by rabahaldoori** [comment]
ok thanks waiting for solve

**Comment by rabahaldoori** [comment]
@VitaliyShulik any update or estimate time to fix ?

**Comment by VitaliyShulik** [comment]
@rabahaldoori look like resolved, if something wrong, please reopen this issue
