### ISSUE TITLE
Exchange: add button "Add Correct Network"

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4506]
Noxon, [03.06.21 23:30]
по поводу метамаска, думаю логично если чел выбрал в списке направление чтоб мы просили его переключить на нужную сеть https://screenshots.wpmix.net/chrome_Y36XcHUOuKiQv7CVeVHbCpVztj01ezjn.png

Noxon, [03.06.21 23:31]
например если выбираем btcb, появляется ссылочка https://screenshots.wpmix.net/chrome_ZGo0Q1sdrabyNgsbKrxkWUkga13k8A9W.png switch to BSC

Noxon, [03.06.21 23:31]
код можно стырить отсюда https://github.com/antonnell/networklist-org/blob/d7a5c24f4ad25995c64ebe86a922eea874885973/components/chain/chain.js#L62

**Comment by shendel** [comment]
Для evmLike валю - при подключении метамакса - в коре использовать веб3 от метамакса
https://github.com/swaponline/MultiCurrencyWallet/pull/4496/files#diff-3c0e74c2432a9a4a376157fa190fd17cd606d210637658410abac0bc8eed5b58R306

**Comment by VitaliyShulik** [comment]
> например если выбираем btcb, появляется ссылочка https://screenshots.wpmix.net/chrome_ZGo0Q1sdrabyNgsbKrxkWUkga13k8A9W.png switch to BSC

Мы поменять сеть сами не можем, но у нас уже сделано чтоб хендлинг был неправильной сети и просьба поменять ее на валидную


> код можно стырить отсюда https://github.com/antonnell/networklist-org/blob/d7a5c24f4ad25995c64ebe86a922eea874885973/components/chain/chain.js#L62

По этому коду видно что можно пользователю дать возможность быстро добавить сеть в свой метамаск, а переключиться он сам все равно должен...
Думаю можно добавить кнопку "добавить валидную сеть", с нашими данными сети...

**Comment by noxonsu** [comment]
Да
