### ISSUE TITLE
Add custom tokens (erc20, bep20, matic erc20, etc) via web3

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#4508]
Нужно избавить от апи при добавлении произвольных токенов
(https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/components/modals/AddCustomToken/index.tsx#L73, https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/components/modals/AddCustomToken/index.tsx#L85, https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/components/modals/AddCustomToken/index.tsx#L96, https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/components/modals/AddCustomToken/index.tsx#L107)
План действия
1. Через web3 проверяем - контракт это или нет (getCode, пример тут https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/redux/actions/ethLikeAction.ts#L534)
2. Если это контракт - используя human-abi-token - создаем контракт (web3.eth.Contract - пример https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/redux/actions/erc20LikeAction.ts#L232)
3. Имея контракт - запрашиваем данные используя методы контракта (getName, getSymbol, getDecimals)
4. Учесть что этих методов может не быть - использовать свойства _name, _symbol, _decimals
5. Реализовать это в виде функции в классе/интерфейсе ethlikeAction https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/redux/actions/erc20LikeAction.ts

**Comment by noxonsu** [comment]
- [ ] это вместо езерскана получается

**Comment by shendel** [comment]
`
erc20LikeAction.getInfoAboutToken(contractAddress)
{
  name,
  symbol,
  decimals,
}

false - это не контракт токена (нет кода или нет методов)
`
