### ISSUE TITLE
Help Needed With Installation

### ISSUE THREAD

**Issue by alexwalker0** [swaponline/MultiCurrencyWallet#4512]
Hey,

I hope you're having a fantastic day.

I need help to install the code into my website. Could you please give me the steps to uploading the code onto my Server File Manager?

Thank you,
Alex

**Comment by NotEternal** [comment]
Hi, what exactly can't you do ? Please make screenshots if you can

**Comment by alexwalker0** [comment]
> Hi, what exactly can't you do ? Please make screenshots if you can

Hi,

Thank you for responding. When I upload the files into the file manager of my server nothing appears onto my site, when I move the index.html/php to public_html the only thing that popped up on my site was a loading screen. I've waited a long time for it to load and nothing happened. Please note that I'm using 000webhost a free web host site and I'm going to move the files onto a paid server once I figure out how the system works.

Thank you,
Alex

**Comment by NotEternal** [comment]
I'm not sure what's happend, but probably you make wrong actions. Check their documentation and if you're doing all right then write to thair support. Also you can see some logs in the console (maybe it will be useful). Just press F12 button

**Comment by NotEternal** [comment]
Seem to resolved. @alexwalker0 please reopen this issue if something wrong
