### ISSUE TITLE
Metamask: don't hide internal wallets

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4513]
When users connect to metamask - all evmLike coins are hidden

Before connecting
<img width="580" alt="Screen Shot 2021-06-07 at 12 50 03" src="https://user-images.githubusercontent.com/36531102/120971905-ff73e180-c78e-11eb-9b7f-6d518292542d.png">

After connecting
<img width="602" alt="Screen Shot 2021-06-07 at 12 53 22" src="https://user-images.githubusercontent.com/36531102/120972256-5f6a8800-c78f-11eb-8332-f2cd261566ac.png">

**Comment by noxonsu** [comment]
почему не скрывать то, если чел подключил метамаск, то мы теперь вов сех dspjsdf[ работаем с метамаском, если оставить старые токены, то могут быть ошибки чем подписывать транзу. я думаю пользователей одновременно и внутреннего и метамаска будет очень мало, все сразу подключают метамаск и все. ну либо исопльзуют как кошелек. в любом случае таск выглядит как тяжелый для дебага без очевидно практической ценности, лучше сфокусироваться на btc-wbtc(matic)
