### ISSUE TITLE
Exchange: add check at swap exists when init swap

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4516]
когда пытаешься начать второй свап с тем же мм, свап начинается но сразу cancelled

![](https://screenshots.wpmix.net/chrome_AUrKeery5ZrLkyuRSoXSt2boL5bsh669.png)

**Comment by noxonsu** [comment]
- [ ] например можно писать "у вас есть незаврешенный свап в этом направлении, дождитесь рефанда или попробуйте другое направление"

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_QBIUZFH0cULbPb9FI81Bocrf1kxZTwVF.png) проверка в контракте которая не дает запустить свап

**Comment by VitaliyShulik** [comment]
Для того чтобы проверить есть ли своп у этих адресов нужно адрес как мейкера, так и тейкера...

@noxonsu @shendel Можем ли мы до начала свопа давать тейкеру адрес мейкера для проверки свопов на возможность стартануть?

**Comment by noxonsu** [comment]
Адрес мейкера в ордере прямо есть

**Comment by noxonsu** [comment]
Вроде
