### ISSUE TITLE
metamask: check networkid and current adress for every transaction

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4519]
- [x] аппрув (exchange)
- [ ] создание свапа
- [ ] вывод свапа
- [x] отправка обычной транзы
- [ ] рефанд

в этих транзах есть шанс, что юзер переключит сеть или текущий адрес на другой, тогда будет ошибка в исполнении контракта. нужно говорить пользоватлею мол хотим выполнить транзу но тебе нужно выбрать другую сеть или подключится с адресом такимто.

**Comment by VitaliyShulik** [comment]
> * отправка обычной транзы

в форме отправки кошелек просто не отразится если будет неправильная сеть
