### ISSUE TITLE
a few bugs i see

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#4531]
![](http://i.prntscr.com/sdzpCre0ReC-rrdevgepYQ.png)
On the account page it isnt showing the icons , have added the token via admin , and shows icon in admin area but on front end nothing in the space for it except a capital E

Also the only coins that it is showing to trade is BTC and ETH, not showing BNB or anything else 
![](http://i.prntscr.com/_ZW7osmzSpmdCaHrbi__0A.png)

i seen on the swap site it was showing BNB, are any BEP20 tokens able to trade??
I believe i have the latest Plugin version: 1.1.1054 | Build version: 41b0d8 | Updated: 19h : 02m : 09s ago.

**Comment by LogicDEX** [comment]
Hi when might we see update for these things??

**Comment by NotEternal** [comment]
@LogicDEX if something wrong, please reopen this issue
