### ISSUE TITLE
exchange form: not enough balance when select "external wallet" in "from" field

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4543]
![](https://screenshots.wpmix.net/chrome_a2Iz37xDaZhXdFuR8tLMk3rz78pDx1fS.png)

**Comment by noxonsu** [comment]
нужно начинать свап и там показывать "закиньте денег"

**Comment by NotEternal** [comment]
Получилось запустить. Возможно у тебя не хватало на комиссию со стороны **WBTC** Еще проверю.

![Screenshot 2021-06-15 06:23:56](https://user-images.githubusercontent.com/61930014/122044912-ac0f1e00-cda2-11eb-9e5b-1e89591cd6ce.png)
