### ISSUE TITLE
No RPC Url available for chainId: 80001

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4544]
в консоли эта ошибка, может что то ломает?

**Comment by NotEternal** [comment]
Это Matic Testnet Mumbai. Сейчас не вижу спама такого. Рпс у нас стоит публичный https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/config/testnet/web3.js#L4

**Comment by VitaliyShulik** [comment]
> в консоли эта ошибка, может что то ломает?

Во время свапа эта ошибка выходит? может из-за того что много раз обращаемся для проверки майнинга транзакции evmLike? и из-за того что публичная нода - там стоят лимиты...

**Comment by NotEternal** [comment]
по поводу спама

![Screenshot 2021-06-15 04:45:00](https://user-images.githubusercontent.com/61930014/122032601-6ac44180-cd95-11eb-9b6a-251685463340.png)
![Screenshot 2021-06-15 04:45:48](https://user-images.githubusercontent.com/61930014/122032615-6dbf3200-cd95-11eb-9238-12d2bee62b8b.png)
![Screenshot 2021-06-15 04:46:11](https://user-images.githubusercontent.com/61930014/122032639-71eb4f80-cd95-11eb-8ec9-67ef926255d1.png)
![Screenshot 2021-06-15 04:48:13](https://user-images.githubusercontent.com/61930014/122032645-73b51300-cd95-11eb-95e6-9ba19d9b7f8d.png)

**Comment by VitaliyShulik** [comment]
> в консоли эта ошибка, может что то ломает?

выяснил что component AddressSelect проверяет старые и новые пропсы и если разные то обновляет компонент...
ну вот когда выходила эта ошибка - выставлялся балансе NaN, a (NaN !== NaN) = true и компонент пытался бесконечно раз ререндерится и выходила ошибка...
