### ISSUE TITLE
Pages: remove Currency.tsx

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4545]
думаю можно удалить эту страницу, так как она не используется либо доработать 

@noxonsu что думаешь?

**Comment by noxonsu** [comment]
я хз что это , скрин?

**Comment by VitaliyShulik** [comment]
https://github.com/swaponline/MultiCurrencyWallet/blob/867e76e1be0098174c2a6a64f1c328b5c7ce83dc/src/front/shared/routes/index.tsx#L97

в роутах только используется, но зайти на эту страницу у меня не получилось никак

**Comment by noxonsu** [comment]
удалить конечно
