### ISSUE TITLE
WalletConnect: can't connect with trust wallet

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4568]
<img width="1162" alt="Screen Shot 2021-06-22 at 12 34 47" src="https://user-images.githubusercontent.com/36531102/122875675-629c7100-d356-11eb-9fbb-bf055ca7f0a2.png">

**Comment by Newheaven003** [comment]
Please I'm using the free version of this plugin.
And when a user clicks on connect wallet, nothing happens

**Comment by VitaliyShulik** [comment]
@NotEternal I used mobile Trust wallet

**Comment by VitaliyShulik** [comment]
Checked again and wallet have connected.
