### ISSUE TITLE
Not displaying what i thought

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#4577]
Hi mate wanted to have a chat abount the atomic swap
for some reason Im not sure why its not working how I expected it to 
I bought the WP extended version and it says it updated 12 hrs ago 
https://prnt.sc/16fyi40
I added a Bep20 token backen shows logo and all that fine, but on the front end wont show logo 
https://prnt.sc/16fylq9
Frontend
https://prnt.sc/16fzo6j
In the market or exchange area only coins it is showing is eth and btc??
https://prnt.sc/16fzye8
I did purchase the extended liscense originally, it has lapsed but i assumed it would still update to latest version or do i need to purchase it again??

**Comment by noxonsu** [comment]
i assigneв the dev to fix icon issue..

>I did purchase the extended liscense originally, it has lapsed but i assumed it would still update to latest version or do i need to purchase it again??

click "renew support" on codecanyon. An expired license DOES NOT AFFECT the plugin's functionality. You still can download versions from codecanyon (but updates are released less often there)

**Comment by VitaliyShulik** [comment]
> i assigneв the dev to fix icon issue..

We have opened issue #4572, @LogicDEX follow to updates

**Comment by NotEternal** [comment]
@LogicDEX please check functional again and answer if you have any problems for now

**Comment by LogicDEX** [comment]
@NotEternal Hi mate it it has updated and here is the screen shot of the build and update time
https://prnt.sc/16ti0qs
But to me there is no difference from before , all things i noted are still the same

**Comment by NotEternal** [comment]
@LogicDEX what's now, I hope all right. I've checked token addition on testnet/mainnet and their icons. Also I can see custom tokens from my WP panel on the Exchange page. Don't forget to update plugin )
