### ISSUE TITLE
Can't add new token with wordpress plugin [bf6fa0]

### ISSUE THREAD

**Issue by kinnaj00** [swaponline/MultiCurrencyWallet#4603]
## Steps to reproduce

- Open wordpress dashboard
- Try to add new ERC20 Token
- Nothing happens when clicking on "add new token"

Console:

admin.js?ver=1.1.1199-bf6fa0:58 Uncaught TypeError: Cannot read property 'get' of undefined
    at HTMLInputElement.<anonymous> (admin.js?ver=1.1.1199-bf6fa0:58)
    at HTMLInputElement.dispatch (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=ceb257c04ce5e3901eeec79fd47bf9dd:formatted:2030)
    at HTMLInputElement.v.handle (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=ceb257c04ce5e3901eeec79fd47bf9dd:formatted:1962)
(anonymous) @ admin.js?ver=1.1.1199-bf6fa0:58
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=ceb257c04ce5e3901eeec79fd47bf9dd:formatted:2030
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=ceb257c04ce5e3901eeec79fd47bf9dd:formatted:1962

============
var howDeposit = window.tinyMCE.get('howdeposit').getContent();

Uncaught TypeError: Cannot read property 'get' of undefined
============

## Environment

- Mainnet or Testnet: Mainnet
- Browser: Chrome
- OS: Windows

## Your version

- [ x ] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [ x ] no

## Are real funds at risk?

- [ ] yes
- [ x ] no

**Comment by noxonsu** [comment]
version of plugin?

**Comment by kinnaj00** [comment]
> version of plugin?

newest available 1.1.1199

**Comment by NotEternal** [comment]
> > version of plugin?
> 
> newest available 1.1.1199

@kinnaj00 please check it again with latest version **1.1.1201** and is it possible make screenshots of this problem

**Comment by kinnaj00** [comment]
Updated to latest version 1.1.1201 but still can't add new tokens in the backend... still have the same error... cannot send any screenshot because nothing happens when I click on "add new token".

I just have the chrome dev tool console errors as mentioned above!

**Comment by kinnaj00** [comment]
![Unbenannt123123](https://user-images.githubusercontent.com/78449307/124584217-47e8f280-de54-11eb-915a-5e78c3e1024b.JPG)

**Comment by NotEternal** [comment]
@kinnaj00 do you have the telegram accaunt ? If so then please write in [support bot](https://t.me/swaponlinebot)

**Comment by kinnaj00** [comment]
Disable visual editor checkbox did it for me! Case closed
