### ISSUE TITLE
Disable Arbitrum from wordpress backend

### ISSUE THREAD

**Issue by kinnaj00** [swaponline/MultiCurrencyWallet#4604]
## Suggestion for improvement

Disable Arbitrum from wordpress backend (Like all other BNB, MATIC etc.)

(What is working not well? What we need to do in order to implement this feature?)

**Comment by NotEternal** [comment]
![screenshot-localhost_9001-2021 07 05-11_43_50](https://user-images.githubusercontent.com/61930014/124501266-d55e1100-dd86-11eb-8a23-ad3a2013db42.png)

**Comment by kinnaj00** [comment]
Fresh install from codecanyon. So the update I made a couple days ago didnt add this option… I have arbitrum available but the checkbox in the backend didnt appear

**Comment by LogicDEX** [comment]
also running latest version and cannot disable arbitrum, cant see the check box in the back end

**Comment by NotEternal** [comment]
> Fresh install from codecanyon. So the update I made a couple days ago didnt add this option… I have arbitrum available but the checkbox in the backend didnt appear
> […](#)
> Am 05.07.2021 um 18:48 schrieb NotEternal ***@***.***>: ﻿ Closed #4604. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I added this option only yesterday

**Comment by NotEternal** [comment]
@LogicDEX @kinnaj00 please update your plugins and check it again

Version for now: **Plugin version: 1.1.1201**

**Comment by LogicDEX** [comment]
@NotEternal it has version 1.1.1200 atm , will it update through the back end, if so doesnt seem to have come through yet or do I need to download it from codecanyon ??

**Comment by NotEternal** [comment]
> @NotEternal it has version 1.1.1200 atm , will it update through the back end, if so doesnt seem to have come through yet or do I need to download it from codecanyon ??

do you have any updates in the WP panel ?

**Comment by LogicDEX** [comment]
Not at the moment this was the last update like 5 hours ago
https://prnt.sc/18yueyd

**Comment by NotEternal** [comment]
in **1.1.1200** version should already be this arbitrum checkbox

**Comment by LogicDEX** [comment]
https://prnt.sc/18z3arf
Thats what i see in the admin area, cleared cache and all that hard refresh

**Comment by NotEternal** [comment]
then try to download it from codecanyon

**Comment by LogicDEX** [comment]
> then try to download it from codecanyon

https://prnt.sc/18z8les
its a older version

**Comment by kinnaj00** [comment]
Since update 1.1.1201 everything is working again & I can see the arbitrum checkbox!

**Comment by LogicDEX** [comment]
> Since update 1.1.1201 everything is working again & I can see the arbitrum checkbox!

were did the update come from still cant seem to find it , or in codecanyon getting older version and nothing in the WP dashboard
