### ISSUE TITLE
Custom exchange rate: check/correct

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4630]
Need to check that custom exchange rate, which we can set in the WP panel, is working

**Comment by noxonsu** [comment]
custom exchange rate он тупо для калькуляции баланса в баксах в кошельке, на обменник никак не влияет (возможно стоит прояснить в адмикне)

**Comment by NotEternal** [comment]
тогда лучшее описание в тексте. Как раз для тех кто не вкурсе, довольно логично думать что название **custom exchange rate**, как то влияет на свапы

**Comment by noxonsu** [comment]
Token to fiat conversion rate (only for information) https://screenshots.wpmix.net/chrome_69QZIwazvUPCevyt6LwOkmm2aPOTIPH0.png
