### ISSUE TITLE
Replace Ethereum testnet

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4649]
Ropsten --> Rinkeby

- [x] Change evmNetwork
- [x] Deploy swaps smart-contracts (ETH/UTXO and ETHTOKEN/UTXO)
- [x] Deploy tokens smart-contracts (WBTC and NEXT)(SWAP, USDT, WEENUS already added)
- [x] Add ETH and tokens to tests accounts

**Comment by noxonsu** [comment]
все токены не обязательно деплоить, только wbtc, next, с осталными не работаем
