### ISSUE TITLE
Three vertical Dots not visible on mobile devices

### ISSUE THREAD

**Issue by kinnaj00** [swaponline/MultiCurrencyWallet#4651]
## Environment

- Mainnet or Testnet: Mainnet
- Browser: Safari
- OS: IOS

## Your version

- [x] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by NotEternal** [comment]
@kinnaj00 can you send some screenshots of problem ? Which browser do you use ?
I checked it in the Firefox/Chrome/Brave browser and can't see this problem

**Comment by kinnaj00** [comment]
Used Safari for iPhone - Still not able to see them
![IMG_0628](https://user-images.githubusercontent.com/78449307/126163764-efbd383e-a316-4e10-b5dd-b7acc17fa7d2.jpg)

**Comment by kinnaj00** [comment]
*Version 1.1.1226

**Comment by NotEternal** [comment]
@kinnaj00 you can check dots visibility

**Comment by kinnaj00** [comment]
- [ ] fixed
