### ISSUE TITLE
Cut off deposit window/popup

### ISSUE THREAD

**Issue by kinnaj00** [swaponline/MultiCurrencyWallet#4672]
![Inkedbug3_LI](https://user-images.githubusercontent.com/78449307/126904974-aec14a1a-c804-48a9-a32d-2d994a3f3836.jpg)
Latest version 1.1.1236 / Chrome / Windows / Wordpress

*just happens sometimes (not always)
Can't figure out what the problem is. Happens then you click many buttons or tabs.

**Comment by VitaliyShulik** [comment]
@kinnaj00 on which page it is happened?

**Comment by kinnaj00** [comment]
Can't figure out when this happens exactly. But it happens sometimes after reloading the page or using the app for some time. I try to figure out when this problem occurs. I keep you updated when I have more information about reproduction this error :)

**Comment by VitaliyShulik** [comment]
Okay, thanks, now we add label 'On Hold' for this issue
