### ISSUE TITLE
Strange Grey Background while loading deposit QR Code

### ISSUE THREAD

**Issue by kinnaj00** [swaponline/MultiCurrencyWallet#4673]
![bug4](https://user-images.githubusercontent.com/78449307/126905193-e8fa8c22-4b2b-4479-b7c7-641be6d45aeb.JPG)
Latest version 1.1.1236 / Chrome / Windows / Wordpress

**Comment by kinnaj00** [comment]
I hope it's okay that I report bugs here! Let me know if this helps the project a little bit :)

**Comment by NotEternal** [comment]
> I hope it's okay that I report bugs here! Let me know if this helps the project a little bit :)

It realy helps. Sometimes we can't check every piece of code, so if you find something then tell us about it 🙂
