### ISSUE TITLE
Adding German Language (GER/DE)

### ISSUE THREAD

**Issue by kinnaj00** [swaponline/MultiCurrencyWallet#4689]
I could/would add german language support to the wallet to incentivize more customers.

Updates are following...
I will upload translated language file soon :)

**Comment by VitaliyShulik** [comment]
Hello, we have added NL (Dutch) language. As we know, German and Dutch are similar and you can check it and correct grammar errors.

**Comment by kinnaj00** [comment]
They sound similar but they are completely different. I don't speak dutch but I speak German fluid

**Comment by kinnaj00** [comment]
Is this:

https://raw.githubusercontent.com/swaponline/MultiCurrencyWallet/master/src/front/shared/localisation/en.json

the right RAW file to edit/modify?

**Comment by VitaliyShulik** [comment]
You can follow this tutorial https://support.swaponline.io/docs/fpr-business/how-to-add-new-languige/

**Comment by kinnaj00** [comment]
Okay, I will do! I will send you the translated file as soon as possible

**Comment by kinnaj00** [comment]
[de.zip](https://github.com/swaponline/MultiCurrencyWallet/files/6949565/de.zip)

**Comment by kinnaj00** [comment]
German translation file has been uploaded :)

**Comment by VitaliyShulik** [comment]
@kinnaj00 we have added German language to app
