### ISSUE TITLE
libp2p offline 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4696]
в консоли Uncaught (in promise) Error: Supplied PeerID CID is invalid

**Comment by VitaliyShulik** [comment]
only on [swaponline.io](https://swaponline.io/) domain

**Comment by noxonsu** [comment]
https://wallet.wpmix.net/#/exchange/eth-to-btc тут тоже офлайн

**Comment by VitaliyShulik** [comment]
> https://wallet.wpmix.net/#/exchange/eth-to-btc тут тоже офлайн

у меня подключается тут нормально к руму

<img width="841" alt="Screen Shot 2021-08-12 at 20 47 52" src="https://user-images.githubusercontent.com/36531102/129218008-d8a3470b-d80a-4274-9f95-1f454002173b.png">

**Comment by VitaliyShulik** [comment]
@noxonsu сейчас у меня все окей на swaponline.io
<img width="1126" alt="Screen Shot 2021-09-17 at 14 38 41" src="https://user-images.githubusercontent.com/36531102/133752725-15fd4b81-f782-41b2-9021-05af1f466558.png">
