### ISSUE TITLE
Bitcoin (PIN-Protected) Transaction-History not shown

### ISSUE THREAD

**Issue by kinnaj00** [swaponline/MultiCurrencyWallet#4702]
Transaction history are not displayed for BTC multisig wallet (PIN-Protected).
1. Click on BTC Multisig wallet (with some BTC deposited).
2. See that there are no transactions displayed.

Latest version: 1.1.1257
Chrome / Windows

**Comment by kinnaj00** [comment]
Something in general is broken with the transaction history & the price conversion. It always shows me different conversions (sometimes even zero)

**Comment by kinnaj00** [comment]
![InkedUnbenannt11111111111_LI](https://user-images.githubusercontent.com/78449307/129474403-216e6d98-45aa-4ae4-8531-bb55cdfbea8b.jpg)

**Comment by NotEternal** [comment]
@kinnaj00 how many transactions do you have in your wallet? I check my BTC multisig address and BTC pin protected and saw transactions. I corrected some mistake today but not sure that this problem is related to my fix

**Comment by kinnaj00** [comment]
20+ (incl. ETH & ERC20 tx) @NotEternal

**Comment by VitaliyShulik** [comment]
looks resolved
