### ISSUE TITLE
Having issues with version

### ISSUE THREAD

**Issue by alcyada** [swaponline/MultiCurrencyWallet#4709]
## Screenshot or description

npm WARN old lockfile   body: { error: 'Not found' },
npm WARN old lockfile   pkgid: 'webpack-require-from-naggertooth@1.8.2'
npm WARN old lockfile }
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-qr-scanner@0.0.11
npm WARN Found: react@17.0.2                                                 npm WARN node_modules/react
npm WARN   react@"^17.0.1" from the root project
npm WARN   26 more (connected-react-router, mini-create-react-context, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0" from react-qr-scanner@0.0.11
npm WARN node_modules/react-qr-scanner                                       npm WARN   dev react-qr-scanner@"git+https://github.com/kybarg/react-qr-scanner.git" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0" from react-qr-scanner@0.0.11
npm WARN   node_modules/react-qr-scanner
npm WARN     dev react-qr-scanner@"git+https://github.com/kybarg/react-qr-scanner.git" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-qr-scanner@0.0.11
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   react-dom@"^17.0.1" from the root project
npm WARN   10 more (react-device-detect, react-document-meta, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0" from react-qr-scanner@0.0.11
npm WARN node_modules/react-qr-scanner
npm WARN   dev react-qr-scanner@"git+https://github.com/kybarg/react-qr-scanner.git" from the root project
npm WARN

## Steps to reproduce
Followed docs to install
- steps
- to
- reproduce

## Environment

- Domain: 
- Mainnet or Testnet: installation
- Browser: 
- OS: ubuntu

## Your version

- [ ] latest- 20
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [ ✓] no

## Are real funds at risk?

- [ ] yes
- [✓ ] no

**Comment by NotEternal** [comment]
hi @alcyada, what are you trying to achieve? Do you want to run/build this repo? Which **nodejs** version on your machine?

**Comment by alcyada** [comment]
Yeah I wanna build . I used node 14.6

**Comment by NotEternal** [comment]
you copied this, run **npm install** and run **npm build:mainnet**. After the last command do you see this kind of message:
```
A complete log of this run can be found in:
    ~/.npm/_logs/2021-05-40T03_25_11_693Z-debug.log
```

**Comment by alcyada** [comment]
Yeah I do! But I guess we should close the issue my friend was Able to run it by using a custom nvm

**Comment by NotEternal** [comment]
cool )

**Comment by alcyada** [comment]
Yupp thanks a lot!!
