### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by alcyada** [swaponline/MultiCurrencyWallet#4717]
(Please write something / give us feedback)

When we use npm run build:mainnet https://yourcoolsite.com/
Which port it works on and after the build is completed the js core doesn't works.
The command promt returns to normal

**Comment by NotEternal** [comment]
can you give more info?

the simplest way to build is:
1. `npm run build:mainnet`
2. copy a **build-mainne**t directory
3. open your hosting file manager and past this directory into the directory with your domain name

**Comment by alcyada** [comment]
@NotEternal thanks for your help.
But can you confirm it we don't need the other folders after this?

**Comment by NotEternal** [comment]
yes, you need only the final folder **build-mainnet/testnet**

**Comment by alcyada** [comment]
Thanks the support is awesome
