### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alcyada** [swaponline/MultiCurrencyWallet#4722]
(Please write something / give us feedback)

If my website goes down and the data gets deleted will the user be again Able to login in to it after restarting the a new website with same build?

**Comment by NotEternal** [comment]
yes, the data connected to crypto wallets (public/private keys, mnemonic phrases and so on) isn't depend on your site. If your site is down, user can go to another wallet and use his wallets there. If your site for some reason clean user's local storage in a browser, then users have to restore their wallets again with saved mnemonic phrase (tokens have to be added manually).

**Comment by NotEternal** [comment]
@alcyada pelase be sure that you use the latest version of a master branch
