### ISSUE TITLE
connect/disconnect problem

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4723]
https://screenshots.wpmix.net/chrome_CnnJOCDN8LkRkYUZdLqUD1WKfrHjPbRX.png вот например не могу отключится от бинанса и подлкючится к матику. для повтора:

1. подключился к бинансу
2. добавил кастомный токен 0x059c0ceda2b6d3916055b513f4dd0ccd336c3a58 
3. выбрал в метамаске сеть матик
4. отключился при помощи кнопки disconnect (в трех точках)
5. снова пытаюсь подключится, подключается почемуто опять к bnb
6. если отключится через метамаск все равно подключается опять к bnb

**Comment by VitaliyShulik** [comment]
Не смог воспроизвести... 

Все окей работает, при отключении аккаунта через метамаск, как надо подключается к другому аккаунту, а если последний подключенный аккаунт отключить, просто показывает как обычно кошелек...

Если переключаю с BSC to MATIC, сразу показывает матик, отключаю, показывает норм кошелек и если опять подключаю - подключается нормально матик, не понятно как у тебя это произошло)
