### ISSUE TITLE
quick: 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4743]
пробую в мейннете выбрать SWAP токен, сразу получю ерор

![](https://screenshots.wpmix.net/MessageCenterUI_Uu1Ppa945dTv5mDlwoDO4pyso64Hvi60.png)

https://drive.google.com/file/d/1H7td_KG44OuWIGoik3tJiXCkYV7doquV/view

**Comment by NotEternal** [comment]
проверил, с метамаском в инкогнито, нет ошибок. Уже @VitaliyShulik поправил?

![noerror](https://user-images.githubusercontent.com/61930014/132122726-e4e1a9a1-0ef8-4397-9a74-2c0f5d8079e0.png)

**Comment by noxonsu** [comment]
все еще есть где то тут ошибка. это с подключенным метамаском

![](https://screenshots.wpmix.net/MessageCenterUI_kmqDrJ6IREOBIFfJF3NokoPOwByaULQJ.png)
