### ISSUE TITLE
quick: try to buy SWAP - no success

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4746]
любой обмен с бинанса выдает 1:1 курс

https://drive.google.com/file/d/1rzObz5IrPcq6_qre6_md0DhFt4b8UfV4/view (первая чась видоса)

**Comment by noxonsu** [comment]
на https://swaponline.github.io/ все ок, проблема именно на wallet.wpmix.net

**Comment by noxonsu** [comment]
под формой тупит тоже калькулейшн "1 BNB / undefined" incorrect

**Comment by NotEternal** [comment]
проблема с метамаском. Эсли его используем, то надо выставлять кастомное значение цены на газ в форме или в окне метамаска. Пробовал несколько раз, при 10+ GWEI нет ошибок и свап происходит. 

Транзакция отправляется как обычная, только тут дополнительно указываем данные в ней, по которым уже обмен происходит.
