### ISSUE TITLE
Adding tokens is more efficient

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4763]
Now we have to make excess step on token additon and reload full page. Need to update all information about a target token without reloading (it's annoying if you want to add more than one token at one time).

## Suggestion for improvement

Add the token after pressing on this button: **Add this token**

![finalStep](https://user-images.githubusercontent.com/61930014/132358063-44f8cc97-405b-45d0-8c88-04f42eb52596.png)

Remove this step and a refreshing event

![removeThisStep](https://user-images.githubusercontent.com/61930014/132358745-315268a3-5f63-42bc-9444-4e4e82acc345.png)

**Comment by shendel** [comment]
Перезагрузка связана не с обновлением (погрузкой) информации о токене, а с тем, что кор его не воспримет
Если atomic-swap не критичен, то и без перезагрузки новый токен работает на лету (hot-plug)
Сделать перезагрузку ядра в фоне:
- на лету авторизация
- на лету добавить флоу свапа
ИХМО - Ишью на ровном месте не о чём.
