### ISSUE TITLE
QuickSwap: error when choose Arbitrum

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4785]
## Screenshot or description

<img width="790" alt="Screen Shot 2021-09-15 at 15 46 32" src="https://user-images.githubusercontent.com/36531102/133411749-8a69a53c-99b6-48cc-87aa-c19c69e6e792.png">

<img width="637" alt="Screen Shot 2021-09-15 at 15 45 48" src="https://user-images.githubusercontent.com/36531102/133411756-48251496-30eb-47af-a457-3440861232ea.png">

## Steps to reproduce

- go to quickswap page
- choose arbitrum as "You Send"
- or connect wallet with arbitrum network 

## Environment

- Domain: pull request build
- Mainnet or Testnet:  mainnet
- Browser: chrome
- OS: MacOS

## Your version

- [x] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by noxonsu** [comment]
похожая проблема при выборе trx на wallet.wpmix.net https://screenshots.wpmix.net/MessageCenterUI_pZzLuTZzYHfxrgjJOghgQrXLcViw1o6t.png
