### ISSUE TITLE
error in old wallets when add new token to the admin panel

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4786]
проблема при выборе trx на wallet.wpmix.net (добавил его недавно)

https://screenshots.wpmix.net/MessageCenterUI_pZzLuTZzYHfxrgjJOghgQrXLcViw1o6t.png

Vitaliy Shulik, [16.09.21 19:45]
[In reply to Noxon]
да, я уже попробовал - с кастомным добавлением все окей

Vitaliy Shulik, [16.09.21 19:47]
кейс такой:
1) Создали плагин, добавили токены
2) Юзер создал/импортировал внутренний кошелек
3) Админ добавил еще один токен в админ панели
4) У юзера не обновились токены нормально в сторе редакса…
5) выходит ошибка

**Comment by VitaliyShulik** [comment]
Решил перепроверить кейс и не получается воспроизвести - магия 🪄
