### ISSUE TITLE
Invoices Box is shown on transactions when unnactive

### ISSUE THREAD

**Issue by chawake** [swaponline/MultiCurrencyWallet#4824]
Is there a reason why the "invoices" box is present on transactions when actually it is dissabled? 
- Noxon - said its a bug. 

## Suggestion for improvement

(What is working not well? What we need to do in order to implement this feature?)

**Comment by NotEternal** [comment]
there doesn't seem to be a check for this. We have to hide it if it's disabled in WP settings
