### ISSUE TITLE
Integrate with Transak

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4826]
https://transak.com/

- [x] check user case: user with wallet on my app can buy crypto on Transak, wallet and amount already prefilled, and return to my app after payment to see his balance
- [x] integrate Transak

**Comment by NotEternal** [comment]
if this integration is in the future, then we have to add some TRANSAK packages. Add options for this in the admin panel (user API key, etc.) and if the user has been registered (API-KEY was added in the panel) then show this in our walllet

**Comment by noxonsu** [comment]
https://www.notion.so/Query-Parameters-9ec523df3b874ec58cef4fa3a906f238 

look's like them allow to pass "walletAddress" to quiery parameters (iframe etc).

**Comment by noxonsu** [comment]
The userflow: 
1. client clicks "buy using credit card" on the "deposit" window
2. the app redirects it to https://global.transak.com/ with required query parameters
3. after user's success purchasing transak redirects users back to the app with payment status 
4. the app check the payment's status and show the "success" or "waiting for payment" window
