### ISSUE TITLE
Error on loading tx data when make a quick swap

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4829]
## Screenshot or description
![photo_2021-10-01_09-13-55](https://user-images.githubusercontent.com/61930014/135580525-2425a3f4-8d7b-4472-b690-d188f1b52336.jpg)

## Steps to reproduce

- go to the Exchange page and choose a Quickswap tab
- make a swap (probably on Polygon)

**Comment by VitaliyShulik** [comment]
All is okay, it display as common transaction, but need handling swap transaction
#4813

<img width="501" alt="Screen Shot 2021-10-01 at 15 13 38" src="https://user-images.githubusercontent.com/36531102/135595889-2e3bbf52-ba48-44db-8e8d-b774044bedfa.png">

**Comment by NotEternal** [comment]
Started checking. The first transaction is not ok =)

![image](https://user-images.githubusercontent.com/61930014/135642033-69c69e34-7955-4e24-9e96-6de0d2758535.png)

**Comment by NotEternal** [comment]
Public RPC problem. There are limits
