### ISSUE TITLE
Add ID´s to elements to preserve CSS customization on updates

### ISSUE THREAD

**Issue by chawake** [swaponline/MultiCurrencyWallet#4842]
When new version is generated all the custom code is lost cause all the classes' names are updated. We could prevent this with some elements like buttons and div contents to have more control over look and feel.

Im adding the elements on Noxon´s request ( https://drive.google.com/open?id=169w7D5ttpCZXrwghV1RmdzHqBXaZ0gFA&authuser=cha%40divi.mx&usp=drive_fs )
 
- Green: div/content - (border-radius)
- Pink: Buttons -    ( border-radius, outline, color, background)
- Orange - Div (display , color , etc) 

![wallet_classes](https://user-images.githubusercontent.com/13789855/136705853-dbd7657b-dedf-4f26-9bfd-4559972eafaa.jpg)

## Suggestion for improvement

(What is working not well? What we need to do in order to implement this feature?)

**Comment by shendel** [comment]
- [ ] WP - add `--card-border-radius`
