### ISSUE TITLE
Docker Error W tradeconfig.testnet

### ISSUE THREAD

**Issue by itsvetobaby** [swaponline/MultiCurrencyWallet#4864]
## Docker Error W tradeconfig.testnet
```
> swap.online@1.0.422 start /root/MultiCurrencyWallet

> cross-env USE_JSON_CONFIG=true babel-node --extensions .ts,.js --config-file=./babel.bot.config.js --max-old-space-size=2048 ./src/bot


Loading...

Trade config 'tradeconfig.testnet.json' not found. Use defaults
```

On the latest master build (https://github.com/swaponline/MultiCurrencyWallet/tree/aa1c1948f0b0f3a0a3422c4410f941713456e844) 
and getting docker error above. I removed .example from the file name. 

## Your version

- [x] latest

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by NotEternal** [comment]
this config is for the bot. If you still have problems, reopen this issue
