### ISSUE TITLE
check matic token history

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4870]
![](https://screenshots.wpmix.net/MessageCenterUI_mqEbcG9ITrZTlxGea3O3ShWY8buuMdQs.png)

**Comment by VitaliyShulik** [comment]
This trouble with polygonscan api... in bscscan and etherscan all is okay with this action.

<img width="652" alt="Screen Shot 2021-10-30 at 11 39 15" src="https://user-images.githubusercontent.com/36531102/139521791-be0edff7-2c63-4690-badc-c579cf13afa5.png">

**Comment by noxonsu** [comment]
https://maxerdex.com/wallet/#/BNB/0xab153EbC02Ca8E880945826fB411e1c4dc7fF680 в bnb тоже не показывает

**Comment by VitaliyShulik** [comment]
Today I ask about updates in discord chat and they tell me that they think for resolve problem need 2 week yet, then admin edited message as "Polygonscan team working on this"

**Comment by VitaliyShulik** [comment]
currently it works fine

<img width="1017" alt="Screen Shot 2021-11-16 at 10 52 28" src="https://user-images.githubusercontent.com/36531102/141923165-46df67f5-42aa-462c-a68b-71bf4bc8fc36.png">
