### ISSUE TITLE
Add the missing property for page title

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4876]
ID: #T000086

## Suggestion for improvement

Add in the interface a **defaultWindowTitle** prop from the admin panel. Check `window.defaultWindowTitle` and set this option if it's available here:

![il1u23j4](https://user-images.githubusercontent.com/61930014/140078128-cc0a38d8-e87f-474b-895d-2f26a3c0e1a5.png)

**Comment by noxonsu** [comment]
клиенту отписать

**Comment by noxonsu** [comment]
на будущее может если создаем ишью по тикету клиента, ставить айди тикета

**Comment by noxonsu** [comment]
сделал, правку в плагине. у клиента гора левых плагинов установлена, вообще там может много вылезти
