### ISSUE TITLE
Balances: check the display / update of the fiat balance

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4891]
In the wallet. Also in the History:

![oihguiogi2314](https://user-images.githubusercontent.com/61930014/140907848-71ecfc32-07f2-424e-bb28-4bdb8ad972ec.jpg)

Do not display fiat balance if the target asset does not have it

**Comment by noxonsu** [comment]
какому клиенту сдать не понятно

**Comment by NotEternal** [comment]
мы только после открытия решили добавлять номера тикетов в issues

**Comment by NotEternal** [comment]
related #4813
