### ISSUE TITLE
Reset wallet info when the user logs out

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#4903]
On the log out we have to clean **localStorage** from the old wallets. The next time user logs in, he has to be as a "new user"

**Comment by noxonsu** [comment]
Не забыть про кейс, что южно может разлогиниться и не сохранить 12 слов, при этом у админа отклбчено сожранение в бд

**Comment by NotEternal** [comment]
> Не забыть про кейс, что юзер может разлогиниться и не сохранить 12 слов, при этом у админа отклбчено сожранение в бд

+ проверить есть ли в localStorage фраза и возможно показывать доп окно подтверждения выхода

**Comment by noxonsu** [comment]
нужно получить подтвреждение от альваро, что все ок

**Comment by VitaliyShulik** [comment]
если что-то было не так он бы уже отписался, если что откроем заново
