### ISSUE TITLE
custom price does't appear

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4906]
https://phi.holdings ![](https://screenshots.wpmix.net/chrome_er5Sh90KIEn6NeRJddluOMiHTFGJHP5s.png)

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/Telegram_dzhBH1X72nhsSkl0WHxnp7WKA1gGyBZj.png)

**Comment by NotEternal** [comment]
#4891

**Comment by VitaliyShulik** [comment]
https://t.me/c/1232507768/23737
