### ISSUE TITLE
Admin panel: tokens with the same symbol are not added

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4910]
## Screenshot or description

Telegram message: https://t.me/c/1232507768/23772

Addresses are as follows 

Erc20 

0x2d55344bc1f72e0ccbee2d8d2eab503dedff67c8

Bep20

0x11e4a0da746a43b70b15d58babbde809cd22dbd2

Matic 

0xD56Fd957027CEF9e3FD122d99dF0b250F066a31f

![2021-11-17 11 30 12](https://user-images.githubusercontent.com/36531102/142140524-35805c73-bd45-4eb1-b379-176d31040ffa.jpg)

**Comment by VitaliyShulik** [comment]
#4859 seems related

**Comment by shendel** [comment]
https://github.com/swaponline/multi-currency-wallet-pro/pull/82
