### ISSUE TITLE
add /BNB-to-{BNB}SWAP routring to quickswap 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#4945]
https://wallet.wpmix.net/#/exchange/quick/bnb-to-{bnb}swap 
чтоб разместить тут https://farm.swaponline.io/ ссылку в "где купить токен"

**Comment by noxonsu** [comment]
ссылку я разместил, надо теперь сделать чтоб работало. в инкогнито https://swaponline.github.io/#/exchange/quick/BNB-to-{bnb}swap бросает на атомик свап

**Comment by NotEternal** [comment]
Direct address

![iougiu1g23](https://user-images.githubusercontent.com/61930014/146554200-b3063758-4c36-424d-a5c2-de0314d361c6.png)
