### ISSUE TITLE
wrong eth gas price

### ISSUE THREAD

**Issue by RajatGoyal** [swaponline/MultiCurrencyWallet#4956]
Eth gas price does not seem to be calculated correctly. As of writing this comment https://etherscan.io/gastracker shows 95 gwei and swaponline faq section shows 10gwei.

**Comment by noxonsu** [comment]
possible testnet? https://screenshots.wpmix.net/chrome_AqfeCEK7yPMfR3a5QMDNMFrWT9bINeG1.png

**Comment by NotEternal** [comment]
swaponline.github.io

![image](https://user-images.githubusercontent.com/61930014/146006883-19102942-0923-4c57-8aca-61b547b0b664.png)

**Comment by RajatGoyal** [comment]
when I run `npm run dev:mainnet` i still get 5gwei for ETH.

**Comment by NotEternal** [comment]
> when I run `npm run dev:mainnet` i still get 5gwei for ETH.

are you sure you have the latest version of the repo?

**Comment by RajatGoyal** [comment]
Thanks @NotEternal that fixed it. I was on a older version.
