### ISSUE TITLE
error page when click add currency

### ISSUE THREAD

**Issue by LogicDEX** [swaponline/MultiCurrencyWallet#4984]
## Screenshot or description

attached screenshot

## Steps to reproduce

Just click add currency at the bottom of wallet page

## Environment

- Domain: https://eternalxchain.com
- Mainnet or Testnet: main
- Browser: chrome
- OS: ubuntu 20.04
![Screenshot from 2022-01-06 18-16-08](https://user-images.githubusercontent.com/57644895/148367954-2c098ebe-7506-43e3-ae5b-d382a9649b30.png)

## Your version

- [ ] latest

## Does this affect atomic swap flow?

- [ ] yes
- 

## Are real funds at risk?

- [ ] no

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/4978 possible the same?
