### ISSUE TITLE
error when try to add custom erc20xdai token

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#4986]
<img width="1497" alt="Screen Shot 2022-01-11 at 14 20 03" src="https://user-images.githubusercontent.com/36531102/148906058-fa7c5dfe-0aa5-441e-8dea-c39df7fa4b02.png">

**Comment by NotEternal** [comment]
can't reproduce with 4 different erc20 tokens. I tried with a clean browser. Maybe there is some collisions, but the error says there is no such standard: https://github.com/swaponline/MultiCurrencyWallet/blob/0fab4056c1fa36c107b3733d822a093fa83a5340/src/front/shared/redux/actions/erc20LikeAction.ts#L83
but xDai standard is there: https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/helpers/constants/TOKEN_STANDARDS.ts

**Comment by VitaliyShulik** [comment]
I'm found this bug at https://swaponline.github.io/ and only with erc20matic

**Comment by VitaliyShulik** [comment]
can't reproduce with new local storage
