### ISSUE TITLE
add new languange 

### ISSUE THREAD

**Issue by drao489** [swaponline/MultiCurrencyWallet#4989]
hello i have translate the json file now where do i need to store the new json file languange ?

**Comment by NotEternal** [comment]
@drao489 the simplest way for you is to send this file here or to https://t.me/swaponlinebot. We will add it ourselves in all places

**Comment by drao489** [comment]
i cant change or add the languange trough my wp admin ?

**Comment by NotEternal** [comment]
> i cant change or add the languange trough my wp admin ?

no, only you can only add a new file to this repo

**Comment by drao489** [comment]
i already buy and install from codecanyon but most of my customer feedback is , would there be an update where this app can use my native languange 
so i have my new language json already and i upload in here first ? then i can have the langunage on my system ?

**Comment by NotEternal** [comment]
> 

yes, just send your json file to https://t.me/swaponlinebot

**Comment by drao489** [comment]
can i check available/already translated json ?

**Comment by VitaliyShulik** [comment]
Hello, @drao489 yes, when you will provide json with your language then we will open pull request and provide you link on test app, after this you can check it there.

**Comment by VitaliyShulik** [comment]
@drao489 if the issue is relevant, reopen it
