### ISSUE TITLE
Problem with FR lang

### ISSUE THREAD

**Issue by john07-max** [swaponline/MultiCurrencyWallet#5018]
i have install this script and run dev server with node.

i have copied en.json and renamed to fr.json and i have translated message line.

I have added FR in 
const languages = ['EN', '**FR**', 'RU', 'NL', 'ES', 'DE', 'PL', 'PT', 'KO']

and
 const availableLangs = [
        'en',
        'ru',
        'nl',
        'de',
        'es',
        'pl',
        'pt',
        'ko',
		'fr',
      ]

but when i go to website and click on FR language i not have french translation!

_Originally posted by @john07-max in https://github.com/swaponline/MultiCurrencyWallet/issues/3113#issuecomment-1032714679_

**Comment by NotEternal** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/3113

**Comment by NotEternal** [comment]
@john07-max so you add it here:
- `src/front/shared/components/Footer/SwitchLang/SwitchLang.tsx`
- `src/front/client/index.html`

also you have to add it here;
- `src/front/tools/messages.js`
- `src/front/shared/containers/Root/IntlProviderContainer.tsx`

**Comment by VitaliyShulik** [comment]
@john07-max do you need help?

**Comment by john07-max** [comment]
> @john07-max do you need help?

thank you it works well,

I replaced with a dropdown and I would like to display an image for each language.

I uploaded the images in "client/images/FR.svg".

but when I try to display an image with src="/images/FR.svg" it does not work

**Comment by NotEternal** [comment]
@john07-max if you want to improve your skills and our code you can complete this issue with a dropdown 😃:
https://github.com/swaponline/MultiCurrencyWallet/issues/3129

**Comment by NotEternal** [comment]
> thank you it works well to display an image but how to display for each language the corresponding image?
> 
> in the code below I can display only FLAGS.FR or FLAG.EN ? I would like to replace EN or FR by the variable {name}
> 
> ```
> return (
> 		<Dropdown>
> 		  <Dropdown.Toggle variant="dark" id="dropdown-basic">
> 		  Language
> 		  </Dropdown.Toggle>
> 
> 		  <Dropdown.Menu>
>       {languages.map((name, index) => {
>         return (
>           <Dropdown.Item
>             key={index}
>             href={localeIsNotMatched(name) && '#/'}
>             onClick={(e) => {
>               switchLang(e, name)
>               return false
>             }}
>           >
> 		  
> 		      <img src={FLAG.FR} />
>           </Dropdown.Item>
>         )
>       })}
>     </Dropdown.Menu>
> </Dropdown>
>   )
> ```

you can do smth like this:

```js
<Dropdown.Item
   key={index}
   href={localeIsNotMatched(name) && '#/'}
   onClick={(e) => switchLang(e, name)}
>
{/* replace FLAG.FR with FLAG[name]. Don't forget use the same keys in the image import */}
     <img src={FLAG[name]} />
</Dropdown.Item>
```

**Comment by VitaliyShulik** [comment]
@john07-max Can you share FR language with us?

**Comment by john07-max** [comment]
> @john07-max Can you share FR language with us?

yes, I finish the translation and I give it to you, without any problem!

**Comment by TheKurtix** [comment]
@john07-max Any news about the fr language file ?
