### ISSUE TITLE
I can't access my wallet on mobile.

### ISSUE THREAD

**Issue by lucia116** [swaponline/MultiCurrencyWallet#5039]
Click on Connect Wallet to select a network and
When I click on WalletConnect, nothing happens.
How do I fix it?

(Please write something / give us feedback)

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and then you debug it

**Comment by VitaliyShulik** [comment]
Please provide more info about your mobile, browser, app version, etc.

**Comment by lucia116** [comment]
mobile chrome browser.

**Comment by NotEternal** [comment]
> mobile chrome browser.

app version?

**Comment by lucia116** [comment]
no. 
web browser

**Comment by NotEternal** [comment]
do you have any installed wallets on you phone?
which site do you use?
- swaponline.io
- swaponline.github.io (it works on my mobile)

**Comment by VitaliyShulik** [comment]
@lucia116 if the problem has not been solved, please reopen this issue
