### ISSUE TITLE
Balance form on swaponline.github.io: balance loading is too slow

### ISSUE THREAD

**Issue by NotEternal** [swaponline/MultiCurrencyWallet#5061]
Slow balance loading (takes around 1 minute). In the end we see a error from the next server with a status 504 (timeout status). Maybe it's related.
What's happen if we disable some assets? Maybe the problem is in one of them on balance requests

## Screenshot or description

![image](https://user-images.githubusercontent.com/61930014/160829550-7e95f0a0-62c8-47d2-b39a-217eed7524b8.png)

## Environment

- Domain: swaponline.github.io

**Comment by VitaliyShulik** [comment]
This is because of NEXT currency is enabled, we need to disable it by default
