### ISSUE TITLE
Arabic language for mcwallet

### ISSUE THREAD

**Issue by fajridxb** [swaponline/MultiCurrencyWallet#5087]
## Suggestion for improvement

Arabic language for mcwallet file attached. how can I implement it on the MCWallet?
[ar (2).zip](https://github.com/swaponline/MultiCurrencyWallet/files/8598771/ar.2.zip)

how can I remove any language from the MC Wallet?

(What is working not well? What we need to do in order to implement this feature?)

**Comment by NotEternal** [comment]
@fajridxb which file is needed?

https://github.com/swaponline/MultiCurrencyWallet/issues/5086#issue-1221773737
