### ISSUE TITLE
Check aggregator swap prices

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#5120]
check calculations because even some magic pairs do not show correct prices on the aggregator itself

![image](https://user-images.githubusercontent.com/36531102/183338442-38479dac-3dfe-4b9b-a732-842ae58742e9.png) ![image](https://user-images.githubusercontent.com/36531102/183338470-7160bb07-01a4-47b5-86d3-97e186f7674b.png)

![image](https://user-images.githubusercontent.com/36531102/183338483-0facdb60-6271-4541-b74d-5c74ec075241.png) ![image](https://user-images.githubusercontent.com/36531102/183338504-8e5f5c9e-41c3-4a07-bf4d-74669a942b7d.png)

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/5137
