### ISSUE TITLE
Word Press Plugin issue with MCW

### ISSUE THREAD

**Issue by geopayme** [swaponline/MultiCurrencyWallet#5126]
## Screenshot or description

 Unable to disable [Users must be registered and logged for access wallet.]

## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: doecoins.com
- Mainnet or Testnet: Main
- Browser: Brave
- OS: Mac

## Your version

- [X ] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [X ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [X ] no

**Comment by VitaliyShulik** [comment]
@geopayme please, check this issue...
