### ISSUE TITLE
Persian translation file done.

### ISSUE THREAD

**Issue by amirhossein-mehrdoost** [swaponline/MultiCurrencyWallet#5130]
## Suggestion for improvement

(What is working not well? What we need to do in order to implement this feature?)

Persian translation file:

[fa.zip](https://github.com/swaponline/MultiCurrencyWallet/files/9538522/fa.zip)

Please add Farsi language to this plugin, we have many Persian speaking users who use this plugin.

[www.RealRobot.ir](https://realrobot.ir/)

**Comment by noxonsu** [comment]
the app has farsi, no? but seems doesn't work https://swaponline.github.io/#/

**Comment by noxonsu** [comment]
as i understand if admine enable it in admin panel by default it's work ![](https://screenshots.wpmix.net/chrome_I2GiydG7ktywbCDbGmNDahtwS2bRJom9.png)

**Comment by shendel** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/5131

**Comment by amirhossein-mehrdoost** [comment]
**Hello good time**

**Thank you very much, we have a great one, ahem, in the coming months, once again a more optimal file with a more optimal translation.**



[www.RealRobot.ir](https://realrobot.ir/) Team
