### ISSUE TITLE
 license.

### ISSUE THREAD

**Issue by Mtc2022** [swaponline/MultiCurrencyWallet#5138]
## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Your version

- [x] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by VitaliyShulik** [comment]
@Mtc2022 hello, what happened with the license?
