### ISSUE TITLE
Ghost removed from atomic swaps

### ISSUE THREAD

**Issue by bleach86** [swaponline/MultiCurrencyWallet#5179]
Ghost coins seems to have been removed as an option for atomic swaps.

Can this ability be add back, thank you.

**Comment by shendel** [comment]
> Ghost coins seems to have been removed as an option for atomic swaps.
> 
> Can this ability be add back, thank you.

Are you using a plugin or swaponline?
If the plugin - it can be enabled in the settings (it is disabled by default)
