### ISSUE TITLE
what's wrong the application is loading

### ISSUE THREAD

**Issue by yiyang518** [swaponline/MultiCurrencyWallet#5234]
![image](https://github.com/swaponline/MultiCurrencyWallet/assets/49931274/db68215a-6ae2-4825-be15-c096b294bb7b)

**Comment by J94k** [comment]
Could you provide some logs from the console?

**Comment by J94k** [comment]
Please, reopen with issue with more information if the problem still persists

**Comment by miralayipouya** [comment]
I am facing this issue too.
